### ISSUE TITLE
Check ...should().beAssignableFrom(...) for classes ....that().implement(...)

### ISSUE THREAD

**Issue by HWelling** [TNG/ArchUnit#1002]
What I have is similar to this: 

```java
public interface Vegetable {
// ...
}

public abstract class AbstractVegetable implements Vegetable {
// ...
}

public abstract class AbstractPieable {
// ...
}

public class Pumpkin extends AbstractPieable implements Vegetable {
// ...
}

public class Scallop extends AbstractVegetable {
// ...
}
```

What I wanted to test is that every class that implements the Interface _Vegetable_ should also extend _AbstractVegetable_:

```java
@ArchTest
static final ArchRule implementingInterfaceAndAbstractVegetable =
    ArchRuleDefinition.classes()
        .that().implement(Vegetable.class)
        .should().beAssignableFrom(AbstractVegetable.class);
```
 
This now gives me two violations: _Pumkin_ as i expected, but also _Scallop_ what shouldn't be a case, because it is extending _AbstractVegetable_.
I tried the same with the other abstract _AbstractPieable_ to make sure the problem is not the hierarchy of _Vegetable_ and _AbstractVegetable_ but it leads to the a similar result:

```java
@ArchTest
static final ArchRule implementingVegetableAndExtendsPiable =
    ArchRuleDefinition.classes()
        .that().implement(Vegetable.class)
        .should().beAssignableFrom(AbstractPieable.class);
```

Now violations given are: _AbstractVegetable_ and _Scallop_ as I would expect, but also _Pumkin_. 
For antoher verification I tried to switch the checks: 

```java
@ArchTest
static final ArchRule extendsPiableAndImplementingVegetable =
    ArchRuleDefinition.classes()
        .that().areAssignableFrom(AbstractPieable.class)
        .should().implement(Vegetable.class);
```

This works as expected but doesn't represent my case.

**Comment by hankem** [comment]
Use [`should().beAssignable`**`To`**](https://javadoc.io/doc/com.tngtech.archunit/archunit/latest/com/tngtech/archunit/lang/syntax/elements/ClassesShould.html#beAssignableTo(java.lang.Class)) to test that every class that `implements Vegetable` also `extends AbstractVegetable`:
```java
@ArchTest
static final ArchRule implementingInterfaceAndAbstractVegetable =
    ArchRuleDefinition.classes()
        .that().implement(Vegetable.class)
        .should().beAssignableTo(AbstractVegetable.class);
```
For example, if `class Tomato implements Vegetable` and you have a `Tomato tomato`, you can have the assignment:
```java
AbstractVegetable vegetable = tomato;  // Tomato should be a subtype of AbstractVegetable!
```

[`should().beAssignable`**`From`**](https://javadoc.io/doc/com.tngtech.archunit/archunit/latest/com/tngtech/archunit/lang/syntax/elements/ClassesShould.html#beAssignableFrom(java.lang.Class)), on the other hand, would require that for any `AbstractVegetable vegetable`, you can have the assignment:
```java
Tomato tomato = vegetable;  // Should Tomato really be a supertype of AbstractVegetable???
```
You can see that this is not the rule you intended to write (and that it will report all subtypes of `AbstractVegetable`).

I must admit that thinking about "assignable to vs. from" or "super- vs. subtypes" gives me a headache, too – but I usually need `should().beAssignableTo`. 😉

**Comment by HWelling** [comment]
beAssignableTo is what I was looking for
