### ISSUE TITLE
[suggestion] sort violations in guid files alphabetically

### ISSUE THREAD

**Issue by danhaywood** [TNG/ArchUnit#1026]
Sorting the violations in the guid files would make changes to them easier to review.

**Comment by codecholeric** [comment]
Can you give me an example, where this is not the case? Because i.g. the violations are sorted lexicographically I think, at least the code to create the failure report (which get's stored in the violation store) is created via 

```
violations.stream()
  .flatMap(event -> event.getDescriptionLines().stream())
  .sorted(natural())
  .collect(toImmutableList());
```

So in most typical cases this should be sorted :thinking:

**Comment by danhaywood** [comment]
We have a stored.rules file per maven module.  Here's one of them:

[image: image.png]

**Comment by codecholeric** [comment]
Did something go wrong with the image upload? At least I can't see the image, I just see `[image: image.png]` without any possibility to click on it :thinking:

**Comment by danhaywood** [comment]
Hi Peter - not sure what happened with that image upload.  But I'll close this ticket, I suspect it may be invalid.  I have a different proposal to raise, I'll do that in a new ticket.
