### ISSUE TITLE
Revise log levels

### ISSUE THREAD

**Issue by odrotbohm** [TNG/ArchUnit#1038]
Importing class files currently writes a lot of `DEBUG` output to the console, as most loggers default to `DEBUG` log level. Especially in Spring Boot applications, that usually configure their integration test log levels via `application.properties` adding a configuration file dedicated to the logging library causes the Boot log configuration to back off, as that now expects *all* logging to be configured in that file. Ideally, I'd like to see ArchUnit to not produce any output, except logging explicitly configured to.

It would be nice if the following steps were taken:
* Lower the log levels in `PluginLoader` for the Java version detection to `TRACE`.
* Lower the log levels in `UrlSource`, `ArchConfiguration` and `JavaClassProcessor` to `TRACE`.

**Comment by codecholeric** [comment]
Yes, I got you :joy: Should probably have done this a long time ago just to avoid the discussion :man_shrugging: I just always had the feeling that "taking `archunit.properties` from path x" is a different quality than "importing method foo". And setting everything to `TRACE` will effectively not allow to distinguish by level anymore. But I guess it's always possible to just to a category based configuration :man_shrugging: I'm gonna adjust it...

**Comment by odrotbohm** [comment]
Thanks! 🫶
