### ISSUE TITLE
Rule for checking if a class as an associated test class

### ISSUE THREAD

**Issue by esfomeado** [TNG/ArchUnit#1041]
Hello,

First of all thanks for this amazing library.

I would like to create a rule that checks if a class as an associated test class. The test class will be have `Test` at the end of the name.

I tried a few things but neither of them worked. Is this possible to achieve? 

Thanks

**Comment by hankem** [comment]
See https://stackoverflow.com/a/75075942/13134095.

**Comment by esfomeado** [comment]
Thank you. I was trying to use a custom condition as well but I was not getting the same results but I saw why after your response.

Thanks again.
