### ISSUE TITLE
Comment Regarding Generic Type Possibly No Longer Relevant

### ISSUE THREAD

**Issue by raphaelNguyen** [TNG/ArchUnit#1049]
https://github.com/TNG/ArchUnit/blob/2c183aa14b416ab20bde2f9ad0023c23a9c37f5a/archunit/src/main/java/com/tngtech/archunit/core/domain/JavaField.java#L53-L61

When I called `getType()` on a field declared with generic types, `List<String> field`, I get back a `JavaType` object that is also an instance of `JavaParameterizedType` (actual class is `ImportedParameterizedType`) and describe the generic class sufficiently.

Is that what this comment is referring to, and if so, is this comment still relevant?

I was looking for a way to find the actual parameter type of a generic type field, found this comment which seems to indicate that it was not yet implemented but a bit of practical experimentation (screenshots below) seems to show that it does. Now I'm a bit confused.

Thank you for your time.

![image](https://user-images.githubusercontent.com/42530075/214173527-c4e97e88-df25-4e95-a55d-070a6050d29b.png)
![image](https://user-images.githubusercontent.com/42530075/214173385-e419057c-9f77-44e5-9297-3806896be396.png)

**Comment by codecholeric** [comment]
Really sorry for the confusion, you're right, the comment is outdated! I've added a fix into this PR [d4fc2b5](https://github.com/TNG/ArchUnit/pull/1050/commits/d4fc2b5340082919dcdaacee90648262adabf3bb) (as it's just some minor docs change).
