### ISSUE TITLE
Check all subpackages for cycles?

### ISSUE THREAD

**Issue by arthware** [TNG/ArchUnit#106]
Hi, 

I am currently testing ArchUnit to detect and prevent package cycles in our modules - thank you for the project and the good documentation!

However, I couldn't really figure out how to write a rule that checks all packages under a given package must be free of cycles.

The given example in the doc only checks 'api' package only, but does not go deeper.
```
SliceRule rule = SlicesRuleDefinition.slices()
         .matching("com.actico.dependency.management.api.(*)..").should().beFreeOfCycles();
```
What I really need is to define a rule that checks all sub-packages  of _com.actico.dependency.management.api_ to be free of cycles.

In Degraph it simply looks like this: _com.actico.dependency.management.api.(*).**_

Thanks for your help!

**Comment by codecholeric** [comment]
I think what you want, is

```
slices().matching("com.actico.dependency.management.api.(**)").should().beFreeOfCycles()
```

Two stars captures an arbitrary number of packages, so each combination of packages (like `api.foo`, `api.bar.baz`) will become it's own slice and will thus be checked for cycles.

Is this what you want?
I've added this example to the docs -> https://www.archunit.org/userguide/html/000_Index.html#_slices

**Comment by arthware** [comment]
Works perfect, thank you very much! :-)

**Comment by codecholeric** [comment]
Thanks, glad to hear it :smiley:
