### ISSUE TITLE
Question regarding ArchUnit for Groovy systems

### ISSUE THREAD

**Issue by gernotstarke** [TNG/ArchUnit#107]
when using ArchUnit for a Groovy-based system, all rules always evaluate
to "green", although violating dependencies exist in code...

Any idea how to debug such a situation? Most likely I misconfigured something.

Example: one of the rules:

```
@Before
    public void importClasses() {
        classes = importer.importPackages("org.aim42");
    }


 @Test
    public void check_should_not_access_html() {
        ArchRule rule = noClasses()
                .that()
                .resideInAPackage("..check..")
                .should()
                .accessClassesThat()
                .resideInAPackage("..html..");

        rule.check(classes);
    }
```

and in one class from package "check" I have a method declaration:

`
    protected SingleCheckResults check(final HtmlPage pageToCheck) {
`

where a dependency violating the rule above is contained!

thanx a lot...

**Comment by gernotstarke** [comment]
you're awesome - I'll give that a try.

**Comment by codecholeric** [comment]
I'd be interested to hear about the problems / limitations you run into with everyday coding :wink:

**Comment by gernotstarke** [comment]
tried and (heavily) failed: literally dozens of errors popped up, as our (HtmlSanityChecker) relies on some of Groovys dynamic features...

I'll give up for now (with ArchUnit for Groovy-based systems) - but thanx anyway for your support.

**Comment by codecholeric** [comment]
I was expecting something like that, you should probably just use Scala or Kotlin if you start writing `@CompileStatic` on every class :wink: 
Hmm, too bad, I think it might be possible to retrieve enough info for reasonable tests from bytecode, but it would definitely need some extra logic to consider more context for dynamic invokations...
