### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by joel-costigliola** [TNG/ArchUnit#109]
I have just started using ArchUnit (which looks awesome BTW) but I'm failing to enforce package rules, it is likely a newbie mistake but I can't see it :(

Here's my package rule:

`com.orchestral.health.social.history.validation`  must **not** access `com.orchestral.health.social.history.service`.

I expressed the rule with this test:

```java
package com.orchestral.health.social.history;

import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.noClasses;

import org.junit.runner.RunWith;

import com.tngtech.archunit.junit.AnalyzeClasses;
import com.tngtech.archunit.junit.ArchTest;
import com.tngtech.archunit.junit.ArchUnitRunner;
import com.tngtech.archunit.lang.ArchRule;

@RunWith(ArchUnitRunner.class)
@AnalyzeClasses(packages = "com.orchestral.health.social.history")
public class ArchitectureTest {

  @ArchTest
  public static final ArchRule validation = noClasses()
       .that().resideInAPackage("com.orchestral.health.social.history.validation")
       .should().accessClassesThat().resideInAPackage("com.orchestral.health.social.history.service");
}
```
and the class that I'm expecting to the test to report a violation for:
 
```java
package com.orchestral.health.social.history.validation;

// just here to make my archunit test fail
import com.orchestral.health.social.history.service.SocialHistoryService;

public class ValidationError {

	private final String message;
        // just here to make my archunit test fail
	SocialHistoryService service = null;

	public ValidationError(final String message) {
		this.message = message;
	}

	public String getMessage() {
		return this.message;
	}
}
```

`ValidationError` resides in `com.orchestral.health.social.history.validation` and accesses `SocialHistoryService` which resides in `com.orchestral.health.social.history.service`, that should violate the rule right ?

If I replace `"com.orchestral.health.social.history.service"` by `"java.lang"` in the test I get a violation as expected.

The test belongs to a separate project that depends on the project where `ValidationError` and `SocialHistoryService`  are defined.

**Comment by codecholeric** [comment]
I think your problem is, that `accessClassesThat()` really literally checks for that, i.e. if your class accesses another class. But if you look closely, that is not the case, because your field is unused (as far as I can see).
I would guess, that as soon as you call any method on `SocialHistoryService`, you would get your expected violations.
Other than that, you can make this rule more strict by forbidding any dependency:

```
@ArchTest
public static final ArchRule validation = noClasses()
        .that().resideInAPackage("com.orchestral.health.social.history.validation")
        .should().dependOnClassesThat().resideInAPackage("com.orchestral.health.social.history.service");
```

(notice the `dependOnClassesThat()` instead of `accessClassesThat()`. That should give you a violation because of the field type as well.
Does this help you?

**Comment by joel-costigliola** [comment]
It does help, thanks!

I was actually following the [Package Dependency Checks](https://www.archunit.org/userguide/html/000_Index.html#_package_dependency_checks) first example, I think it should use  `dependOnClassesThat` instead of `accessClassesThat` as you can depend on a type without accessing it as in my (contrived) example.

If you agree with this change, it might be worth it adding an example with `accessClassesThat` to point out te difference with `dependOnClassesThat`.

I'm happy to contribute the doc changes if you want.

Great fluent API, it read really nicely! :+1:

**Comment by codecholeric** [comment]
You are right, this example is a little outdated, I've just changed it -> https://www.archunit.org/userguide/html/000_Index.html#_package_dependency_checks. I think `dependOn` is generally the thing you want to use for this example, and the title is "dependency checks", so I think it makes sense, and it's probably unnecessary to say anything about `accessClasses` there (the ArchUnit examples project shows both of these anyway, and also has comments pointing out the difference -> https://github.com/TNG/ArchUnit/blob/master/archunit-example/example-junit4/src/test/java/com/tngtech/archunit/exampletest/junit4/LayerDependencyRulesTest.java)

I'm glad you like the fluent API :smiley: I'm an enthusiastic long term user of AssertJ, so it's an honor :wink:

**Comment by joel-costigliola** [comment]
Thanks for the kind words and the help!
