### ISSUE TITLE
stop changing the state of instance variables within Spring beans

### ISSUE THREAD

**Issue by arundotin** [TNG/ArchUnit#1118]
I have Spring beans this way

```java
@Service
public class HotelsService {

    public List<Hotel> fetchAllHotels() {
        return dummyHotelsList();
    }
}
```
I should stop my developers to create an instance variable within this bean and start changing the state within the method (see below snippet which i dont want to happen). Need to do this via archUnit. Didn't want to catch this during code review process

```java
@Service
public class HotelsService {
    private int someInteger;

    public List<Hotel> fetchAllHotels() {
        this.someInteger=1; // just for example
        return dummyHotelsList();
    }
}
```
I am ok to have instance variables and just read it. But don't want to write on it. 

Any straightforward implementation in ArchUnit ?

**Comment by hankem** [comment]
See https://stackoverflow.com/q/76375426.

**Comment by arundotin** [comment]
Thanks. This solves the issue. Am closing this
