### ISSUE TITLE
Use with TestNG

### ISSUE THREAD

**Issue by vladdu** [TNG/ArchUnit#112]
I can't find another place where to ask questions.

We are using TestNG in our project and it doesn't recognize JUnit-style ArchUnit tests. Is there a way to make them usable with TestNG, or do we need to implement them in full, as test methods?

**Comment by codecholeric** [comment]
Unfortunately there is no specific support for TestNG yet, so you'd have to write your tests similar to the examples found in https://github.com/TNG/ArchUnit-Examples/tree/master/example-plain/src/test/java/com/tngtech/archunit/exampletest
Most of the API is usable the same way though, the only difference is that you have to take care of caching yourself and you have to call `rule.check(classes)` yourself on the imported classes.

**Comment by vladdu** [comment]
Ok, thank you.
