### ISSUE TITLE
Rule to ensure that implementation is not used

### ISSUE THREAD

**Issue by sysmat** [TNG/ArchUnit#1129]
- is there any rule theClass which implement interface is not used, because we use DI
- something like that

```java
public static final ArchRule IMPLEMENT_INTERFACE_NOT_USED =
            theClass(AvsService.class)
                    .should().implement(AvsInterface.class).???; // not used by classpath
```

**Comment by hankem** [comment]
Did I understand correctly that `AvsService`, which implements `AvsInterface`, should not be used directly? If it's only about `AvsService`, you could probably use something like this:
```java
@ArchTest
ArchRule rule = noClasses().should().dependOnClassesThat().haveFullyQualifiedName(AvsService.class.getName());
```

**Comment by sysmat** [comment]
@thx, but problem is that then it find it in a test file

**Comment by hankem** [comment]
You could replace `AvsService.class.getName()` with the String literal, but then you wouldn't notice when this is renamed/moved, so the better solution is probably to explicitly whitelist the test itself:
```java
@ArchTest
ArchRule rule = noClasses()
        .that().doNotHaveFullyQualifiedName(getClass().getName())
        .should().dependOnClassesThat().haveFullyQualifiedName(AvsService.class.getName());
```

**Comment by sysmat** [comment]
@hankem thx
