### ISSUE TITLE
Tests not firing in my mac terminal

### ISSUE THREAD

**Issue by arundotin** [TNG/ArchUnit#1139]
The test cases are failing in IntelliJ. But when i run `mvn clean install` in my terminal, none of the archunit test cases are failing (genuine failures)

Below is the only log i see

```
[INFO] Running com.paypal.risk.chargebacks.archrules.CommonArchRulesSpec
20:21:01.365 [main] INFO  c.tngtech.archunit.core.PluginLoader - Detected Java version 1.8.0_232
```

This is the archunit depdency i have

```xml
<dependency>
      <groupId>com.tngtech.archunit</groupId>
      <artifactId>archunit</artifactId>
      <version>1.0.1</version>
      <scope>test</scope>
    </dependency>
```

**Comment by hankem** [comment]
We might need a little more information about your situation. How do your tests look like and where are they located?
You don't seem to use [ArchUnit's JUnit support](https://www.archunit.org/userguide/html/000_Index.html#_junit_support), which would require the `archunit-junit4` or `archunit-junit5` dependency, so ArchUnit doesn't even seem to be involved in the test execution.

**Comment by arundotin** [comment]
I figured this out. I added this extra dependency `junit-platform-engine` while my test cases are running using spock (groovy files). IntelliJ somehow loads the test cases. But maven was not running properly due to some conflicts in the engine (i guess).

That said, after i removed this dependency, the test cases are running properly.

```xml
<dependency>
      <groupId>org.junit.platform</groupId>
      <artifactId>junit-platform-engine</artifactId>
      <version>1.9.2</version>
      <scope>test</scope>
    </dependency>
```
