### ISSUE TITLE
ClassFileImporter to read source code

### ISSUE THREAD

**Issue by fcostasilva** [TNG/ArchUnit#116]
First of all, congratulations for this amazing tool!
I would like to check if ArchUnit is suitable for analyzing "raw source code" instead of bytecode. Or if there is a java parser which uses the same metamodel, in order to use the same API for querying.

**Comment by codecholeric** [comment]
Thanks, glad you like it :smiley:
Unfortunately at the moment ArchUnit can only parse byte code and there is no source code parser available.
I've already thought about the advantages to be able to import different sources, which would also be great to apply ArchUnit rules to classes imported from an IDE meta-model, but so far I didn't find the time for it.

**Comment by fcostasilva** [comment]
Being able to analyse source code would broaden the scope of the tool. Sometimes we want to run this kind of checks against different versions of the same application/module/class, for example, and depend on byte code would force us to compile all versions. I agree, though, it takes time to implement this feature. I will invest some time this week to understand how I could help on this. I believe the main principle would be parsing code using a library like Eclipse JDT or Javaparser and then some kind of visitor to navigate through all the nodes and build the corresponding objects of ArchUnit's metamodel.

**Comment by codecholeric** [comment]
Yeah, I think it would be some work though to untangle the bytecode aspects from the import. And there are some features that would not be possible anymore with source code like importing missing classes from the classpath (except for mixing both approaches).

**Comment by codecholeric** [comment]
I'll close this for now. Obviously I can't find the time to approach this and nobody else wanted to pitch in either. I really like the idea, so if anyone wants to tackle this, feel free to reopen!!
