### ISSUE TITLE
Maven builds do not fail for parsing errors with plantUml diagrams

### ISSUE THREAD

**Issue by stefanroeck** [TNG/ArchUnit#1166]
Steps to reproduce
- Have a invalid plantuml diagram and run a @ArchTest
- Use maven surefire 2.x (seems to work with surefire 3.x)

Expected
- Maven build fails

Actual
- Parsing error is logged as warning, but build succeeds

Reproducer repo:
https://github.com/stefanroeck/archunitpumlbug

**Comment by hankem** [comment]
I think that Maven Surefire plugin 2.22.2 requires more configuration to discover JUnit5 tests in general:

If the `pom.xml` only contains the `junit-jupiter-api` dependency and a bare plugin configuration:
```
    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.10.0</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.2</version>
            </plugin>
        </plugins>
    </build>
```
a simple JUnit5 test such as 
```java
class JUnit5Test {
    @org.junit.jupiter.api.Test
    void test() {
      org.junit.jupiter.api.Assertions.assertEquals(1, 2);
    }
}
```
is not picked up:
```
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
```
---

With a `pom.xml` containing the `maven-surefire-plugin:2.22.2` and an explicit `junit-jupiter-engine` dependency:
```
    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.10.0</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.10.0</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.2</version>
            </plugin>
        </plugins>
    </build>
```
_or_ version 3 of `maven-surefire-plugin`:
```
    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.9.3</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0</version>
            </plugin>
        </plugins>
    </build>
```
you will however get:
```
[ERROR] Failures: 
[ERROR]   JUnit5Test.test:7 expected: <1> but was: <2>
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```
---

I'm not exactly sure how the JUnit5 support of the `maven-surefire-plugin` evolved (the answers to [StackOvervflow 36970384: "Surefire is not picking up Junit 5 tests"](https://stackoverflow.com) suggest to me that there have been many changes back then) – and why version `2.22.2` already invokes the `ArchUnitTestEngine`, which tries to instantiate your `PlantUmlArchitectureTest`, which leads to the `java.lang.ExceptionInInitializerError`
```
Caused by: com.tngtech.archunit.library.plantuml.rules.IllegalDiagramException: There is no Component with name or alias = 'invalid'. Components must be specified separately from dependencies.
	at com.tngtech.archunit.library.plantuml.rules.PlantUmlComponents.findComponentWith(PlantUmlComponents.java:51)
	at com.tngtech.archunit.library.plantuml.rules.PlantUmlParser.findComponentMatching(PlantUmlParser.java:121)
	at com.tngtech.archunit.library.plantuml.rules.PlantUmlParser.parseDependencies(PlantUmlParser.java:82)
	at com.tngtech.archunit.library.plantuml.rules.PlantUmlParser.createDiagram(PlantUmlParser.java:50)
	at com.tngtech.archunit.library.plantuml.rules.PlantUmlParser.parse(PlantUmlParser.java:42)
	at com.tngtech.archunit.library.plantuml.rules.PlantUmlArchCondition.create(PlantUmlArchCondition.java:242)
	at com.tngtech.archunit.library.plantuml.rules.PlantUmlArchCondition.adhereToPlantUmlDiagram(PlantUmlArchCondition.java:214)
	at org.example.archunitbug.PlantUmlArchitectureTest.<clinit>(PlantUmlArchitectureTest.java:23)
```
from the
```java
    public static final ArchRule verifyDependenciesFromPlantUmlDiagram =
            classes()
                    .should(adhereToPlantUmlDiagram(requireNonNull(PLANT_UML_DIAGRAM), consideringOnlyDependenciesInAnyPackage("org.example..")));
```
– but I wouldn't worry and just use [the latest version](https://search.maven.org/artifact/org.apache.maven.surefire/surefire) (currently `maven-surefire-plugin:3.1.2`.

**Comment by stefanroeck** [comment]
Thanks @hankem for quick feedback. Even after adding `junit-jupiter-engine` the behavior is strange. While other ArchUnit tests are picked up as expected, the initializating error for the PlantUml test is just logged and the build still succeeds. I [updated ](https://github.com/stefanroeck/archunitpumlbug/commit/0f4e48fa0bcc949c31812424c8e0532c0d6b8dd6) the reproducer repo.
I will look into updating maven-surefire-plugin to 3.x for the project as workaround but am still a bit puzzled because of this odd behavior...

**Comment by hankem** [comment]
Maybe `ArchUnitTestEngine` should handle the `ExceptionInInitializerError` more gracefully? I unfortunately don't know much about the junit5-engine, would have to take a closer look (but don't have the time immediately).

**Comment by codecholeric** [comment]
I think this is more of a Surefire problem. AFAIS it can also happen for JUnit Jupiter for certain Surefire versions, if you manage to create something where a `clinit` class initialization fails -> https://github.com/junit-team/junit5/issues/2386

If I run the test e.g. in IntelliJ it is correctly reported as failed. It seems somewhat reasonable that the whole engine run is aborted if an exception already happens during class initialization, which is unfortunately what happens here due to all the static declarations 🤔 

Anyway, I would close this here for now, because I don't think it's something that ArchUnit can change and it seems to work with Surefire 3.x. But feel free to reopen if you think there is something that needs to be fixed within ArchUnit.
