### ISSUE TITLE
Support for Re-Throw and Wrapping of exception

### ISSUE THREAD

**Issue by vshenbag75** [TNG/ArchUnit#1190]
I would like to check re-throw or wrapping of exception propagate the exception to the higher level.

Example:
```java
try {
    // Some Code
} catch (CustomException1 e) {
    throw new CustomException2("Failed during some operation");  // <-- Violation
}
```
Expectation
```java
try {
    // Some Code
} catch (CustomException1 e) {
    throw new CustomException2(e);  // <-- Valid
}

try {
    // Some Code
} catch (CustomException1 e) {
    throw e;  // <-- Valid
}
```
Any idea how to handle using ArchUnit?

**Comment by hankem** [comment]
I fear that ArchUnit currently (as of version 1.2.0) neither knows about `throw` statements nor that a statement is within a `catch` block, so I don't see a way how to write the test you're looking for.

Depending on your further contraints, there could be workarounds, though. Do your custom exceptions need constructors that don't take another exception? If not, you could write a rule preventing such constructors, and the violation wasn't possible anymore.
