### ISSUE TITLE
Enforce ArchTests when module is depended upon

### ISSUE THREAD

**Issue by lobaorn** [TNG/ArchUnit#1201]
Hey there, I am not sure if this is possible already, if so please just point me to the probable direction.

The question is, in a multi-module project, I wish now to create a common module that will do some orthogonal features, like observability.

If this Module is "M1", and I wish to enforce a convention of classes names, packages, inheritance, interfaces and everything of how "M1" is used in modules that include it as a dependency, how should I do it?

In a Maven context at least, I am not sure if it is possible right now, because the modules that depend on "M1" would just add it, maybe with test scope, but then will it run properly?

I will try it locally in the project, but my guess is that it won't be enough to do it how it is envisioned.

If it works as expected, I believe it will be a great use case to internal frameworks and to enforce conventions for new developers in many contexts (even in open source projects).

**Comment by daniellobaofigueiredo** [comment]
As it seems I will be able to create what is needed using the maven-plugin (https://github.com/societe-generale/arch-unit-maven-plugin), so I think this issue can be closed, and may be useful for someone else with similar needs.
