### ISSUE TITLE
.net port?

### ISSUE THREAD

**Issue by ligu** [TNG/ArchUnit#121]
Hi All,

I like the idea of ArchUnit pretty much, and would like to use something similar for C#/.NET projects.
Googled a bit, but nothing similar found.
Do You guys have any plans or intention to port this lib to .net?

**Comment by codecholeric** [comment]
I'll close this issue, since it's not directly related to ArchUnit and I have unfortunately no further info about a port.

**Comment by BenMorris** [comment]
NB: If it helps, I have authored something similar for .Net Standard:

https://github.com/BenMorris/NetArchTest

I have also posted a discussion around the related issues around [implementing an ArchUnit inspired library for .Net](https://www.ben-morris.com/writing-archunit-style-tests-for-net-and-c-for-self-testing-architectures/).

I am surprised that there hasn't been more activity around this in the .Net space. That said, doing anything more involved than a wrapper around the reflection API is pretty tricky. I used the Mono.Cecil API to handle type-level dependency checking, though Roslyn might be a more promising route once it has better support for loading .Net Standard projects.

Note that there is a LINQ implementation in [nDepend](https://www.ndepend.com/features/cqlinq) which addresses all of this, but that incurs per-seat license fees.

**Comment by ligu** [comment]
@BenMorris thanks for the notes.
We planned using Roslyn, but will look into Your solution too!

**Comment by codecholeric** [comment]
If you want to check dependencies between namespaces, it might be worth to look at https://github.com/realvizu/NsDepCop as well.

**Comment by fgather** [comment]
Hi,
we are currently working on an official ArchUnit.NET port. It is based on Mono.Cecil and will hopefully be open sourced next month. The first version won't have the lang abstraction, but you'll be able to do LINQ-based assertions of your architecture.

**Comment by fgather** [comment]
We just uploaded the first version to NuGet: https://www.nuget.org/packages/TngTech.ArchUnitNET/
The Github repository can be round here: https://github.com/TNG/ArchUnitNET 

We are now working on implementing fluent assertions, as the first release had its focus on making plain LINQ/NUnit possible in an efficient way.
