### ISSUE TITLE
question about calling line numbers

### ISSUE THREAD

**Issue by heyuxiang1996** [TNG/ArchUnit#1257]
I use the dex2jar tool to convert APK to a jar package,then use archunit to scan the calls in the converted jar package, All line numbers for calls are 69
such as:
`Constructor <com.android.settings.ActivityPicker.<init>()> calls constructor <com.android.internal.app.AlertActivity.<init>()> in (ActivityPicker.java:69)`
I want to know the reasons behind this and whether there is a solution to it

**Comment by heyuxiang1996** [comment]
[Uploading SettingsGoogle-dex2jar.zip…]()
这是一个jar包

**Comment by hankem** [comment]
ArchUnit can only use the information available in the byte code, but `dex2jar` might have issues with line numbers, cf. pxb1988/dex2jar#84 / pxb1988/dex2jar#165 / pxb1988/dex2jar#562. Sorry; I fear that ArchUnit cannot solve this "problem".

**Comment by heyuxiang1996** [comment]
> ArchUnit can only use the information available in the byte code, but `dex2jar` might have issues with line numbers, cf. [pxb1988/dex2jar#84](https://github.com/pxb1988/dex2jar/issues/84) / [pxb1988/dex2jar#165](https://github.com/pxb1988/dex2jar/issues/165) / [pxb1988/dex2jar#562](https://github.com/pxb1988/dex2jar/issues/562). Sorry; I fear that ArchUnit cannot solve this "problem".

thank you very much
