### ISSUE TITLE
DependenciesFromSelf does not consider classes referenced in throws-clause

### ISSUE THREAD

**Issue by tngwoerleij** [TNG/ArchUnit#126]
With f761154228c4c2c4b209134073c6a4019b306d67 JavaClass's method [getDirectDependenciesFromSelf()](https://github.com/TNG/ArchUnit/commit/f761154228c4c2c4b209134073c6a4019b306d67?diff=unified#diff-b5c0368e6ab86b282bfd74b185de72a4) was already extended to take many dependencies into account. However, exception classes referenced in the throws-clauses of the class' methods are not yet considered.

We currently have an ArchUnit-test implemented like this
```    
@ArchTest
public static final ArchRule daosShouldNotExposeSql = noClasses().that()
                                                                 .haveSimpleNameContaining("DAO")
                                                                 .and()
                                                                 .areInterfaces()
                                                                 .should()
                                                                 .dependOnClassesThat()
                                                                 .resideInAPackage("java.sql..");
```

Looking at an example DAO implementation, the first two methods fail the test, while the third doesn't.

```
public interface ExampleDAO
{
    java.sql.ResultSet returns();


    void consumes(java.sql.PreparedStatement statement);


    void throwsException() throws java.sql.SQLException;
}
```

**Comment by codecholeric** [comment]
Yes, you're right, this info is still missing. Thanks for raising the issue!!
I would propose to add a class `ThrowsDeclaration` and parse/add this to `JavaCodeUnit` (since constructors and methods can both declare throw statements).
Then once the info is available, it should be trivial to add it to a `JavaClass`' dependencies.
