### ISSUE TITLE
Improve supported PlantUML syntax

### ISSUE THREAD

**Issue by codecholeric** [TNG/ArchUnit#127]
At the moment it's not possible to write

```
[Foo] --> [Bar] : description
```

This would be really useful :wink:

**Comment by aweisser** [comment]
When you already have a valid PlantUML model you can use https://gitlab.com/iternity/jplantuml to transform it into a selfcontained PlantUML URL. ;)

**Comment by codecholeric** [comment]
Thanks for the tip!!
It might be worth mentioning, that you can host this server on premises, e.g. as Docker image -> https://github.com/plantuml/plantuml-server
Since there might be organizations out there that wouldn't want their arch diagrams to be sent to some public server :wink:

**Comment by aweisser** [comment]
Here you go: https://gitlab.com/iternity/jplantuml/commit/9c923e213cb8a72387cf15ac35a5971d6741d3e7

**Comment by codecholeric** [comment]
Oh, I didn't mean that as request for you to implement this, but rather a suggestion for anyone wanting this to support you with a PR!!
But anyway, great that you added support for this so quickly :smiley:
