### ISSUE TITLE
Jakarta Inject package name incorrect in BE_ANNOTATED_WITH_AN_INJECTION_ANNOTATION rule

### ISSUE THREAD

**Issue by bbadjari** [TNG/ArchUnit#1285]
Jakarta's `Inject` annotation package name used for the `BE_ANNOTATED_WITH_AN_INJECTION_ANNOTATION` rule in the `GeneralCodingRules` class is set to `javax.inject.Inject` when it should be `jakarta.inject.Inject`. See the related [API documentation](https://jakarta.ee/specifications/dependency-injection/2.0/apidocs/jakarta/inject/inject).

**Comment by hankem** [comment]
You're right: The rule had been added (#289) before [Jakarta EE9 was introduced](https://en.wikipedia.org/wiki/Jakarta_EE#History), and it was overlooked to update it to consider the `jakarta` package, too.
