### ISSUE TITLE
Priorities should be configurable

### ISSUE THREAD

**Issue by AndreasIgelCC** [TNG/ArchUnit#129]
Hi at all,

in current version each testfailure reports a priority too. Unfortunately this priority could not be set on rules. Please offer a setter in builder-pattern to change this priority to a specific one.

Thanks!

Greetings,
Andreas

**Comment by codecholeric** [comment]
This might not be the most obvious API, but it is already possible:

```
ArchRuleDefinition.priority(HIGH).classes().that()...
```

At least if I understand you correctly? I thought the priority in the middle of the rule would break the flow so I decided to put it to the beginning back then...
Does this help you?

**Comment by AndreasIgelCC** [comment]
Thx for the tip. Helped to solve the issue.
