### ISSUE TITLE
DONT_INCLUDE_TESTS should be enabled by default 

### ISSUE THREAD

**Issue by qoomon** [TNG/ArchUnit#152]
Would be great to have DONT_INCLUDE_TESTS to be enabled by default, cause in general you want to check the project architecture not the test architecture.

**Comment by codecholeric** [comment]
I'm not sure about this:

* in my current project we also have a lot of rules to apply to test code
* it might also be valid to demand the same rules from your test code (e.g. if productive components should only depend on each other in a certain way, maybe test components should too?)
* and as a last point, `DONT_INCLUDE_TESTS` has always just been a "best guess" about the structure of most projects (if you look how it's implemented, you'll see why :wink:). There is no way to be sure that tests are excluded, this only works by convention.

That are the reasons it's not default up to now. Especially the last part, you just can't be sure that `DONT_INCLUDE_TESTS` really works for every project and then you have a default behavior that varies depending on the layout / build tool of your project.

**Comment by qoomon** [comment]
Okay I see your point 😁, thx for Your derailed answer
