### ISSUE TITLE
It should be possible to negate every should rule

### ISSUE THREAD

**Issue by qoomon** [TNG/ArchUnit#153]
Would be great if we can write something like this `noClasses().should().accessClassesThat().not().resideInAPackage("fo.bar..")`

e.g.
```
private <T> DescribedPredicate<T> not(DescribedPredicate<T> predicate) {
        return new DescribedPredicate<T>("not") {
            @Override
            public boolean apply(final T input) {
                return !predicate.apply(input);
            }
        };
    }
```

**Comment by codecholeric** [comment]
I had thought about that, but it seemed to make the internals and semantics more complicated, for example, what is the scope of `not()` if I write

```
accessClassesThat().not().haveName("foo").or().haveName("bar")
``` 

I.e. it's not self-evident, if not applies to the next partial sentence or all the rest to `should()` which might lead to confusion. Besides that it's not a grammatically correct sentence anymore :wink: 
So at the moment the API explicitly provides negations for everything making it clear that it's exactly this partial sentence that's inverted. What you can write for your case is

```
noClasses().should().accessClassesThat().resideOutsideOfPackage("fo.bar..")
```

which seems grammatically nicer. 
Btw. that "not-predicate" already exists as `DescribedPredicate.not(..)` :wink:

**Comment by codecholeric** [comment]
I'll close this for now, as long as I'm not convinced that this can be integrated in a self-explanatory non-confusing way.
