### ISSUE TITLE
`FieldsShould` should provide negated variants of `haveRawType`

### ISSUE THREAD

**Issue by asbachb** [TNG/ArchUnit#162]
Currently I want to accomplish something like this:
```
fields().that().areDeclaredInClassesThat().resideInAPackage("..package..")
.should().notHaveRawType(Float.class);
```
Which seems to be impossible with current api.

**Comment by hankem** [comment]
Those syntax elements are currently still missing indeed, but you can already build on [ArchConditions.not](https://static.javadoc.io/com.tngtech.archunit/archunit/0.10.0/com/tngtech/archunit/lang/conditions/ArchConditions.html#not(com.tngtech.archunit.lang.ArchCondition)) and [ArchConditions.haveRawType](https://static.javadoc.io/com.tngtech.archunit/archunit/0.10.0/com/tngtech/archunit/lang/conditions/ArchConditions.html#haveRawType(java.lang.Class)) with ArchUnit 0.10:
```
    fields().that().areDeclaredInClassesThat().resideInAPackage("..package..")
            .should(not(haveRawType(Float.class)));

```
Alternatively, the following should be equivalent as well:
```
    noFields().that().areDeclaredInClassesThat().resideInAPackage("..package..")
            .should().haveRawType(Float.class);
```
