### ISSUE TITLE
Class exclusion not working correctly?

### ISSUE THREAD

**Issue by schmist** [TNG/ArchUnit#165]
Consider the following minimal example (`archunit-junit4:0.10.0`):

```
package example.a

import example.b.B

class A {

    fun bar(b: B): B =
        b
}
```

```
package example.b

import example.a.A

class B {

    fun foo() {
        val a = A()
    }
}
```

```
class Ignored : ImportOption {
    override fun includes(location: Location): Boolean {
        return !location.contains("example/a")
    }
}

@RunWith(ArchUnitRunner::class)
@AnalyzeClasses(packages = ["example"], importOptions = [Ignored::class])
class ArchUnitTest {

    companion object {
        private const val aLayer = "aLayer"
        private const val bLayer = "bLayer"
    }

    @ArchTest
    @JvmField
    val layering: ArchRule =
        layeredArchitecture()
            .layer(aLayer).definedBy("example.a")
            .layer(bLayer).definedBy("example.b")
            .whereLayer(aLayer).mayNotBeAccessedByAnyLayer()
            .whereLayer(bLayer).mayNotBeAccessedByAnyLayer()
}
```

Because package `a` is excluded, there should be no violation in the layering test, which is true for version `0.9.3`. Since version `0.10.0`, the following violation is thrown:
```
java.lang.AssertionError: Architecture Violation [Priority: MEDIUM] - Rule 'Layered architecture consisting of
layer 'aLayer' ('example.a')
layer 'bLayer' ('example.b')
where layer 'aLayer' may not be accessed by any layer
where layer 'bLayer' may not be accessed by any layer' was violated (2 times):
Method <example.a.A.bar(example.b.B)> has parameter of type <example.b.B> in (A.kt:0)
Method <example.a.A.bar(example.b.B)> has return type <example.b.B> in (A.kt:0)
```
It seems that package `a` is still used as a starting point for evaluations, which was not the case in older versions. Am I missing something which changed in `0.10.0`?

**Comment by codecholeric** [comment]
I've tried to reproduce your example and it seems to me, that it might be connected to https://github.com/TNG/ArchUnit/issues/111 ?
People complained the old behavior was too confusing, so now the default behavior resolves missing classes from classpath which might lead to additional violations.
Anyway, if that should really be the problem you can either change the behavior back to the old version:
https://www.archunit.org/userguide/html/000_Index.html#_configuring_the_resolution_behavior 
Or you can adjust your rule to ignore those classes independently of which classes have been imported (maybe the more robust version):

```
layeredArchitecture()
    // ...
    .ignoreDependency(object : DescribedPredicate<JavaClass>("from example.a") {
        override fun apply(javaClass: JavaClass): Boolean {
            return javaClass.packageName.contains("example.a")
        }
    }, DescribedPredicate.alwaysTrue())
```

Does this help you?

**Comment by schmist** [comment]
Thanks for your answer. Yes it helps, but what we do not understand is why it is necessary to exclude unwanted classes twice. Is there a reason why the classes are imported although they are excluded?

**Comment by codecholeric** [comment]
At the moment the location filter only decides which classes you import, e.g. package `com.foo` but not `com.foo.B`. Now as the user guide tries to explain, if there is an imported class `com.foo.A` that depends on `com.foo.B`, but `com.foo.B` was not originally imported, the importer needs to decide what to do.
You could skip all dependencies and thus hide them from the imported classes. But that would mostly confuse people and lose information you'd probably want. Thus there is this hook in form of a `ClassResolver` that allows you to specify how the importer should try to locate those classes.
You could of course argue, that at this moment the importer should check if the `ImportOption` would forbid this import and then skip the dependency, but really at this moment you only have a fully qualified class name (like I need `com.foo.B`) and not an URI per se. To make matters worse, when you resolve from the classpath `com.foo.B` could be present in several locations, not all of them excluded by the location filter (e.g. add two JARs to the classpath with `com.foo.B` inside).
So it's just not that simple, the `ImportOption` defines which classes you originally want to look at. But how many classes are actually imported is dependent on the dependencies of those imported classes and the `ClassResolver` used to look for missing classes.
Does this make sense?

**Comment by schmist** [comment]
Yep, thanks for the clarifications.
