### ISSUE TITLE
Link from archunit.org to v0.10.2 release notes is broken

### ISSUE THREAD

**Issue by jwoe** [TNG/ArchUnit#166]
https://www.archunit.org/news/release/2019/03/31/release-v0.10.2.html links to https://github.com/TNG/ArchUnit/releases/tag/v0.10.2, yielding HTTP 404. As 0.10.2 was released with tag 0.10.2 instead of v0.10.2, the correct link would be https://github.com/TNG/ArchUnit/releases/tag/0.10.2.

I'm not sure if the link is false or the tag should have been v0.10.2 instead of 0.10.2.

**Comment by codecholeric** [comment]
Thanks for the info!! Yes, the convention is vx.y,z, I've retagged it the correct way. Can you check it works now for you? (I've tried the link and it seems okay, but better safe than sorry :wink:)

**Comment by jwoe** [comment]
Thanks for the quick response. It's working now 😊
