### ISSUE TITLE
How to check that dependencies injected in the constructor of classes only match certain conditions?

### ISSUE THREAD

**Issue by dvdciri** [TNG/ArchUnit#169]
I'm looking for a way to check that all classes (that match certain conditions) can have only certain dependencies injected in the constructor.

i.e. All classes that end with `test` can only have classes that end with `foo` or `bar` in the constructor, a class that end with `foobar` would make the test fail.

Is there a way to do that?

**Comment by codecholeric** [comment]
I hope I understood your problem, but what about

```
@ArchTest
static ArchRule injected_constructors_of_tests_have_correct_types =
        constructors()
                .that().areDeclaredInClassesThat().haveSimpleNameEndingWith("Test")
                .and().areAnnotatedWith(Inject.class)
                .should().haveRawParameterTypes(endingWithAnyOf("foo", "bar"));

private static DescribedPredicate<List<JavaClass>> endingWithAnyOf(String... suffixes) {
    return new DescribedPredicate<List<JavaClass>>("ending with any of %s", Arrays.toString(suffixes)) {
        @Override
        public boolean apply(List<JavaClass> parameterTypes) {
            Predicate<JavaClass> hasCorrectSuffix = clazz -> 
                    Arrays.stream(suffixes).anyMatch(suffix -> clazz.getSimpleName().endsWith(suffix));
            return parameterTypes.stream().allMatch(hasCorrectSuffix);
        }
    };
}
```

Does this get you started?

**Comment by dvdciri** [comment]
Oh yes, absolutely. I definitely see new methods that I wasn't aware of and this customer predicate is exactly what I needed. Thanks a lot.

I don't necessarily need to check the presence of the annotation but is definitely something that I can do. 
Am I right saying there is no method to do something like the custom predicate, where you don't have a orShould, or a andShould but you have a any of kind of assertion?

Cause that is what was driving me crazy :)

**Comment by codecholeric** [comment]
If that does not help you, maybe show me a concrete example so I can better understand :wink:

**Comment by dvdciri** [comment]
Yes that is exactly what I was looking for, thanks a lot we can close this :)
