### ISSUE TITLE
TestNg dependency prevent the Arch unit tests from being picked up by the surefire plugin

### ISSUE THREAD

**Issue by GaryCas** [TNG/ArchUnit#175]
Hi ArchUnit Team,

Similar to https://github.com/TNG/ArchUnit/issues/112

I've found that when there is a dependency on testng the maven-surefire plugin does not pick up on the ArchUnit tests at all. In summary. For a project with a failing archunit test this config does not pick up the test result.

    <dependencies>
        <dependency>
            <groupId>com.tngtech.archunit</groupId>
            <artifactId>archunit-junit4</artifactId>
            <version>0.9.3</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.8.8</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.0</version>
            </plugin>
        </plugins>
    </build>

But this config will 

    <dependencies>
        <dependency>
            <groupId>com.tngtech.archunit</groupId>
            <artifactId>archunit-junit4</artifactId>
            <version>0.9.3</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.0</version>
            </plugin>
        </plugins>
    </build>

This feels like a surefire problem and not and Archunit problem, but does anyone know if there is a resolution besides to remove testng as a dependency.? 

Thanks,
Gary

**Comment by hankem** [comment]
If you already have a suite of TestNG tests and want to add ArchUnit, you could just use plain ArchUnit with TestNG, cf. [archunit-example/example-plain](https://github.com/TNG/ArchUnit/tree/master/archunit-example/example-plain).

With the [Surefire documentation on "Running TestNG and JUnit Tests"](https://maven.apache.org/surefire/maven-surefire-plugin/examples/testng.html#Running_TestNG_and_JUnit_Tests), I also got a minimal example working using
```
    <dependencies>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.14.3</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.tngtech.archunit</groupId>
            <artifactId>archunit-junit4</artifactId>
            <version>0.10.2</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.2</version>
                <configuration>
                    <properties>
                        <property>
                            <name>junit</name>
                            <value>false</value>
                        </property>
                    </properties>
                    <threadCount>1</threadCount>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.apache.maven.surefire</groupId>
                        <artifactId>surefire-junit47</artifactId>
                        <version>2.22.2</version>
                    </dependency>
                    <dependency>
                        <groupId>org.apache.maven.surefire</groupId>
                        <artifactId>surefire-testng</artifactId>
                        <version>2.22.2</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
```
I you want, I can also share the full example.

**Comment by GaryCas** [comment]
Hi Hankem,

Thanks for the speedy reply, that did work! I was playing around with the configuration and I noticed that it only work when the thread count is explicitly set to one. Would you have any idea as to why that is? And also why the junit property is set to false and not true? 

Cheers, 
Gary

**Comment by hankem** [comment]
Hi Gary, to be honest: I have next to no experience with `surefire-testng`, and I am also puzzled by its configuration... 😉 So no; I unfortunately have no idea either, I'm sorry!

**Comment by codecholeric** [comment]
I think this is basically a Surefire issue. Unfortunately I don't know how to solve the quirk with the thread count and Surefire either, but I guess you would have to ask the Surefire maintainers about it.
Basically if you don't want any dependency on JUnit and use pure TestNG you have to use the ArchUnit Core library as @hankem has pointed out. 
Other than that I'm afraid that how to run TestNG and JUnit parallel with Surefire is out of scope here.
