### ISSUE TITLE
Verify input set is not empty in ArchRule

### ISSUE THREAD

**Issue by Bananeweizen** [TNG/ArchUnit#178]
It's easy to write a wrong rule like
`classes().thatAreDeclaredInAPackage("..nonexisting..).should()...`

Therefore it would be nice to have some additional syntax around the should() to verify that the input for the following conditions is not empty. This can not be implemented by means of a custom predicate, since the predicates are never called for an empty input set.

Basically I'm thinking of something like this:
`classes().thatAreDeclaredInAPackage("..nonexisting..).mustExistAndShould()...`

That rule would already fail before any predicate is executed, if the number of classes is empty when starting to evaluate the conditions.

If you feel this has no value for the general archunit users, I'm happy with response where I need to dig around to implement this myself locally. Thanks

**Comment by codecholeric** [comment]
I see your point, but I think what you want might already be possible:

```
import static com.tngtech.archunit.base.DescribedPredicate.greaterThan;

classes().thatAreDeclaredInAPackage("..nonexisting..)
    .should()...
    .andShould().containNumberOfElements(greaterThan(0))
```

Do you think this could work for your case?

**Comment by Bananeweizen** [comment]
Great. That works very well for that use case. I'll just create another issue, since it is only available for ClassConjunction, not for fields, constructors, etc.

**Comment by crehn** [comment]
Is there a way to check this for `noClasses()`?

**Comment by codecholeric** [comment]
Hmm, sadly since this is part of the condition, and the condition is negated, you probably have to do some crazy thing like

```
noClasses()...should()...
    .orShould().containNumberOfElements(equalTo(0));
```
