### ISSUE TITLE
Error with (generated) anonymous inner class (e.g. SWITCH statement)

### ISSUE THREAD

**Issue by jhartlep** [TNG/ArchUnit#196]
Hi,
we have some problems with anonymous inner classes (generated code by mapstruct)

Here is a part of my mapper (autogeneraded by mapstruct):

```
public class FooBarMapperImpl {
    public Foo fooToBar(Foo foo) { // Foo and Bar are ENUM
        if (foo == null) {
            return null;
        }
        switch (foo) {
            case Foo.BAR: return Bar.FOO;
            case Foo.Foo: return Bar.BAR;
            default: throw new IllegalArgumentException("Unexpected enum constant");
        }
    }
}
```
The corresponding ArchUnit rule looks like this:

```
classes().that()
    .resideInAPackage("..mapper")
    .should().haveSimpleNameEndingWith("Mapper")
    .orShould().haveSimpleNameEndingWith("MapperImpl")
```

NamingConventionTest Architecture Violation [Priority: MEDIUM] - Rule 'classes that reside in a package '..mapper' should have simple name ending with 'Mapper' or should have simple name ending with 'MapperImpl'' was violated (1 times):
simple name of some.package.mapper.FooBarMapper$1 doesn't end with 'Mapper' in (FooBarMapper.java:0) and simple name of some.package.mapper.FooBarMapper$1 doesn't end with 'MapperImpl' in (TardisRemoteServiceMapper.java:0)

What can I do  to get this test work?
If I write the mapper manually with the SWITCH-CASE code, the same error occurs.
If I write the mapper manually with IF construct, the test is fine.

So this is a general problem with ArchUnit and switch.

Kind regards,
Jens

**Comment by codecholeric** [comment]
This is a general problem with any anonymous classes I would say. But what you can do, is just to express what you want: "Outer classes should adhere to naming convention" (Honestly I don't have a good name for the opposite of inner classes :wink:)
Am I right? So you could express this by

```
classes().that()
        .resideInAPackage("..mapper")
        .and(areOuterClasses())
        .should().haveSimpleNameEndingWith("Mapper")
        .orShould().haveSimpleNameEndingWith("MapperImpl");

// ...

private DescribedPredicate<JavaClass> areOuterClasses() {
    return new DescribedPredicate<JavaClass>("are outer classes") {
        @Override
        public boolean apply(JavaClass javaClass) {
            return !javaClass.getEnclosingClass().isPresent();
        }
    };
}
```

Alternatively you could use the Java compiler naming convention (but I don't think I'd recommend that :wink:) 

```
classes().that()
        .resideInAPackage("..mapper")
        .should().haveNameMatching(".*Mapper(Impl)?(\\$.*)?")
```

Note though, that the package `"..mapper"` will only match **toplevel** classes, as soon as you have `.mapper.sub.SomeMapper`, the class will be ignored. It you want to consider subpackages, too, you need `"..mapper.."`.

Does this solve your problem?

**Comment by jhartlep** [comment]
Hi Peter,
thanks for your answer.
The first example works perfect! Thanks!
