### ISSUE TITLE
build fails with Java 9

### ISSUE THREAD

**Issue by JoergM** [TNG/ArchUnit#199]
Using JDK 9 the build fails with the following message:
```
> Task :archunit:spotbugsMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':archunit:spotbugsMain'.
> SpotBugs rule violations were found. See the report at: file:///Users/joerg/Source/java/ArchUnit/archunit/build/reports/spotbugs/main.html
```

The Spotbug report mentions the following warnings:

```

Code | Warning
-- | --
OBL | com.tngtech.archunit.library.freeze.ViolationStoreFactory$TextFileBasedViolationStore$FileSyncedProperties.loadRulesFrom(File) may fail to clean up java.io.InputStream
  |  
OBL | com.tngtech.archunit.library.freeze.ViolationStoreFactory$TextFileBasedViolationStore$FileSyncedProperties.syncFileSystem() may fail to clean up java.io.OutputStream
```

The same code can be build using JDK 11 so it seems to be a JDK 9 related issue. I used AdoptOpenJDK 9.

**Comment by hankem** [comment]
I can confirm the failure (on the current `master` 783e72b5409ae219e3540ec15d993778a882c0f8) with Java 9 and 10.

The details for this _Experimental Warning_ `OBL_UNSATISFIED_OBLIGATION` mention that
> the false-positive suppression heuristics for this bug pattern have not been extensively tuned, so reports about false positives are helpful to us.

To me, both `InputStream` and `OutputStream` seem to be handled correctly in a try-with-resources statement, so I believe that those are false positives indeed (cf. spotbugs/spotbugs#432).

We could probably add two more entries to `spotbugs-excludes.xml` (as I did with fc9d520a233bd281961e764d61fa51bf293031af for other false positives, also related to try-with-resources statements) to support the build with Java 9 and 10.

**Comment by codecholeric** [comment]
Yes, I agree that this is a false positive. I found this issue described online as well. Should be fixed now thanks to @hankem :smiley:
