### ISSUE TITLE
Add module description for java 9+ compatibility

### ISSUE THREAD

**Issue by tobiasdiez** [TNG/ArchUnit#206]
It would be nice if you could add a module-info file describing the modules that ArchUnit exports. This would make it easier to use ArchUnit in a modularized application and would prevent split package problems.

For example, the gradle configuration 
````
    testRuntime 'com.tngtech.archunit:archunit-junit5-engine:0.10.2'
    testCompile 'com.tngtech.archunit:archunit-junit5-api:0.10.2'
````
leads to the following errors on runtime (with java 11)
````
Modules com.tngtech.archunit.junit5.engineapi and com.tngtech.archunit.junit5.api export package com.tngtech.archunit.junit to module org.assertj.core
````

**Comment by codecholeric** [comment]
Version 1.0 would be a good time to break the API here, I think (because this will likely move some classes around that might cause compile errors. But maybe it is good enough the just transparently move the engine classes to a different package and adjust the service loader descriptor file.
