### ISSUE TITLE
Extend Classes Syntax for anonymous / inner / outer classes

### ISSUE THREAD

**Issue by codecholeric** [TNG/ArchUnit#207]
It would be neat to have `classes().that().`

* `areAnonymous()`
* `areInnerClasses()` (includes anonymous classes, do we need `areNamedInnerClasses()`?)
* `areOuterClasses()` (i.e. no enclosing class / toplevel, I'm open for better naming :wink:)

Same holds for `classes().should().be...`

**Comment by codecholeric** [comment]
Overlaps in parts with #172

**Comment by rweisleder** [comment]
The JLS defines four different kinds of classes, see [chapter 8](https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html).

With this reference I suggest to add the methods `classes().that().`
* `areTopLevelClasses()`
* `areNestedClasses()`
* `areLocalClasses()`
* `areAnonymousClasses()`

And of course the same for `classes().should().be...`

To be consistent with existing methods we should also add the negated methods like `areNotTopLevelClasses()` and `notBeTopLevelClasses()`.

**Comment by codecholeric** [comment]
We should also make the determination of the nested class type more resilient. Currently `isAnonymous()` is implemented by checking the simple name for being empty. The class file import should be able though, to derive a type of the nested class (static nested, inner, local, anonymous) and pass that on to the `JavaClass` instead of applying some heuristics later (since for a local class this would be something shady like `javaClass.getName().matches(".*\\$\\d+\\w+")` or similar :fearful:)

**Comment by rweisleder** [comment]
I started working on this issue.
