### ISSUE TITLE
Is there a way log/trace files that are not covered by any layer of a LayeredArchitecture?

### ISSUE THREAD

**Issue by gadton** [TNG/ArchUnit#222]
Defining layers and allowed access is easy but how to check if all loaded classes are covered by at least one layer?

**Comment by codecholeric** [comment]
I don't think there is a way at the moment. Originally I thought, that the white list way to define layers would draw in all relevant classes in in time anyway. E.g. define layer `persistence` may only be accessed by `service`, and also only `persistence` may use the `EntityManager`. Now any class that wants to access the database must reside in the `persistence` layer, or use a class from the `persistence` layer, but then it must reside in the `service` layer, and so on.
I guess `LayeredArchitecture` could be extended to allow some `strict` mode, where all classes must be covered by layers, similar like how a PlantUML rule fails, if not all checked classes are covered by the diagram. But `LayeredArchitecture` as opposed to the PlantUML rules, allows no way to filter the classes before.
Anyway, you can still somewhat mitigate your pain by simply writing a second rule

```
classes().should().resideInAnyPackage(allLayerPackageIdentifiers);
```

**Comment by codecholeric** [comment]
I think this would by a nice addition, so if anybody is looking for a simple starter to contributions, this here is open for grabs :wink: 
I guess we could introduce something like `enforceAllClassesResideInLayers()`, but we also would need an additional `ignoreClasses(Class<?>...)` and `ignoreClasses(DescribedPredicate<JavaClass>)` to enable specific ignores (let's be realistic about the world out there :wink:).

**Comment by clojj** [comment]
Very nice to see this addition! exactly the thin I tried to test by using something like this

```
ArchRuleDefinition.classes().that()
            .resideOutsideOfPackage("$orderBoundedContext..").should()
            .containNumberOfElements(DescribedPredicate.equalTo(0))
```

...really hope this gets merged soon !?
