### ISSUE TITLE
is there any plan to support local variables?

### ISSUE THREAD

**Issue by destan** [TNG/ArchUnit#227]
Hi,

After reading #208, I got the impression that _ArchUnit could read the local variable table_ if we wanted to.

Being aware of the local variables and writing rules about them do not seem to be related about architecture at first but doing so would give us:

* ability to check coding style and best practices
* ability to find code smells and vulnaribilities like followings:
  - https://rules.sonarsource.com/java/RSPEC-2131
  - https://rules.sonarsource.com/java/RSPEC-5334
  - https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-2254

I believe those things are an important part of software architecture and by checking & imposing them in a project significantly improves quality.

Moreover, with local variable awareness ArchUnit could be a complete replacement of any static code analyzer (Sonar, CAST etc.)

Hence my question: First of all am I right about my assumptions? Then, do you plan to support it? What are your thoughts on this issue?

Thanks

**Comment by codecholeric** [comment]
AFAIK you're right about your assumptions, local variables could be extracted and added to `JavaCodeUnit`, i.e. methods and constructors. I think the information easily accessible would be name, type, index and scope (even though scope just means label start and label end without any reference to anything else ArchUnit extracts so far). Also it would be possible to extract in which line a local variable is set and read. Should not even be too difficult.
I could imagine this being useful, and I like ArchUnit to be as powerful as possible to assert patterns on code bases.
However, what I'm worried about would be to significantly increase the resources needed for any user. I.e. ArchUnit already needs a big amount of heap for big code bases. I would not like to increase this significantly for a feature that only a fraction might use.
So I would be open to add this, but only in a way similar to MD5 handling for `JavaClass.source`, i.e. by default this import is deactivated, and must be explicitly activated via `archunit.properties`/`ArchConfiguration`.
Then `JavaCodeUnit` could offer a `LocalVariables v = javaCodeUnit.getLocalVariables()`, but without the activated feature it would simply throw an exception telling how to activate the configuration, or similar.

**Comment by destan** [comment]
Making local variable support optional sounds fair and logical. So you are open to adding this feature but don't have any concrete plan for implementing it or have this as an item in the road map right?

I'd like to be part of the development process of this feature however I am really new to this library and not familiar with the internals. However, if you decide to implement this maybe I can help with the requirements, API or use case examples.

**Comment by codecholeric** [comment]
Yes, I don't have any concrete plans, because I don't have the resources at the moment. If you want to give it a shot though, I'd definitely give you all the support I can!
The point where you would have to start at, is

```
com.tngtech.archunit.core.importer.JavaClassProcessor.MethodProcessor
```

You could start by overriding

```
@Override
public void visitLocalVariable(String name, String descriptor, String signature, Label start, Label end, int index) {
    // log interesting parameters
    super.visitLocalVariable(name, descriptor, signature, start, end, index);
}

@Override
public void visitVarInsn(int opcode, int var) {
    // log interesting parameters
    super.visitVarInsn(opcode, var);
}
```

and simply logging the parameters. Then write a simple unit test, and just try

```
@Test
public void demo() {
    new ClassFileImporter().importClass(Foo.class);
}

----

private static class Foo {
    void call() {
        int localExample = 0;
    }
}
```

You should see how the methods behave and what info could be extracted. There is already a variable `lineNumber` that continuously gets updated within `MethodProcessor`.

**Comment by dbraun1991** [comment]
For more persons to find their way to this thread ...
https://stackoverflow.com/questions/74461422/archunit-test-sensitive-variable-naming
... ;-)
