### ISSUE TITLE
orShould().onlyBeAccessed().byClassesThat().haveSimpleNameEndingWith() doesn't work as expected!?

### ISSUE THREAD

**Issue by blackfoxoh** [TNG/ArchUnit#229]
Let's say we have services and facades. Definition of what is a facade or service comes from the classnames. Services could be used by the facades or by other services. Other classes (which aren't facades or services) should be restricted from accessing the services.

I have the following ArchRule:
`ArchRule rule = classes().that().haveSimpleNameEndingWith("Service").should().onlyBeAccessed().byClassesThat().haveSimpleNameContaining("Facade").orShould().onlyBeAccessed().byClassesThat().haveSimpleNameEndingWith("Service");`
As it didn't work as expected I created a simple example consisting of two services and one facade where the only method in SomeService is called from both other classes.
![grafik](https://user-images.githubusercontent.com/1757547/64410911-574a5980-d08c-11e9-96c4-12bae7e832c5.png)

This results in 
`Rule 'classes that have simple name ending with 'Service' should only be accessed by classes that have simple name containing 'Facade' or should only be accessed by classes that have simple name ending with 'Service'' was violated (1 times):
Method <archunitExample.OtherService.someMethod()> calls method <archunitExample.SomeService.someMethod()> in (OtherService.java:15) and Method <archunitExample.SomeFacadeBean.someMethod()> calls method <archunitExample.SomeService.someMethod()> in (SomeFacadeBean.java:15)`

If I just use one or the other `byClassesThat().haveSimpleName...()` condition each one on its own does exactly what it should.
Is this a bug with `orShould()` or is it just the wrong way I used to express my rule?

**Comment by hankem** [comment]
The exclusiveness demanded by `onlyBeAccessed()` is the reason why your test fails: It is neither true
* that _services are only accessed by facades_ (as `OtherService` accesses `SomeService`), nor
* that _services are only accessed by services_ (as `SomeFacadeBean` accesses `SomeService`).

What you're probably looking for is an `ArchRule`
```
    classes().that().haveSimpleNameEndingWith("Service").should().onlyBeAccessed().byClassesThat(
            have(simpleNameContaining("Facade")).or(have(simpleNameEndingWith("Service")))
    );
```

**Comment by blackfoxoh** [comment]
Thank you very much.
Your example didn't complie for me as I didn't find a method `have()`.
I ended up with the following rule which seems to do what I need:
`classes().that().haveSimpleNameEndingWith("Service").should().onlyBeAccessed().byClassesThat(
            Predicates.simpleNameContaining("Facade").or(Predicates.simpleNameEndingWith("Service")));`

Can someone tell me please if I missed the `have()`-method somewhere and if yes if it makes any difference to my finally found solution?
Of course, this is not a bug then but my mistake so I'll close this case. Thanks again for the help.

**Comment by codecholeric** [comment]
Hey! It's `com.tngtech.archunit.lang.conditions.ArchPredicates#have` :wink: But that is only syntactic sugar, i.e. adjusts the description to make it nicer to read and nothing else...
