### ISSUE TITLE
jekyll/docker has github authentication error when starting jekyll server

### ISSUE THREAD

**Issue by gernotstarke** [TNG/ArchUnit#23]
actually, this is more of a pull-request than issue, but:
too bad, I cannot open a pull request on the orphaned gh-pages branch, therefore I attach the modified Gemfile here:

    source "https://rubygems.org"

    # commented the line below to get rid of github authentication warnings
    # gem "github-pages", group: :jekyll_plugins

    # added the following line, same reason as above
    gem "jekyll", group: :jekyll_plugins 

    group :jekyll_plugins do
      gem "jekyll-paginate"
      gem "jekyll-sitemap"
      gem "jekyll-gist"
      gem "jekyll-feed"
      gem "jemoji"
   end

**Comment by codecholeric** [comment]
Thanks, I made the adjustment in https://github.com/TNG/ArchUnit/commit/1efd35c4335dd2e3ca3338d6e7362206aac2b120

**Comment by codecholeric** [comment]
Actually, if I apply this, the Github Pages build doesn't work anymore, guess I would need to separate Gemfiles for local tests vs automatic build on Github?
Sorry, as I said, not much experience with Jekyll, Ruby and Github Pages :wink:

**Comment by gernotstarke** [comment]
You need separate config.yml for local build ("development") and github-build ("prod").
See arc42.org... in config-dev you use localhost as URL, in config-prod you use the real URL of the site (archunit.org). 

I'm fine with ONE Gemfile (with everything included the theme needs).

I'll look into it immediately... just need to do some housework first :-)

**Comment by gernotstarke** [comment]
what's the error message you get from github?
(I ask as arc42.org builds correctly on Github with exactly the same Gemfile as the one we have here...)

**Comment by codecholeric** [comment]
That's the problem, there was no error, the page just didn't come up (see my questions in the other issue, guess I should close this here, cause it's starting to confuse me :wink:)
