### ISSUE TITLE
Validate no calls to static method?

### ISSUE THREAD

**Issue by Jurrie** [TNG/ArchUnit#231]
Hello,

I want to assert that no code calls `DocumentBuilderFactory.newInstance()`. Easy enough at first sight: `noClasses().should().callMethod(DocumentBuilderFactory.class, "newInstance")`

However, you could extend DocumentBuilderFactory, and use that to call the method: `new MyDBF().newInstance()`. I also want to assert that no code does that. But I do not see how I should do it with ArchUnit. The ArchUnit rule above does not see this. Am I missing something in the API?

With kind regards,

Jurrie

**Comment by codecholeric** [comment]
I don't know, if I understand your point. First of all, if `DocumentBuilderFactory.newInstance()` is static, why would you extend `DocumentBuilderFactory` and call `newInstance()` on an instance of the subclass? There are various code quality tools, including any reasonable IDE that would warn you not to do that :wink: (`WARNING: static member ... accessed via instance reference`) 

Anyway, if you would actually do that for whatever reason, you should still be able to catch it, for example via

```
import static com.tngtech.archunit.core.domain.JavaAccess.Predicates.target;
// ...

ArchRule rule = noClasses().should().callMethodWhere(
        target(name("newInstance")
                .and(declarationIsWithin(DocumentBuilderFactory.class))));

private DescribedPredicate<AccessTarget> name(String methodName) {
    return HasName.Predicates.name(methodName).forSubType();
}

private DescribedPredicate<HasOwner<JavaClass>> declarationIsWithin(Class<?> type) {
    return Get.<JavaClass>owner().is(assignableTo(type));
}
```

Does this help you?

**Comment by Jurrie** [comment]
Thanks for your quick response!

I completely agree with your argument that it's "rather exotic", and that quality tools will warn for this. However, I'm writing a library that is going to be used by many other developers, most of which I do not know. The library will guard against unsafe usage of XML parser classes. But it might possibly be a pita for someone out there, so I can imagine that people will try to find creative ways around it. I'm doing my best to detect all usage of those unsafe classes.

That said, detecting invocation of a static method of a parent class using a child class is not at the top of my list, for the same reasons as you gave already.

I can not seem to get the code fragment above to work. It looks like it should work just fine; I will have to investigate further to see why it doesn't work. When I figure it out, I'll post here.

**Comment by codecholeric** [comment]
In case you're still having problems, this should be a complete working example:

```
package com.tngtech.archunit.exampletest;

import javax.xml.parsers.DocumentBuilderFactory;

import com.tngtech.archunit.base.DescribedPredicate;
import com.tngtech.archunit.core.domain.AccessTarget;
import com.tngtech.archunit.core.domain.JavaClass;
import com.tngtech.archunit.core.domain.properties.HasName;
import com.tngtech.archunit.core.domain.properties.HasOwner;
import com.tngtech.archunit.core.importer.ClassFileImporter;
import org.junit.Test;

import static com.tngtech.archunit.core.domain.JavaAccess.Predicates.target;
import static com.tngtech.archunit.core.domain.JavaClass.Predicates.assignableTo;
import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.noClasses;

public class DemoTest {
    @Test
    public void demo() {
        noClasses().should().callMethodWhere(
                target(name("newInstance")
                        .and(declarationIsWithin(DocumentBuilderFactory.class))))
                .check(new ClassFileImporter().importClasses(Evil.class, CallsEvil.class));
    }

    private DescribedPredicate<AccessTarget> name(String methodName) {
        return HasName.Predicates.name(methodName).forSubType();
    }

    private DescribedPredicate<HasOwner<JavaClass>> declarationIsWithin(Class<?> type) {
        return HasOwner.Functions.Get.<JavaClass>owner().is(assignableTo(type));
    }

    private abstract static class Evil extends DocumentBuilderFactory {
    }

    private static class CallsEvil {
        Evil evil;

        void call() {
            evil.newInstance();
        }
    }
}
```

Let me know, if you could solve your problem :smiley:

**Comment by codecholeric** [comment]
Any update on this?

**Comment by Jurrie** [comment]
Hi @codecholeric,

I'm sorry I didn't follow up on this. Thank you for your elaborate example. However, in the mean time, I've chosen a different route to fixing my problem. So, I'm closing this issue now. Thanks again for your help on this!

With kind regards,

Jurrie
