### ISSUE TITLE
ArchTestInitializationException for the Android project

### ISSUE THREAD

**Issue by igorwojda** [TNG/ArchUnit#241]
I am trying to add ArchUnit to my [android-showcase](https://github.com/igorwojda/android-showcase) project. I tried to implement a simple test, but when running Gradle command `./gradlew testDebugUnitTest` the tasks fails with:
```
com.igorwojda.showcase.feature.album.CleanArchitectureDependencyTest > check dependency rule FAILED
    com.tngtech.archunit.junit.ArchTestInitializationException
```

When running test from [Android Studio](https://developer.android.com/studio) UI...
![image](https://user-images.githubusercontent.com/530122/65917809-28e04580-e3d0-11e9-80c9-5c12cc05790d.png)

...test fails with more specific error:
```
> Task :feature_album:processDebugAndroidTestResources FAILED
AGPBI: {"kind":"error","text":"Android resource linking failed","sources":[{"file":"/Users/igorwojda/.gradle/caches/transforms-2/files-2.1/e98d6ef326a2039d580b55f40a7e963b/core-1.6.3/AndroidManifest.xml","position":{"startLine":8,"startColumn":4,"endColumn":277}}],"original":"/Users/igorwojda/.gradle/caches/transforms-2/files-2.1/e98d6ef326a2039d580b55f40a7e963b/core-1.6.3/AndroidManifest.xml:9:5-278: AAPT: error: resource style/Theme.PlayCore.Transparent (aka com.igorwojda.showcase.feature.album.test:style/Theme.PlayCore.Transparent) not found.\n    ","tool":"AAPT"}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':feature_album:processDebugAndroidTestResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/igorwojda/.gradle/caches/transforms-2/files-2.1/e98d6ef326a2039d580b55f40a7e963b/core-1.6.3/AndroidManifest.xml:9:5-278: AAPT: error: resource style/Theme.PlayCore.Transparent (aka com.igorwojda.showcase.feature.album.test:style/Theme.PlayCore.Transparent) not found.
```

Here is the branch where you can reproduce described behavior (`CleanArchitectureDependencyTest` class):
https://github.com/igorwojda/android-showcase/tree/arch-unit-verify-ca-dependencies

**Comment by codecholeric** [comment]
Sorry, somehow this issue slipped through :disappointed: Were you able to solve the issue meanwhile? I see the link is dead now? Unfortunately I have little experience with Android development (just some little app a while ago), so I don't know if I can help you much, but if you still have this problem I can at least give it a try!

**Comment by codecholeric** [comment]
I'll close this for now, feel free to reopen!!
