### ISSUE TITLE
Does a archunit exist for c/c++

### ISSUE THREAD

**Issue by stefaneicher** [TNG/ArchUnit#242]
Hi,
do you know if there exists tool similar to archunit for the C/C++ environment?

Regards Stefan

**Comment by codecholeric** [comment]
I'm really sorry, but I don't know any alternative for C/C++. There are some solutions for .NET/C#, but for C/C++ I don't know of anything. :frowning_face: 
Since nobody has had any better idea so far, I would close the issue for now.

**Comment by stefaneicher** [comment]
Ok thanks you anyway.
