### ISSUE TITLE
Fluency for notAccessed

### ISSUE THREAD

**Issue by abeyecon** [TNG/ArchUnit#254]
Using the following rule I can ensure that no impl class gets accessed directly (they will instead be injected via spring @Component injection against their interface).  However it doesn't read as well as it could, and the violation message doesn't read well either.  Suggest adding .notBeAccessed()

@ArchTest
    public static final ArchRule implOnlyUsedByInjection = classes()
            .that().resideInAPackage(IMPL)
            .should().onlyBeAccessed().byAnyPackage();

Violation Message:
Architecture Violation [Priority: MEDIUM] - Rule 'classes that reside in a package 'com.eyecon.xyz.impl..' should only be accessed by any package ['']' was violated (51 times):

**Comment by hankem** [comment]
Even though not fluent, you can easily use a custom condition:
```java
    @ArchTest
    public static final ArchRule implOnlyUsedByInjection = classes()
            .that().resideInAPackage(IMPL)
            .should(notBeAccessedAtAll());

    static ArchCondition<JavaClass> notBeAccessedAtAll() {
        return new ArchCondition<JavaClass>("not be accessed at all") {
            @Override
            public void check(JavaClass clazz, ConditionEvents events) {
                Set<JavaAccess<?>> accessesToSelf = clazz.getAccessesToSelf();
                StringBuilder message = new StringBuilder(clazz.getName()).append(" is accessed ").append(accessesToSelf.size()).append(" times");
                if (!accessesToSelf.isEmpty()) {
                    message.append(":");
                }
                for (JavaAccess<?> javaAccess : accessesToSelf) {
                    message.append("\n").append(javaAccess.getDescription());
                }
                events.add(new SimpleConditionEvent(clazz, accessesToSelf.isEmpty(), message.toString()));
            }
        };
    }
```

Violation Message:
```
java.lang.AssertionError: Architecture Violation [Priority: MEDIUM] -
 Rule 'classes that reside in a package 'com.eyecon.xyz.impl..' should not be accessed at all'
 was violated (51 times):
```

**Comment by abeyecon** [comment]
package archunit255;

import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.classes;

import org.junit.runner.RunWith;

import com.tngtech.archunit.junit.AnalyzeClasses;
import com.tngtech.archunit.junit.ArchTest;
import com.tngtech.archunit.junit.ArchUnitRunner;
import com.tngtech.archunit.lang.ArchRule;

@RunWith(ArchUnitRunner.class)
@AnalyzeClasses(packages = "archunit255")
public class ArchUnit255 {
    @ArchTest
    public static final ArchRule implClassesShouldOnlyBeInjectedOrAccessedBySubClasses = classes()
            .that().haveNameMatching(".*Impl$")
            .should().onlyBeAccessed().byClassesThat().extendThem();

    public interface I {
        void op();
    }

    public class BImpl implements I {
        public BImpl() {
        }

        @Override
        public void op() {
        }

        public void op2() {
        }
    }

    public class CImpl implements I {
        public CImpl() {
        }

        @Override
        public void op() {
        }
    }

    public class AImpl extends BImpl {
        public AImpl() {
            super();//OK
        }

        @Override
        public void op() {
            super.op();//OK
            super.op2();//NOT OK because called method name (op2) is not caller method name (op)
        }
    }

    public class A2Impl extends BImpl {
        private final I c = new CImpl();

        @Override
        public void op() {
            c.op();//NOT OK because A2Impl does not extend CImpl
        }
    }

    public class A3 extends BImpl {
        @Override
        public void op() {
            super.op();//NOT OK because A3 name is not A3Impl
        }
    }
}

**Comment by abeyecon** [comment]
Thanks @hankem that is a very tidy example

**Comment by codecholeric** [comment]
Just to mention, if it does what you want, and you only don't like the message, you could also just overwrite that:

```
@ArchTest
public static final ArchRule implOnlyUsedByInjection = classes()
    .that().resideInAPackage(IMPL)
    .should().onlyBeAccessed().byAnyPackage()

    .as("Spring bean implementations should not be directly accessed")
    .because("we want to use Spring DI and only to refer to them through their interface");
```

That's also a documentation for anyone reading your rule, what was the intention.

**Comment by abeyecon** [comment]
```    static ArchCondition<JavaClass> notBeAccessed() {
        return new ArchCondition<JavaClass>("not be accessed at all") {
            @Override
            public void check(final JavaClass clazz, final ConditionEvents events) {
                final Set<JavaAccess<?>> accessesToSelf = clazz.getAccessesToSelf();
                final Set<JavaAccess<?>> externalAccessesToSelf = accessesToSelf.stream()
                        .filter(access -> access.getOriginOwner() != clazz)
                        .collect(Collectors.toSet());
                final StringBuilder message = new StringBuilder(clazz.getName()).append(" is accessed ")
                        .append(externalAccessesToSelf.size()).append(" times");
                if (!externalAccessesToSelf.isEmpty()) {
                    message.append(":");
                }
                for (final JavaAccess<?> javaAccess : externalAccessesToSelf) {
                    message.append("\n").append(javaAccess.getDescription());
                }
                events.add(new SimpleConditionEvent(clazz, externalAccessesToSelf.isEmpty(), message.toString()));
            }
        };
    }
```

Modified code to allow class to access itself internally

**Comment by abeyecon** [comment]
Thanks for the help.  Love ArchUnit.  Looking forward to 1.0 so that our large business friends can use it without fighting with the corporate policies.

**Comment by codecholeric** [comment]
Yes, we should really release 1.0
There is no real reason for keeping it 0.x, it's stable and has been out there for a long time, it's mainly just me thinking "why should this be 1.0, it's not different from the last release" :roll_eyes:
I really feel #171 should be in there, but since I'm gonna merge that into the next release, maybe then it's time :wink:

**Comment by codecholeric** [comment]
PS: If your question is solved, do you want to close the issue?
