### ISSUE TITLE
Why are CodeUnitsShould have..Type() and notHave..Type() methods not contravariant?

### ISSUE THREAD

**Issue by daniel-shuy** [TNG/ArchUnit#262]
For example, [FieldsShould#haveRawType(DescribedPredicate)](https://static.javadoc.io/com.tngtech.archunit/archunit/0.12.0/com/tngtech/archunit/lang/syntax/elements/FieldsShould.html#haveRawType(com.tngtech.archunit.base.DescribedPredicate)) is contravariant (takes in a `DescribedPredicate<? super JavaClass>`), whereas [CodeUnitsShould#haveRawReturnType(DescribedPredicate)](https://static.javadoc.io/com.tngtech.archunit/archunit/0.12.0/com/tngtech/archunit/lang/syntax/elements/CodeUnitsShould.html#haveRawReturnType(com.tngtech.archunit.base.DescribedPredicate)) is invariant (takes in a `DescribedPredicate<JavaClass>`).

This makes it possible to do:
```java
ArchRuleDefinition.fields()
    .should().haveRawType(CanBeAnnotated.Predicates.annotatedWith(Annotation.class))
```
(because [CanBeAnnotated.Predicates#annotatedWith(Class)](https://static.javadoc.io/com.tngtech.archunit/archunit/0.12.0/com/tngtech/archunit/core/domain/properties/CanBeAnnotated.Predicates.html#annotatedWith(java.lang.Class)) returns a `DescribedPredicate<CanBeAnnotated>`, and `JavaClass` implements `CanBeAnnotated`)

but not possible to do:
```java
ArchRuleDefinition.methods()
    .should().haveRawReturnType(CanBeAnnotated.Predicates.annotatedWith(Annotation.class))
```

Is this intended?

**Comment by codecholeric** [comment]
No, sorry, this is not intended :frowning_face: I think the second one should have a contravariant predicate type as well. Must have slipped through. Maybe I should write some sort of `ArchRule` for that :wink: 
There is some "convenience" method `annotatedWith(Foo.class).<JavaClass>forSubtype()` to mitigate such pain points (even though in this place it should just work out of the box).

**Comment by codecholeric** [comment]
I've adjusted the API, there were a couple of places where this slipped through.
Also added an `ArchTest` to make sure future methods will always be written correctly with respect to `DescribedPredicate` :wink: 
Thanks for reporting this issue and helping to make ArchUnit better :smiley:
