### ISSUE TITLE
ArchRuleDefinition methods notHaveRawReturnType with generic not work

### ISSUE THREAD

**Issue by JanYunkai** [TNG/ArchUnit#264]
archunit.version: 0.12.0
jdk: 8

```
DescribedPredicate<JavaClass> entityPredicate = JavaClass.Predicates.resideInAPackage("..entity..")

ArchRule classRule = ArchRuleDefinition
                .methods()
                .that()
                .areDeclaredInClassesThat()
                .resideInAPackage("..service")
                .should()
                .notHaveRawReturnType(entityPredicate)
                .because("dao entity can`t be return type")
```

**rule.check() // pass, expect fail**

-----
```
package com.entity
public class EntityA {
}
```
-----
```
package com.service
public interface SomeService {
    List<EntityA> a();
}
```

how can i fix it?

thx

**Comment by hankem** [comment]
FYI @JanYunkai: I've added some Markdown formatting (triple backticks) to your code blocks (cf. [Creating and highlighting code blocks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks)), as otherwise `List<EntityA>` was displayed as `List` only, which just hides the cruicial part. 😃

**Comment by hankem** [comment]
The test stating that 
> _services should not have a raw return type  that reside in a package_ "`..entity..`"

passes because the raw return type of `SomeService.a()` is `java.util.List`.

As far as I can see, ArchUnit does unfortunately not yet have access to generic type parameters of a method's return type (and neither for parameter types, by the way).

**Comment by JanYunkai** [comment]
ok, thx very much。
other way i can use package checks
