### ISSUE TITLE
Detecting member variables being passed to private methods

### ISSUE THREAD

**Issue by abeyecon** [TNG/ArchUnit#265]
Can ArchUnit detect member variables being passed to private methods?
```
    private String member;

    public void method1() {
        aPrivateMethod(member);//bad
    }

    private void aPrivateMethod(final String s) {
    }
```

**Comment by abeyecon** [comment]
This detects the issue, but I'm not sure if it is robust
```
public class ScratchTest {
    @ArchTest
    public static final ArchRule shouldNotPassMemberVariablesToPrivateMethods = methods()
            .that().arePrivate()
            .should(notHaveMemberVariablesPassed());

    private static ArchCondition<? super JavaMethod> notHaveMemberVariablesPassed() {
        return new ArchCondition<JavaMethod>("should not have member variables passed in") {
            @Override
            public void check(final JavaMethod method, final ConditionEvents events) {
                final Set<JavaMethodCall> calls = method.getAccessesToSelf();
                final Set<JavaField> fields = method.getOwner().getFields();
                for (final JavaMethodCall call : calls) {
                    final SourceCodeLocation methodCallLocation = call.getSourceCodeLocation();
                    for (final JavaField field : fields) {
                        for (final JavaFieldAccess fieldAccess : field.getAccessesToSelf()) {
                            final SourceCodeLocation fieldCallLocation = fieldAccess.getSourceCodeLocation();
                            if (fieldCallLocation.equals(methodCallLocation)) {
                                final String message = String.format(
                                        "Call from %s to %s uses member variable %s on line %s", call.getName(),
                                        method.getName(), field.getName(), fieldCallLocation.toString());
                                events.add(new SimpleConditionEvent(method, false, message));
                            }
                        }
                    }
                }

            }
        };
    }

    private String member;

    public void method1() {
        aPrivateMethod(member);//bad
    }

    private void aPrivateMethod(final String s) {
        System.out.println("x");
    }
}
```

**Comment by abeyecon** [comment]
Example false positive:
```
   public void method2() {
      member == null || aPrivateMethod("abc");//good
   }
```

**Comment by abeyecon** [comment]
Example false positive:
```
   private Client client;
   public void method3() {
      aPrivateMethod(client.get());//good.
   }
```

**Comment by codecholeric** [comment]
I don't know exactly what you want to achieve (i.e. why), but I think it exceeds the possibilities ArchUnit offers at the moment. I could think of the same idea as you, look at the accesses and compare line numbers, but yes, that is not robust.
To achieve what you want, I think more bytecode introspection into statements would be necessary, e.g. conditionals and other control structures, to then deduct which constructs have actually been used (like your false positives). I don't see any way to do this with the current state though.
May I ask about the background, why you would want to achieve this? Maybe it would be possible to look at the problem from a different angle...

**Comment by hankem** [comment]
I understood the first example as that one should favor
```
    aPrivateMethod();
```
(where `aPrivateMethod()` accesses the field `member` itself) over 
```
    aPrivateMethod(member);
```
If that was the intention, I'd agree that it is a good practice in some cases, but I wouldn't think that it works as a global "architecture rule" (maybe rather code style), because you could e.g. have `aPrivateMethod(final String s)` being called with diferrent fields / parameters / constants in different cases.

**Comment by codecholeric** [comment]
I sometimes also consciously pass a field into a method, even though it could be accessed from within the private method, if I feel like it better documents the calling site (but I might then also make the method static to immediately signal it's just a little utility function without access to the class state / side effects).
Anyway, yes, I agree, that would rather be code style, and I don't think ArchUnit is the best tool for that (to not get into the "if you only have a hammer" situation :wink:)

**Comment by abeyecon** [comment]
The rationale was to clean up method signatures and get methods to be on the object that most made sense.  It was part of a trio of rules to achieve this.  The other two are working with ArchUnit.
1) methodsWithNoInstanceAccessShouldBeStatic
2) staticMethodsWithAParameterShouldBeInstanceMethodsOnThatClass
3) shouldNotPassMemberVariablesToPrivateMethods
```
class A {
   public void doSomething(B parameter) {
   }
}
```
doSomething() might be better as a method on class B if it (1) accesses no instance fields, (3)has no instance fields passed directly in as parameters.

**Comment by abeyecon** [comment]
I can get rid of the second type of false positives with :
method.getRawParameterTypes().contains(field.getRawType())

**Comment by codecholeric** [comment]
Ah, I see :smiley: As a helping guideline for OO, I never thought of that!
You're right, with that additional assertion it's down to just fields with a matching type being accessed in the same line by accident. That should really not happen too often.
Unfortunately I also don't know of any tool that would do a better job there. One could probably write a PMD rule/plugin or similar, but if that is really worth the pain point of split tools and extra learning effort, I don't know.

**Comment by abeyecon** [comment]
I think with the last tweak it is good enough.  I might need to freeze some cases on the larger projects, but the initial small one is all green after cleaning up two real situations.

**Comment by abeyecon** [comment]
Actually no false positives were generated across all projects, just a bunch of real places to change.
