### ISSUE TITLE
Empty layers of LayeredArchitecture in multi-module project

### ISSUE THREAD

**Issue by xsveda** [TNG/ArchUnit#267]
The `0.12.0` version forbids empty layers of LayeredArchitecture to avoid accidental misbehavior. 

Unfortunately, this breaks our use-case where we use ArchUnit in multi-module project. Our project consists of approx. 60 gradle modules where all share the same LayeredArchitecture configuration. But not all modules have all the layers as i.e. some features just don't need to persist any data to database. 

Currently we are not able to update to `0.12.0` version as this would force us to create and maintain separate LayeredArchitecture configuration for each of them.

Is there any other option we can leverage on in our use case?
If not, would it be possible to make this behavior configurable - enabled by default but allowed to be disabled?

**Comment by pszymczyk** [comment]
The same problem is with OnionArchitecture, I have small module without domain services and in `0.12.0` test failed

```
Layer 'domain service' is empty
```

In my opinion domain services are not required and it's quite regular situation that you don't have any on them.

**Comment by To6i** [comment]
We have the same issue here. But instead of having a global switch I would prefer defining it on a layer basis:

```
layeredArchitecture()
    .layer("AAA").definedBy("..aaa..")
    .layer("BBB").definedBy("..bbb..")
    .whereLayer("AAA").mayNotBeAccessedByAnyLayer()
    .whereLayer("BBB").mayOnlyBeAccessedByLayers("AAA").and().mayBeEmpty
```
or:
```
layeredArchitecture()
    .layer("AAA").definedBy("..aaa..")
    .optionalLayer("BBB").definedBy("..bbb..")
    .whereLayer("AAA").mayNotBeAccessedByAnyLayer()
    .whereLayer("BBB").mayOnlyBeAccessedByLayers("AAA")
```
What do you think about it?

**Comment by codecholeric** [comment]
I like the possibility to be able to specify it per layer as well. Would be more powerful to distinguish between layers that should always be filled and some that could be empty. What do you think @hankem?
Should we just go for `optionalLayer` then? But what about `onionArchitecture`? Or have both options and `onionArchitecture` only allows the global switch? Or should `onionArchitecture` have all onion parts as an `optional...` version as well, piping to `optionalLayer`?

**Comment by hankem** [comment]
I think that there are valid use cases for both options.

I understood the original issue to be due to ArchUnit rules being applied to all modules in a multi-module project – maybe because this is the way how I'm using ArchUnit myself...? 😉 I have the same set of rules consistently applied to each module – including e.g. a `:commons:util` module, which is entirely independent of the domain layers.

So I'd try to add the possibility to define individual `optionalLayer`s.
In the spirit of #177, we should probably prevent unintended misconfigurations by not allowing to have individual `optionalLayer`s together with the global switch?

**Comment by To6i** [comment]
@hankem 
Sounds good! Having both options would be nice.

**Comment by hankem** [comment]
In the current status of #273, I suggest:

* _`layeredArchitecture()`_**`.optionalLayer(`**`name`**`)`**
to define an individual optional layer (≔  one that may be empty, i.e., does not fail if it does not contain any classes)

* _`layeredArchitecture()`_**`.withOptionalLayers(`**`true`**`)`** &
_`onionArchitecture()`_**`.withOptionalLayers(`**`true`**`)`**
to make all layers optional by default

* no individual optional layers for the onion architecture so far
(as I have no experience whether this is needed or not)

* no failure for the combination
_`layeredArchitecture()`_**`.withOptionalLayers(`**`boolean`**`)`**﻿**`.optionalLayer(`**`name`**`)`**
as I've tried to explain in the JavaDoc that `withOptionalLayers` just configures the default behavior for `layer`s, but does not prevent using `optionalLayer`s.
