### ISSUE TITLE
Allow to define Onion Architecture without Domain Services

### ISSUE THREAD

**Issue by pszymczyk** [TNG/ArchUnit#271]
Hi

I've just bump ArchUnit to 0.12.0 and one of my tests failed. It's because I have a module which has no Domain Services - only Application Services and Domain Model components. From my understanding  this situation is totally ok and still consistent with all Onion Architecture principles, that's why in my opinion Domain Services layer should be an optional layer. What it's your point of view? If you agree I can proceed with Pull Request solving this issue.

**Comment by codecholeric** [comment]
Resolved by #273
