### ISSUE TITLE
areAnnotatedWith() does not recognise inherited annotations

### ISSUE THREAD

**Issue by roxspring** [TNG/ArchUnit#277]
Given the following classes:
```java
@Transactional
class AbstractBaseService {..}

@Transactional
class OtherService {..}

class ConcreteService extends AbstractBaseService {
  OtherService other = ...
}
```

When I invoke the rule:

```java
  @ArchTest
  public static final ArchRule transitiveTransactionalAnnotation = classes()
    .that().areAnnotatedWith(Transactional.class)
    .should().onlyBeAccessed().byClassesThat().areAnnotatedWith(Transactional.class);
```

Then I expect no violations, since Spring considers that `ConcreteService` inherits `@Transactional` from `AbstractBaseService`, but ArchUnit does not consider inherited annotations and raises a violation.

I guess annotations are not automatically inherited in java but Spring does consider them inheritable so it would be good if there were at least an option to consider inherited annotations. I suspect this all translates equally to meta annotations too.

**Comment by roxspring** [comment]
FWIW I'm currently working around this by encoding knowledge of the super classes into the rule, which is sufficient for now but not ideal:

```java
  @ArchTest
  public static final ArchRule transitiveTransactionalAnnotation = classes()
    .that().areAnnotatedWith(Transactional.class)
    .should().onlyBeAccessed().byClassesThat().areAnnotatedWith(Transactional.class)
    .orShould().onlyBeAccessed().byClassesThat().areAssignableTo(AbstractBaseService.class);
```

**Comment by codecholeric** [comment]
Yes, `annotatedWith(..)` does refer to the class itself, not considering any parent classes, but did you try

```
@ArchTest
public static final ArchRule transitiveTransactionalAnnotation = classes()
    .that().areAnnotatedWith(Transactional.class)
    .should().onlyBeAccessed().byClassesThat().areAssignableTo(annotatedWith(Transactional.class));
```

That should take parent classes into account (might want to adjust the descriptions a little, e.g. `annotatedWith(Transactional.class).as("classes annotated with @Transactional"`)

**Comment by codecholeric** [comment]
I'll close this for now, feel free to reopen if you have further questions / problems!
