### ISSUE TITLE
False AssertionError on Static Methods Test

### ISSUE THREAD

**Issue by strmecki** [TNG/ArchUnit#279]
Hi,

let me just start by saying very, very, very awesome library. Thanks for sharing it!

I found one small issue. I wrote a test that my services should not contain static methods. However this results in AssertionError because I have static fields in them. Field checks should be excluded when asserting on methods.

```java
@ArchTest
private final ArchRule serviceImplementationsHaveNoStaticMethods = methods().that()
    .areDeclaredInClassesThat().resideInAPackage(SERVICES_IMPL_PACKAGE)
    .should().notBeStatic();
```

Best regards,
Daniel

**Comment by hankem** [comment]
Can you provide an example?

Using ArchUnit 0.12.0, the following works for me, i.e. I don't get a false `AssertionError` for any of the static fields in the test itself, whereas a static method would be caught as expected:

```java
@org.junit.runner.RunWith(com.tngtech.archunit.junit.ArchUnitRunner.class)
@com.tngtech.archunit.junit.AnalyzeClasses(packagesOf = Issue279.class)
public class Issue279 {
    public static final int PUBLIC = 1;
    private static final int PRIVATE = 2;
    protected static final int PROTECTED = 4;
    static final String SERVICES_IMPL_PACKAGE = Issue279.class.getPackage().getName();

    @com.tngtech.archunit.junit.ArchTest
    static final com.tngtech.archunit.lang.ArchRule serviceImplementationsHaveNoStaticMethods =
            com.tngtech.archunit.lang.syntax.ArchRuleDefinition.methods()
                    .that().areDeclaredInClassesThat().resideInAPackage(SERVICES_IMPL_PACKAGE)
                    .should().notBeStatic();

//    static void thisWouldGiveAnAssertionError() { }

    void thisIsFine() { }
}
```

**Comment by strmecki** [comment]
Hi, sure. I am using JUnit 5, version 0.12.0. And you are correct, its not about static fields, the error has something todo with lamda/stream. I guess something there is static when compiled?

This is my test:
`
@ArchTest
private static final ArchRule serviceImplementationsHaveNoStaticMethods = 
     methods().that().areDeclaredInClassesThat().resideInAPackage(SERVICES_IMPL_PACKAGE)
    .should().notBeStatic();
`

And this is one service:
`
@Component(immediate = true, service = ImageFinderService.class)
public class ImageFinderServiceImpl implements ImageFinderService
{
    private static final String DEFAULT_IMAGE = "https://via.placeholder.com/319x212";
    private static final String IMAGE_COMPONENT_RESOURCE_TYPE = "aemsp/components/content/image/v1/image";
    private static final String IMAGE_COMPONENT_FILE_REFERENCE = "fileReference";

    @Override
    public String getFirstImagePath(String rendition, Page articlePage)
    {
        List<Resource> mainContentResources = ResourceUtils.getMainContentResources(articlePage);
        return mainContentResources.stream()
                 .filter(resource -> resource.getResourceType().equals(IMAGE_COMPONENT_RESOURCE_TYPE))
                 .findFirst()
                 .map(Resource::getValueMap)
                 .map(properties -> properties.get(IMAGE_COMPONENT_FILE_REFERENCE, String.class))
                 .map(fileReference -> StringUtils.join(fileReference, rendition))
                 .orElse(DEFAULT_IMAGE);
    }
}
`

I get the following error:
`
java.lang.AssertionError: Architecture Violation [Priority: MEDIUM] - Rule 'methods that are declared in classes that reside in a package '..services.impl..' should not be static' was violated (9 times):
Method <io.ecx.aem.aemsp.core.services.impl.ImageFinderServiceImpl.lambda$getFirstImagePath$0(org.apache.sling.api.resource.Resource)> has modifier STATIC in (ImageFinderServiceImpl.java:0)
Method <io.ecx.aem.aemsp.core.services.impl.ImageFinderServiceImpl.lambda$getFirstImagePath$1(org.apache.sling.api.resource.ValueMap)> has modifier STATIC in (ImageFinderServiceImpl.java:0)
Method <io.ecx.aem.aemsp.core.services.impl.ImageFinderServiceImpl.lambda$getFirstImagePath$2(java.lang.String, java.lang.String)> has modifier STATIC in (ImageFinderServiceImpl.java:0)
`

**Comment by hankem** [comment]
Ah, I see! 😃
Yes, a lambda expression may indeed be compiled to a synthetic static method. For example, 
```java
    void thisShouldBeFine() {
        java.util.stream.Stream.of("Hello", "World!")
                .filter(string -> string.endsWith("!"))
                .forEach(System.out::println);
    }
```
also gives me the following in the bytecode:
```
  private static boolean lambda$thisShouldBeFine$0(java.lang.String);
    descriptor: (Ljava/lang/String;)Z
    flags: (0x100a) ACC_PRIVATE, ACC_STATIC, ACC_SYNTHETIC
    Code:
      stack=2, locals=1, args_size=1
         0: aload_0
         1: ldc           #12                 // String !
         3: invokevirtual #13                 // Method java/lang/String.endsWith:(Ljava/lang/String;)Z
         6: ireturn
```
----
You can, however, exclude those methods from your rules.

I believe that the Java compiler adheres to some naming convention for those methods generated from lambda expressions, but you can probably also exclude synthetic methods in general:
```java
    methods()
            .that().areDeclaredInClassesThat().resideInAPackage(SERVICES_IMPL_PACKAGE)
            .should().notBeStatic()
            .orShould().haveModifier(com.tngtech.archunit.core.domain.JavaModifier.SYNTHETIC)
            // alternatively exclude methods by name:
            .orShould().haveNameMatching(".*lambda\\$.*\\$\\d+");
```

**Comment by strmecki** [comment]
Thanks for the workaround, it works nicely! I am not sure if you can apply it per default?

**Comment by hankem** [comment]
As Java bytecode has different concepts of static and synthetic methods, it seems fair to me that ArchUnit doesn't mix those either (i.e. that `MethodsShould.notBeStatic()` stays independent of a synthetic modifier).
I'd even say that ArchUnit is so powerful because it allows to model many very different use cases as simple combinations of atomic building blocks.

**Comment by codecholeric** [comment]
@strmecki You cannot configure it as default for the fluent API, but you can just build your own extensions to your needs. Consider for example:

```
import static com.tngtech.archunit.core.domain.JavaModifier.*;
import static com.tngtech.archunit.lang.conditions.ArchConditions.haveModifier;
import static com.tngtech.archunit.lang.conditions.ArchConditions.notBeStatic;

...

methods()
    .that().areDeclaredInClassesThat().resideInAPackage(SERVICES_IMPL_PACKAGE)
    .should(notBeStaticIfUserCreated());

static ArchCondition<? super JavaMethod> notBeStaticIfUserCreated() {
    return notBeStatic().or(haveModifier(SYNTHETIC))
        .as("not be static if user-created");
}
```

**Comment by codecholeric** [comment]
I'll close this for now, feel free to reopen if you have more questions or suggestions!
