### ISSUE TITLE
Should-Syntax should contain 'interface' handling

### ISSUE THREAD

**Issue by codecholeric** [TNG/ArchUnit#28]
While there is a predicate syntax
```
classes().that().implement(foo)
```
the only way to filter for interfaces is using
```
classes().that(are(JavaClass.Predicates.INTERFACES))
```
The fluent API should allow filtering for interfaces
```
classes().that().areInterfaces()
classes().that().areNoInterfaces()
```
as well as asserting interfaces
```
classes().should().beInterfaces()
classes().should().notBeInterfaces()
```

**Comment by hajotka** [comment]
I'll have a look on Friday ;)

**Comment by codecholeric** [comment]
Thanks :smiley: I think, this is the hardest and most complex of the "help wanted" issues though, so it's up to you if you want to start with a "quicker win" :wink:
