### ISSUE TITLE
Upgrade to an ASM version supporting JDK 14

### ISSUE THREAD

**Issue by odrotbohm** [TNG/ArchUnit#280]
We would like to explore record types introduced in JDK 14ea and have ArchUnit tests in our codebase and the class import currently (understandably, as it's very early days) fails:

```
java.lang.IllegalArgumentException: Unsupported class file major version 58
	at com.tngtech.archunit.thirdparty.org.objectweb.asm.ClassReader.<init>(ClassReader.java:195)
	at com.tngtech.archunit.thirdparty.org.objectweb.asm.ClassReader.<init>(ClassReader.java:176)
	at com.tngtech.archunit.thirdparty.org.objectweb.asm.ClassReader.<init>(ClassReader.java:162)
	at com.tngtech.archunit.thirdparty.org.objectweb.asm.ClassReader.<init>(ClassReader.java:283)
	at com.tngtech.archunit.core.importer.ClassFileProcessor$UriImporterOfProcessor.tryImport(ClassFileProcessor.java:186)
	…
```

I guess this might have to be reported to ASM downstream.

**Comment by hankem** [comment]
[ArchUnit 0.12.0](https://github.com/TNG/ArchUnit/releases/tag/v0.12.0) indeed already uses ASM 7.2, which is currently the most recent [ASM version](https://asm.ow2.io/versions.html).
(_Disclaimer:_ I personally have so far no experience with JDK 14 or record at all.)

**Comment by odrotbohm** [comment]
Maybe I have been imprecise. What I wanted to express is that ArchUnit will need to upgrade to an ASM version supporting JDK14 to be able to be used on JDK14 itself. The ticket here is supposed to act as a placeholder for this task. I am very well aware that ASM is not there yet.

Records are not something ArchUnit has to care about. I just wanted to give a reason why we're already looking into a JDK version that is not even available in GA.

**Comment by hankem** [comment]
Well, I wasn't aware that ASM is not there yet, as ASM 7.2 beta already claimed:
> * add support for Java 14

But I understand that those things are not final yet, so I guess ASM will provide an update at some point.

**Comment by odrotbohm** [comment]
Your pointer to ArchUnit 0.12 was pretty darn helpful. We had been on 0.11 still and the ASM 7.2 inlined in 0.12 is indeed already capable of dealing with Java 14 based code. Nothing left do do here, awesome!

**Comment by hankem** [comment]
For record types, see also #295.
