### ISSUE TITLE
ArchUnit tests flaky

### ISSUE THREAD

**Issue by athkalia** [TNG/ArchUnit#285]
Hello,

We have a couple of ArchUnit tests, and it seems like every now and then a test passes even though it shouldn't on CI. What that means is that the problematic PR gets merged into develop, and then at a later time CI starts failing on develop.

For example, this has been happening with the 0.11.0 version since we added ArchUnit into the project. 

Here's an example test that is flaky:
(note that we are using the Spek (https://github.com/spekframework/spek) test framework)

```
package com.babylon.archunit

import androidx.appcompat.app.AppCompatActivity
import com.babylon.app.api.common.OwnedBySquads
import com.babylon.v3.base.BaseFlowActivity
import com.babylon.v3.base.BaseSquadsActivity
import com.babylon.v3.home.main.MainActivity
import com.tngtech.archunit.core.importer.ClassFileImporter
import com.tngtech.archunit.core.importer.ImportOption
import com.tngtech.archunit.core.importer.Location
import com.tngtech.archunit.lang.syntax.ArchRuleDefinition.classes
import org.jetbrains.spek.api.Spek
import org.jetbrains.spek.api.dsl.given
import org.jetbrains.spek.api.dsl.it

class ArchUnitActivityRules : Spek({

    given("all classes for app module") {
        val classes = ClassFileImporter().withImportOption(ClassesFromModuleImportOption("app")).importPackages("com.babylon")

        it("All activities need to be annotated with an 'OwnedBySquad' annotation.") {

            val classesToCheck = classes().that().areAssignableTo(AppCompatActivity::class.java)

            classesToCheck
                .and().doNotHaveSimpleName(BaseSquadsActivity::class.java.simpleName)
                .and().doNotHaveSimpleName(MainActivity::class.java.simpleName) // Ownership is defined on a fragment level for this one.
                .and().doNotHaveSimpleName(BaseFlowActivity::class.java.simpleName)
                .should().beAnnotatedWith(OwnedBySquads::class.java)
                .because("a_reason")
                .check(classes)
        }
    }
})

class ClassesFromModuleImportOption(private val modulePath: String) : ImportOption {
    override fun includes(location: Location): Boolean {
        return location.contains("babylon-android/$modulePath/")
    }
}
```

Have you heard of anything similar or have any thoughts on this? As I am writing this I tried to upgrade ArchUnit to the latest version to see if it has any effect (but I couldn't see anything similar in the release notes, so can't really say)

**Comment by codecholeric** [comment]
I have never experienced ArchUnit tests to be flaky, as long as the inputs are reliable. 
What you do with the line

```
ClassFileImporter().withImportOption(ClassesFromModuleImportOption("app")).importPackages("com.babylon")
```
is pretty much to tell ArchUnit "look into my classpath and read all URLs you can find that start with `/com/babylon` and also satisfy the `ImportOption`. So what could make your test flaky would for example be

* you have not compiled all the class to the expected location at the time ArchUnit is running (i.e. `babylon-android/...`)
* you have for some reason a different classpath in different environments (i.e. some folders are sometimes missing from the classpath of the `ClassLoader` executing your test)

The only thing I can imagine how I would go forward to debug this would be to log the respective classes. You can do that by configuring a SLF4J compatible logger and logging `com.tngtech.archunit.core.importer.JavaClassProcessor` on `DEBUG` (i.e. add some SLF4J binding of your choice, like Log4J2, to your `testRuntime` scope and configure the logger accordingly)
And of course you could log the locations passed to your `ClassesFromModuleImportOption` to see if those are always the same.
Also you could configure a Gradle Build Scan to compare the order of the tasks, if the same tasks are executed before the ArchUnit test is executed (i.e. have all sources really been compiled and put in the location you expect)

**Comment by codecholeric** [comment]
Could you fix your problem?

**Comment by athkalia** [comment]
Hello, thanks for the answer. I've still not managed to test what you are suggesting. I'll update once I do!

**Comment by codecholeric** [comment]
Okay, then I'll close this issue for now, feel free to simply reopen if you should run into further problems or have further questions!

**Comment by athkalia** [comment]
Hi @codecholeric , we managed to look at this and it ended up being a problem on our side, not setting the path properly. Thanks again for the help. ArchUnit is rock solid :)
