### ISSUE TITLE
[Question] Classes should be referenced in external package

### ISSUE THREAD

**Issue by jpcampos** [TNG/ArchUnit#286]
Hi, I have a question on how to create a rule fo the following.

I have classes that are autogenerated in a given package, i.e. "com.autogenerate" package. So, for example
```
package com.autogenerate;
public class MyGeneratedClass
```

All the classes generated in this "com.autogenerate" package should be referenced in a class in package "com.usegenerated"

For example, a class called MyUseGeneratedClass references the autogenerated class in a method which is defined in the interface UseGeneratedInterface
i.e., 
```
package com.usegenerated

public class MyUseGeneratedClass implements UseGeneratedInterface {
       MyGeneratedClass getGenClazz() {
           return MyGeneratedClass.class;
 }
```

My question is how to create a rule to check that all classes that are autogenerated are referenced in the "usegenerated" package. This is to ensure that all autogenerated classes have a corresponding class that uses them since we need to force the writing of functionality in the "usegenerated"package. Thanks!

**Comment by codecholeric** [comment]
I'm not sure I completely understand your intentions :thinking: I could understand your description as two different use cases.

### Use case 1

You don't want unused generated classes, i.e. you want to make sure every auto-generated class has a user, otherwise it's obsolete

### Use case 2

You don't want code outside of `com.usegenerated` to directly reference the code in `com.autogenerate` to isolate the auto-generated code. (or you only want one specific class per auto-generated class with a certain convention to reference the respective auto-generated class and no other classes?)

Am I understanding you correctly? Which use case is it? Both can be solved, so if you explain which of both you want to achieve I can provide you with some sketch :wink:

**Comment by codecholeric** [comment]
(even though for **use case 2** I guess the method directly returning the auto-generated class would not make much sense then, correct?)

**Comment by jpcampos** [comment]
Hi, 
My apologies as I should have made it clear as you state in Use Case #1, I want to ensure every auto generated class has a use inside the `com.usegenerated`package (it can also have other uses outside this class) but if it does not have a use inside the `com.usegenerated` it needs to be flagged as obsolete. And you are correct about case #2 not making sense to return the auto generated class. In sum, Use Case #1. Hope this clarifies it, thank you!.

**Comment by codecholeric** [comment]
Sorry for the delay, you could maybe use something like

```
// Rule
classes().that().resideInAPackage("..autogenerate..")
        .should(eachHaveAUserIn("..usegenerated.."))

// Utility
private ArchCondition<JavaClass> eachHaveAUserIn(String packageIdentifier) {
    PackageMatcher packageMatcher = PackageMatcher.of(packageIdentifier);
    return new ArchCondition<JavaClass>("each have a user in " + packageIdentifier) {
        @Override
        public void check(JavaClass javaClass, ConditionEvents events) {
            boolean hasUser = javaClass.getDirectDependenciesToSelf().stream()
                    .anyMatch(d -> packageMatcher.matches(d.getOriginClass().getPackageName()));
            String message = String.format("Class %s %s user within %s",
                    javaClass.getName(), hasUser ? "has a" : "has no", packageIdentifier);
            events.add(new SimpleConditionEvent(javaClass, hasUser, message));
        }
    };
}
```

Would that help you?

**Comment by jpcampos** [comment]
Yep, that works perfectly! Thank you for your reply and help. I will close this issue now, love the framework and look forward to the 1.0 release to satisfy some of the "official" release requirements around here.

**Comment by codecholeric** [comment]
Yes, I was close to releasing an 1.0 RC around now, but I'll release one last minor upgrade and see if I can add some last core things (e.g. type parameters). In particular because I'm on holiday from tomorrow on, so maybe I have time :wink:
