### ISSUE TITLE
println in Kotlin is not caught by noClasses().should(ACCESS_STANDARD_STREAMS)

### ISSUE THREAD

**Issue by lsoares** [TNG/ArchUnit#294]
![image](https://user-images.githubusercontent.com/674045/72190657-09f24600-33f8-11ea-90b5-a7f39b5097e9.png)

the tests are all green with this. the weird part is that even being explicit with System.out, the problem remains.

**Comment by codecholeric** [comment]
Did you figure it out?

**Comment by lsoares** [comment]
hey. yes.. I forgot to call `.check(classes)` -_- my fault
