### ISSUE TITLE
onlyHaveDependentClassesThat() vs onlyBeAccessed()

### ISSUE THREAD

**Issue by rudolfgrauberger** [TNG/ArchUnit#302]
My folder/package structure
```
com.example.post
|- api
    PostApi.java
|- service
    PostService.java
```

```java
public class PostApi {
}
```

```java
@Service
public class PostService {
    @Autowired
    private PostApi postApi;
}
```

My first try

```java
@AnalyzeClasses(packages = "com.example.post", importOptions = { ImportOption.DoNotIncludeTests.class, ImportOption.DoNotIncludeJars.class, ImportOption.DoNotIncludeArchives.class })
public class MyTest {
    @ArchTest
    public static final ArchRule apiClassesShouldOnlyBeAccessedByApis = classes()
        .that().resideInAPackage("..api..")
        .should().onlyBeAccessed().byAnyPackage("..api..");
}
```

Test passed! (undesired and not expected)

I changed the test to 

```java
@AnalyzeClasses(packages = "com.example.post", importOptions = { ImportOption.DoNotIncludeTests.class, ImportOption.DoNotIncludeJars.class, ImportOption.DoNotIncludeArchives.class })
public class MyTest {
    @ArchTest
    public static final ArchRule apiClassesShouldOnlyBeAccessedByApis = classes()
            .that().resideInAPackage("..api..")
            .should().onlyBeAccessed().byClassesThat().resideInAnyPackage("..api..");
}
```

Test passed! (undesired and not expected)

If I change the Test to

```java
@AnalyzeClasses(packages = "com.example.post", importOptions = { ImportOption.DoNotIncludeTests.class, ImportOption.DoNotIncludeJars.class, ImportOption.DoNotIncludeArchives.class })
public class MyTest {
    @ArchTest
    public static final ArchRule apiClassesShouldOnlyBeAccessedByApis = classes()
        .that().resideInAPackage("..api..")
        .should().onlyHaveDependentClassesThat().resideInAnyPackage("..api..");
}
```

Test failed  with message (as expected and desired):

```java
java.lang.AssertionError: Architecture Violation [Priority: MEDIUM] - Rule 'classes that reside in a package '..api..' should only have dependent classes that reside in any package ['..api..']' was violated (1 times):
Field <com.example.post.service.PostService.tagApi> has type <com.example.post.api.PostApi> in (PostService.java:0)
```

Why the different results? I don't think I understand the difference between onlyHaveDependentClassesThat() and onlyBeAccessed()

**Comment by hankem** [comment]
What happens if you add a method to `PostApi` and actually call it from `PostService`?

**Comment by rudolfgrauberger** [comment]
@hankem Thank you very much.

**Comment by codecholeric** [comment]
@rudolfgrauberger yes, this is exactly right. For ArchUnit `class Foo implements Bar` or some field or method parameter type `Bar` is no access, only reading or writing a field or calling a method or constructor.
You could also compare [`com.tngtech.archunit.exampletest.junit4.LayerDependencyRulesTest`](https://github.com/TNG/ArchUnit-Examples/blob/master/example-junit5/src/test/java/com/tngtech/archunit/exampletest/junit5/LayerDependencyRulesTest.java) within the example project.
Do you think it would have helped you, if the Javadoc of `access*` and `depend*` of the API would have elaborated more about the differences and linked to each other?

**Comment by rudolfgrauberger** [comment]
@codecholeric Thank you very much. Yes, I think it would help a lot to explain the difference between  accessed** and depend** in the api and the userguide. The description on the linked LayerDependendyRulesTest would actually be enough.
