### ISSUE TITLE
generic type is not found as dependencie

### ISSUE THREAD

**Issue by scout779** [TNG/ArchUnit#307]
For classes below:

```
package org.foo.a;

import java.util.List;
import org.foo.b.B;

public class A {

	private List<B> b;
}



package org.foo.b;

public class B {

}
```
The rule is finished with success

```
ArchRule rule = ArchRuleDefinition.noClasses().that().resideInAPackage("org.foo.a..")
			.should().dependOnClassesThat().resideInAPackage("org.foo.b..");
```

Is it possible to detect generic type dependencies using ArchUnit?

**Comment by scout779** [comment]
ok, it's not possible becouse of use ASM library - more in issue #131

**Comment by codecholeric** [comment]
I'm optimistic that we can add this feature (in fact I've already started to look into it), but it won't be trivial, i.e. gonna need a little time :wink:
