### ISSUE TITLE
archunit-example should have its own "readme"

### ISSUE THREAD

**Issue by gernotstarke** [TNG/ArchUnit#31]
if you approve #30 (self contained build for archunit-example), then a brief readme
might be helpful for newbie users (like myself).

**Comment by codecholeric** [comment]
I've added a readme to `archunit-example`, can you check if it's understandable?
https://github.com/TNG/ArchUnit/tree/master/archunit-example
I've also removed the `@Ignores` and replaced them by a specific `@Category` to skip them during the regular Gradle build.

**Comment by gernotstarke** [comment]
thanx Peter, that exactly what I was missing before...
