### ISSUE TITLE
Checking if a package exists

### ISSUE THREAD

**Issue by thombergs** [TNG/ArchUnit#310]
ArchUnit tests that check dependencies between packages lose validity when I move or rename a package. The test is still green, but the packages in the test don't exist anymore.

**Example:**
```java
@AnalyzeClasses(packages = "io.reflectoring")
class ArchitectureTests {

  @ArchTest
  static final ArchRule apiDoesNotDependOnInternal = noClasses()
      .that().resideInAPackage("io.reflectoring.api..")
      .should().accessClassesThat().resideInAPackage("io.reflectoring.internal..");

}
```

If I rename the package `io.reflectoring.internal` to something `io.reflectoring.new`, the test will still be green, because there are no classes in that package anymore and thus there will be no dependency violations according to the `ArchRule`. 

But I can now add (unwanted) dependencies from `io.reflectoring.api` to `io.reflectoring.new` without any test breaking.

**Question:**
Is there a way to make such tests refactoring safe? Or to check if the packages I'm referencing im my ArchUnit tests actually exist? 

**Workaround:**
My current workaround is to check for each package that a class exists in that package, i.e. something like this:

```java
@Test
  void internalPackageExists() {
    String className = "io.reflectoring.internal.SomeClass";
    try {
      Class.forName(className);
    } catch (ClassNotFoundException e) {
      fail("Class %s does not exist, did you move it? Don't forget to update the package names in this test!", className);
    }
  }
```

**Comment by hankem** [comment]
You'd probably be on a safer side if you could specify your architecture rule by _whitelisting_ allowed packages (instead of _blacklisting_ forbidden packages), e.g.
```java
@ArchTest
static final ArchRule apiOnlyDependsOnCommon = classes()
    .that().resideInAPackage("io.reflectoring.api..")
    .should().onlyDependOnClassesThat().resideInAnyPackage("java..", "io.reflectoring.common..");
```
(Note that I've switched to test for more general dependencies instead of access only, cf. #302. If you want to stick to access-dependencies, you can replace `onlyDependOnClassesThat` with `onlyAccessClassesThat`.)

If whitelisting all allowed packages is not feasible and you can rely on `SomeClass` to fully represent your forbidden package (i.e. you don't worry that other classes might be refactored to another package  independently), you could use the following refactoring-safe package description:
```java
static final ArchRule apiDoesNotDependOnInternal = noClasses()
    .that().resideInAPackage("io.reflectoring.api..")
    .should().dependOnClassesThat().resideInAPackage(
            io.reflectoring.internal.SomeClass.class.getPackage().getName() + ".."
    );
```

I'm not aware of a way to check if the packages referenced im ArchUnit tests _actually exist_ (which, by the way, might be a difficult concept, as it significantly depends on which classes are imported by ArchUnit.)

**Comment by thombergs** [comment]
Thanks for your reply. Using `getPackage()` certainly goes a long way towards refactoring-safety. 

But as you say, this is still vulnerable to moving single classes.

The best way would be to refer to the package as a String and have a check that verifies that the package actually exists (i.e. there is at least one class in it). I guess one could build something like that with the Reflections library...I'll try that. 

Thanks again, this got me thinking :).

**Comment by hankem** [comment]
Did you consider whitelisting allowed dependencies (which was my main suggestion 😉)?

My last statement on testing whether packages _'exist'_ was probably a bit misleading. You **can** easily combine ArchUnit with your favorite unit testing framework (e.g. [AssertJ](https://assertj.github.io/doc/) as in my example below) to test that a given package is contained among the _imported_ classes:

```java
import static org.assertj.core.api.Assertions.assertThat;

@ArchTest
void validateInternalPackageNameAssumption(JavaClasses classes) {
        String packageName = "io.reflectoring.internal";
        assertThat(classes.containPackage(packageName))
                .as("Imported classes contain package %s", packageName)
                .isTrue();
}
```

**Comment by thombergs** [comment]
Yes, whitelisting is not an option in this because I don't want to restrict the package dependencies too much.

But `containPackage()` is exactly what I was looking for, thank you!
