### ISSUE TITLE
getting the methods from an interface in another module

### ISSUE THREAD

**Issue by vincent-fuchs** [TNG/ArchUnit#312]
Hi,

I am trying to implement a rule, but I am facing some strange behavior. The rule is someting like this : 
in hexagonal architecture, we have interfaces declared in `domain` package, that are implemented in `infrastructure` package. I want to make sure that implementation classes don't have public methods other than the ones declared in the domain interface. 

**note** : I know it may make this issue a bit off topic, but this happens only when I execute the rule through  ArchUnit gradle plugin. Locally within the plugin, my unit tests work. When I tested locally the rule on a real project (PR is still not merged : https://github.com/societe-generale/arch-unit-build-plugin-core/pull/12/files), I find it's not working.

I am able to identify if a class implements an interface, and if that interface belongs to domain package. 

But when I get the interface's methods, then I get an empty list : 

```java
@Override
public void check(JavaClass javaClass, ConditionEvents events) {

	Set<JavaClass> implementedInterfaces = javaClass.getInterfaces();

	if(implementedInterfaces.isEmpty()){
		System.out.println("\t --> no interface");
		return ;
	}

	for(JavaClass thisInterface : implementedInterfaces){

		System.out.println("\t --> has interface "+thisInterface.getFullName()+"..");
					
		Set<JavaMethod> methodsFromDomainInterface = thisInterface.getAllMethods();
		
		System.out.println("\t\t --> nb of methods in the interface :  "+methodsFromDomainInterface.size());

		...
	}
}	
	
```		

Sample output : 

> analysing my.company.service.infrastructure.service.PartnerConfigurationServiceImpl...
>          --> has interface my.company.service.domain.PartnerConfigurationService..
>                  --> nb of methods in the interface :  0

This doesn't happen if one of the class implements : 
- an interface declared in the same module
- a "standard" interface like `Runnable`

I've added this code to try to understand the issue, and I have some inconsistency I am not able to explain : 

```java
 System.out.println("interfaces found for partnerConfigurationServiceImpl : ");
            partnerConfigurationServiceImpl.getInterfaces().stream().forEach(i -> {
                System.out.println("\t - "+i.getName()+" - "+i.isInterface());
            });
```

> interfaces found for partnerConfigurationServiceImpl :
>        - my.company.domain.PartnerConfigurationService - false

--> How comes `PartnerConfigurationService` is returned when we call `getInterfaces` on `partnerConfigurationServiceImpl` , but when I call `isInterface` on it, I get false ? 

I am not sure whether the issue is in the way the module is compiled or how the class is loaded by the plugin : I've tried to replicate in my target project with a regular test, and load the classes the same way the plugin does it, but it works as expected in that case.   

Thanks for your help !

**Comment by codecholeric** [comment]
This sounds very strongly like the interface is sometimes imported and sometimes not imported. In particular `isInterface()` will return `false` if the class has not been imported by ArchUnit.
This can for example happen, if the classpath is different. If you say

```
new ClassFileImporter().importClasses(com.myapp.MyImplClass.class)
```

and the classpath contains `com.anywhere.MyInterface`, then `MyInterface` will also be loaded, while it will be replaced by a stub if it cannot be loaded from the classpath. (as long as the setting `resolveMissingClassesFromClasspath` is `true`)

Have you tried to enable debug logging to check which classes are being imported when the test works and when it doesn't work? I would bet there is a difference in the set of imported classes...

BTW, do you know https://www.archunit.org/userguide/html/000_Index.html#_onion_architecture? :wink:

**Comment by vincent-fuchs** [comment]
Thanks for the quick feedback. I had tried to add an `archunit.properties` file with `resolveMissingDependenciesFromClassPath=false/true` but didn't see any change in behavior. 

Now I have enabled the debug output as you suggested, and this is what I see : 

> [QUIET] [system.out] Loading classes from C:\Users\Vincent\IdeaProjects\my-project\infrastructure\build\classes\java\main...
> [DEBUG] [com.tngtech.archunit.core.importer.JavaClassProcessor] Analyzing class 'my/project/service/infrastructure/service/PartnerConfigurationServiceImpl'
> [INFO] [com.tngtech.archunit.ArchConfiguration] Merging properties: The following properties have been overwritten by system properties: {resolveMissingDependenciesFromClassPath=true}
> ...
> [DEBUG] [com.tngtech.archunit.core.importer.JavaClassProcessor] Analyzing class 'my/project/service/infrastructure/service/PartnerConfigurationServiceImpl$1'
> [INFO] [com.tngtech.archunit.ArchConfiguration] Merging properties: The following properties have been overwritten by system properties: {resolveMissingDependenciesFromClassPath=true}

Clearly, the interface is not in the classpath, as it is in C:\Users\Vincent\IdeaProjects\my-project\domain\build\classes\java\main , while we load the content of  C:\Users\Vincent\IdeaProjects\my-project\infrastructure\build\classes\java\main (domain vs infrastructure)

but since `resolveMissingDependenciesFromClassPath=true`, I would expect it to be resolved somehow. 
Also, I am not sure why a `PartnerConfigurationServiceImpl$1`  is loaded as there's no inner class in `PartnerConfigurationServiceImpl`.

**Comment by vincent-fuchs** [comment]
@codecholeric Do you think I should have other interseting things in the logs ? I noticed that it seems to load the standard java classes, as I can see things like : 

> [INFO] [com.tngtech.archunit.ArchConfiguration] Merging properties: The following properties have been overwritten by system properties: {resolveMissingDependenciesFromClassPath=true}
> [DEBUG] [com.tngtech.archunit.core.importer.JavaClassProcessor] Analyzing class 'com/tngtech/archunit/core/domain/JavaModifier'
> [INFO] [com.tngtech.archunit.ArchConfiguration] Merging properties: The following properties have been overwritten by system properties: {resolveMissingDependenciesFromClassPath=true}
> [DEBUG] [com.tngtech.archunit.core.importer.JavaClassProcessor] Analyzing class 'com/tngtech/archunit/core/domain/JavaClass'
> [INFO] [com.tngtech.archunit.ArchConfiguration] Merging properties: The following properties have been overwritten by system properties: {resolveMissingDependenciesFromClassPath=true}
> [DEBUG] [com.tngtech.archunit.core.importer.JavaClassProcessor] Analyzing class 'org/mockito/MockitoAnnotations'
> [INFO] [com.tngtech.archunit.ArchConfiguration] Merging properties: The following properties have been overwritten by system properties: {resolveMissingDependenciesFromClassPath=true}
>  [DEBUG] [com.tngtech.archunit.core.importer.JavaClassProcessor] Analyzing class 'java/lang/Throwable'
> [INFO] [com.tngtech.archunit.ArchConfiguration] Merging properties: The following properties have been overwritten by system properties: {resolveMissingDependenciesFromClassPath=true}
> [DEBUG] [com.tngtech.archunit.core.importer.JavaClassProcessor] Analyzing class 'org/mockito/Mockito'

I've also tried to add on command line these properties :
  `-Darchunit.classResolver=com.tngtech.archunit.core.importer.resolvers.SelectedClassResolverFromClasspath -Darchunit.classResolver.args=my.company` , but no.. classes from another module, located in `my.company` package are not loaded...

**Comment by codecholeric** [comment]
The `SelectedClassResolverFromClasspath` can only load a subset of the classpath, so if `resolveMissingClassesFromClasspath` doesn't find these classes, neither will this one.
If this is happening during the run of the Gradle plugin, are you sure the classpath of the plugin contains those classes from the other module? I guess in the end you could easily try that by putting a `Class.forName("class.from.the.OtherModule")` on one of your `ArchConditions` and see if the class can be loaded during the run.

If not I could imagine two ways to go:
1) extend the classpath of the Gradle plugin to contain all necessary classes
2) supply a custom `ClassResolver` that knows how to find the classes from the other module

**Comment by vincent-fuchs** [comment]
thanks @codecholeric , you were right : `Class.forName `isn't able to load the interface from domain.

But I have a very basic question then : how come the class `MyImpl` compiles if the interface it implements is not on the classpath ? it would be on the classpath at compilation time, but not later when ArchUnit plugin executes ? 

looks more and more like a Gradle issue actually... I'll google some more..

**Comment by codecholeric** [comment]
Yes, the Gradle compiler plugin will have this class on the classpath. I guess the classpath of your plugin is configured differently? But yes, I think this is a Gradle thing, and not an ArchUnit issue...

**Comment by codecholeric** [comment]
Closing this for now, feel free to reopen!
