### ISSUE TITLE
Can ArchUnit issue warning and not error

### ISSUE THREAD

**Issue by smfaizalkhan** [TNG/ArchUnit#315]
Hi Team,

I have a scenario where i would like the implementer to be notified of the warning and not error
Please find the code below,instead of should(),is it possible to have can()
    
    @PublicAPI(usage = ACCESS)
      ArchRule 
     CLASSES_ANNOTATED_WITH_CONFIGURATION_PROP_
      SHOULD_HAVE_FIELDS_ANNOATED_WITH_JSR380VALIDATIONS =
      ArchRuleDefinition.priority(Priority.HIGH)
      .fields().that().areDeclaredInClassesThat()
       .areAnnotatedWith(ConfigurationProperties.class)
        .should(beAnnotatedWithJsr380ValidationAnnotations);

      @PublicAPI(usage = ACCESS)
      ArchRule 
     CLASSES_ANNOTATED_WITH_CONFIGURATION_PROP_
      SHOULD_HAVE_FIELDS_ANNOATED_WITH_JSR380VALIDATIONS =
      ArchRuleDefinition.priority(Priority.HIGH)
      .fields().that().areDeclaredInClassesThat()
       .areAnnotatedWith(ConfigurationProperties.class)
        .can(beAnnotatedWithJsr380ValidationAnnotations);

The ArchCondition Class
 
    public class BeAnnotatedWithJsr380ValidationAnnotations 
       extends ArchCondition<JavaField> {

       public BeAnnotatedWithJsr380ValidationAnnotations() {
        super("BeAnnotatedWithJsr380ValidationAnnotations");
        }

       @Override
       public void check(JavaField javaField, ConditionEvents conditionEvents) {
        if (javaField.getAnnotations().isEmpty()) {
            conditionEvents.add(SimpleConditionEvent.violated(javaField,
                    String.format("Field %s should be annotated with JSR380 Validation Annotation", 
         javaField)));
        }
        if (!javaField.getAnnotations().isEmpty()) {
            if (!atLeastOneAnnotationShouldBelongToJavaxValidationPackage(javaField))
                conditionEvents.add(SimpleConditionEvent.violated(javaField,
                        String.format("Field %s should be annotated with JSR380 Validation Annotation", 
             javaField)));
        }
    }

        private boolean atLeastOneAnnotationShouldBelongToJavaxValidationPackage(JavaField 
          javaField) {
        return javaField.getAnnotations().stream().anyMatch(fieldAnnotation -> 
       fieldAnnotation.getRawType().getPackageName().equals("javax.validation.constraints"));
         }

Regards,
Faizal

**Comment by hankem** [comment]
Which kind of _notification of the warning_ do you have in mind? `System.out.println`? Maybe even log to a specfic logger, for which you could configure more specific actions?

**Comment by smfaizalkhan** [comment]
What i meant is instead of highlighted text saying Architecture Violation if we have something like Architecture WARNING

**java.lang.AssertionError: Architecture Violation** [Priority: LOW] - Rule 'fields that are declared in 
       classes that are annotated with @ConfigurationProperties should 
       BeAnnotatedWithJsr380ValidationAnnotations' was violated (2 times):
      Field JavaField{com.ing.diba.mymgarchunit.testsample.SampleConfigurationProperties.prop} 
      should be annotated with JSR380 Validation Annotation
       Field JavaField{com.ing.diba.mymgarchunit.testsample.SampleConfigurationProperties.value} 
     should be annotated with JSR380 Validation Annotation

I understand that the Architecture Violation comes because of using 

       should(beAnnotatedWithJsr380ValidationAnnotations);
If  we have a choice to can()
    
    can(beAnnotatedWithJsr380ValidationAnnotations);

Then the ArchRule dosen't enforce the user,rather a warning

    *xxx.xxx.Warining: Architecture Warning**

**Comment by hankem** [comment]
If you don't want the rule to fail, but just print a warning, you could already do something like this:
<details><summary>imports</summary>

```java
import com.tngtech.archunit.base.DescribedPredicate;
import com.tngtech.archunit.core.domain.JavaAnnotation;
import com.tngtech.archunit.core.domain.JavaField;
import com.tngtech.archunit.lang.ArchCondition;
import com.tngtech.archunit.lang.ArchRule;
import com.tngtech.archunit.lang.ConditionEvents;

import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.fields;
```
</details>

```java
ArchRule warn_for_fields_in_ConfigurationProp_annotated_classes_without_JSR380_constraints_annotation =
    fields().that().areDeclaredInClassesThat().areAnnotatedWith(ConfigurationProperties.class)
        .and().areNotAnnotatedWith(annotationInPackage("javax.validation.constraints"))
        .should(printWarning("can be annotated with JSR 380 constraints annotation"));

DescribedPredicate<JavaAnnotation> annotationInPackage(String packageName) {
  return new DescribedPredicate<JavaAnnotation>("annotation in package " + packageName) {
    public boolean apply(JavaAnnotation annotation) {
      return annotation.getRawType().getPackageName().equals(packageName);
    }
  };
}

/** never fails! */
ArchCondition<JavaField> printWarning(String message) {
  return new ArchCondition<JavaField>("print warning " + message) {
    public void check(JavaField field, ConditionEvents events) {
      System.err.printf("Architecture Warning: %s %s %s\n",
          field.getDescription(), javaField.getSourceCodeLocation(), message);
    }
  };
}
```

This admittedly doesn't give you a summary such as:
>  Rule ... was violated (2 times)

but you might be able to build it on your own by pushing the warnings into a list and only print it "at the end", provided that your test framework provides such a hook, like `@org.junit.AfterClass` for JUnit 4 or `@org.junit.jupiter.api.AfterAll` for JUnit 5.

However, as the point of automated tests is IMO to either succeed or fail (just one bit of information; ideal for computers 😉), I'm not sure whether ArchUnit should more directly support warnings that do not fail the test, but are supposed to be read by humans.

**Comment by codecholeric** [comment]
Another possibility would be to use

```
Archrule rule = ...
EvaluationResult result = rule.evaluate(classes);
// do something with result, e.g. use FailureReport
```

This does not cause any `AssertionError` and leaves the handling of the result up to you. It doesn't support your requirements out of the box, but you can do something like

```
result.getFailureReport().toString().replace("Architecture Violation", "Architecture Warning");
```

:wink:

**Comment by codecholeric** [comment]
I have to admit that in most project I have not had good experiences with log things in tests because "someone will surely take care of it at some point" though :wink:
But as a manually triggered report for someone I would go with `rule.evaluate(..)`

**Comment by smfaizalkhan** [comment]
Thanks @codecholeric and @hankem 
Done with evalautionReport
