### ISSUE TITLE
JUnit5 assumptions

### ISSUE THREAD

**Issue by To6i** [TNG/ArchUnit#316]
I don't get assumptions from JUnit5 working. My idea is to enable / disable specific tests based on a configuration using assumptions. An example (Kotlin code):

```
@ArchTest
val rule: ArchRule =
    noClasses()
        .that().resideInAPackage("...")
        .should().dependOnClassesThat().resideInAnyPackage("...")
        .apply { assumeTrue(System.getProperty("key") == "value") }
```

But when executing the tests, they are silently skipped. All of them, not just the one which is using assumptions. It seems like the TestAbortedException thrown by assumeTrue() is not supported when executing ArchUnit tests...

**Comment by codecholeric** [comment]
Yes, I think it would be necessary to catch the thrown exception for a single execution and then mark the test as ignored, unfortunately this is not supported yet.
If anyone wants to add this feature I'm all open!!

If you want to execute tests conditionally of configuration / environment, you could also look into `@ArchTag`, the ArchUnit version of `@Tag`. (and then select tags within your build tool based on the environment)

**Comment by To6i** [comment]
While looking into this issue it became more and more clear that this is in fact not a real issue within archunit.

The example kotlin code from above will trigger an TestAbortedException while creating an instance of an ArchRule. Thus, this happens while archunit is discovering tests and not while executing those tests.

But JUnits [TestAbortedException](https://ota4j-team.github.io/opentest4j/docs/1.0.0/api/org/opentest4j/TestAbortedException.html) is meant to be thrown while the test is being executed!

> ... used to indicate that a test was aborted during execution

So my simple workaround is to create my own ArchRule implementation, that is forwarding all calls to the inner ArchRule. But it's calling the necessary assumptions within check() prior to invoking innerRule.check()

**Comment by codecholeric** [comment]
Oh yeah, that's true. In your example the `assume` happens inside of the wrong scope. But does it work if you throw the exception within the `check(..)` method? Or do you simply skip running check if the conditions are not satisfied? (but then the test would be marked succeeded and not skipped, right?)

**Comment by To6i** [comment]
It does work if the TestAbortedException is thrown within `check(...)`.

So I guess this issue can be closed

**Comment by codecholeric** [comment]
Ah, cool that the platform handles this :smiley:
