### ISSUE TITLE
Onion Architecture main class

### ISSUE THREAD

**Issue by cdietze** [TNG/ArchUnit#318]
Hello,
I tried out the `onionArchitecture()` style on a test project.
My test code (Kotlin):
```
    fun onionTest(importedClasses: JavaClasses) {
        val root = "hexarch_test"
        val rule = onionArchitecture()
            .domainModels("$root.domain.model..")
            .domainServices("$root.domain.service..")
            .applicationServices("$root.application..")
            .adapter("persistence", "$root.adapter.persistence..")
        rule.check(importedClasses)
    }
```
I put a main class which bootstraps the application the base package.
Now archunit complains that this main class accesses adapter code (which is the case).

I tried to add an exception for that class using: `importedClasses.that(doNot(equivalentTo(Main::class.java)))` but it would still complain that the adapter packages are accessed.

Maybe this issue does not occur if I were using DI where the adapter code would not be accessed directly (but actually still are indirectly / at runtime).

What's a good way to solve this? Using a DI-framework should not be mandatory IMO.

**Comment by hankem** [comment]
Did I understand correctly that you're basically doing the following?
```
val filteredClasses = importedClasses.that(doNot(equivalentTo(Main::class.java)))
rule.check(filteredClasses)
```

Restricting `importedClasses` after the import does not help in your case because ArchUnit builds the dependencies already during the class file import, as you can see with (I'm switching to Java syntax 😉):
```java
System.out.println(filteredClasses.get(YourAdapter.class).getDirectDependenciesToSelf());
```

As a temporarily workaround, you might be able to use a tuned `ClassFileImporter` to excluding `Main` already during import:
```java
new ClassFileImporter().withImportOption(new ImportOption() {
        @Override
        public boolean includes(Location location) {
            return !location.contains(Main.class.getName().replaceAll("\\.", "/"));
        }
    })
```

For a proper solution, we should IMO extend `OnionArchitecture` to support an `ignoreDependency​` mechanism [just as `LayeredArchitecture` does](https://javadoc.io/doc/com.tngtech.archunit/archunit/0.13.1/com/tngtech/archunit/library/Architectures.LayeredArchitecture.html#ignoreDependency(java.lang.Class,java.lang.Class))

**Comment by cdietze** [comment]
Thanks, @hankem.
Your workaround works!
Your suggestion to specify dependencies to ignore on `OnionArchitecture` sounds good to me.

**Comment by codecholeric** [comment]
Another possibility might be to use https://www.archunit.org/userguide/html/000_Index.html#_ignoring_violations and simply ignore all violations that contain `com.myapp.Main`.
But yes, I knew that the need for `ignoreDependency` would sooner or later come up :wink:

**Comment by michaelbannister** [comment]
Please forgive if this is a dumb question, but what is the syntax I need to use `.ignoreDependency` for the same case as described by @cdietze? My 'main' class constructs my application – no magic DI frameworks here – and I want to say that _it_ is allowed to depend on anything.

I've tried several variants on 
```kotlin
.ignoreDependency("com.mycompany.myapp.ApplicationKt", ".*")
```
but can't seem to make it work. Help much appreciated!

**Comment by cdietze** [comment]
@michaelbannister In my project I use:
```
.ignoreDependency(resideInAPackage("com.example.testproject.test.."), DescribedPredicate.alwaysTrue())
```

**Comment by Manfred73** [comment]
> @michaelbannister In my project I use:
> 
> ```
> .ignoreDependency(resideInAPackage("com.example.testproject.test.."), DescribedPredicate.alwaysTrue())
> ```

Took me a while to figure out how to exclude a test package until I found this post. This works perfectly!
