### ISSUE TITLE
About us

### ISSUE THREAD

**Issue by sal2row** [TNG/ArchUnit#32]
Hey there,
I'd need to find out, still not been able to, if it's possibile to prevent a class to use an annotation with a given value of one of its attributes.
for instance, to enforce a rule which prevents the value EAGER like

fetch = FetchType.EAGER

to be used in the annotation javax.persistence.OneToMany

thanks in advance,
s2r

**Comment by codecholeric** [comment]
Sure it's possible. The fluent API has at the moment no predefined way to express this, but there are a couple of different ways, to customize this, depending on what you want to emphasize. For example, if you want to express, that fields should not be annotated with `@OneToMany(fetch = EAGER)`, you could do it the following way:

```
import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.no;

@ArchTest
public static final ArchRule entitiesShouldntFetchEager =
        no(fields()).should(beAnnotatedWithOneToManyFetchingEager());

private static ClassesTransformer<JavaField> fields() {
    return new AbstractClassesTransformer<JavaField>("fields") {
        @Override
        public Iterable<JavaField> doTransform(JavaClasses collection) {
            Set<JavaField> result = new HashSet<>();
            for (JavaClass javaClass : collection) {
                result.addAll(javaClass.getFields());
            }
            return result;
        }
    };
}

private static ArchCondition<JavaField> beAnnotatedWithOneToManyFetchingEager() {
    return new ArchCondition<JavaField>("be annotated with @OneToMany(fetch = EAGER)") {
        @Override
        public void check(JavaField field, ConditionEvents events) {
            Optional<OneToMany> oneToMany = field.tryGetAnnotationOfType(OneToMany.class);
            boolean satisfied = oneToMany.isPresent() && oneToMany.get().fetch() == FetchType.EAGER;
            String message = String.format("Field %s.%s is%s annotated with @OneToMany(fetch = EAGER)",
                    field.getOwner().getName(), field.getName(), satisfied ? "" : " not");
            events.add(new SimpleConditionEvent(field, satisfied, message));
        }
    };
}
```
I plan to extend the fluent API in the future, so you get support like `noFields().that()...`, but at the moment you need the customized code (you could also write something like `noClasses().should(customConditionToCheckFields)`)
Does this help you?

**Comment by codecholeric** [comment]
Were you able to solve your problem? If yes, I could close this issue :wink:

**Comment by sal2row** [comment]
Yes mate,
sorry for the gap, I've been off work and catching up afterwards.
your example worked it out nice and smooth, you may close the issue and thanks a lot for the prompt reply!

**Comment by codecholeric** [comment]
No problem, happy that your problem was solved, I'll see, that at least the `fields()` `ClassesTransformer` of the example will be part of the provided fluent API with the next version :smiley: 
(the full fluent API for fields, methods, constructors is probably out of scope for me, at the moment)
