### ISSUE TITLE
ArchUnit test not executing in maven build

### ISSUE THREAD

**Issue by mkovacek** [TNG/ArchUnit#323]
Hi,

question, how to set up a maven project to run the arch unit test during maven build?
I have added archunit dependency and I'm using surefire plugin 

Unit tests are executing, but archunit not (in IntelliJ they are working)

`
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.0.0-M4</version>
                </plugin>
<dependency>
                <groupId>com.tngtech.archunit</groupId>
                <artifactId>archunit-junit5</artifactId>
                <version>0.13.1</version>
                <scope>test</scope>
            </dependency>

`

**Comment by hankem** [comment]
Could you solve the issue?

**Comment by mkovacek** [comment]
Yes, the test class didn't follow a naming convention (*Test / Test*), so that's why it was ignored🤦

**Comment by codecholeric** [comment]
I fell into that trap in the past, too :wink: Too easy to name `@ArchTests` `FooRules`...
