### ISSUE TITLE
cccccckddebddjgvdjvuekgidfelcfuvhgbkjutknurk

### ISSUE THREAD

**Issue by ngocng1310** [TNG/ArchUnit#327]

**Comment by ngocng1310** [comment]
Wron touch

**Comment by hankem** [comment]
Hehehe, I know these accidents very well... 😉
I had also generated several tickets, messages etc. by touching a YubiKey, until I realized that the OTP feature can actually be disabled by configuration, cf. for example [this documentation](https://support.yubico.com/support/solutions/articles/15000006440-accidentally-triggering-otp-codes-with-your-nano-yubikey).
