### ISSUE TITLE
Combining several ArchRules and checking them at once

### ISSUE THREAD

**Issue by daniel-kr** [TNG/ArchUnit#331]
Hey,

I have the situation that I want to apply the same `ArchRule` to many packages. Currently I am doing it this way:
```
@ArchTest
public static void components_only_be_accesed_by_self_or_application(JavaClasses javaCLasses) {
    for (String componentPackage : COMPONENT_PACKAGES) {
        ArchRule rule = ArchRuleDefinition.classes()
                .that().resideInAPackage(componentPackage)
                .should().onlyHaveDependentClassesThat().resideInAnyPackage(
                        ArrayUtils.add(APPLICATION_PACKAGES, componentPackage));
        rule.check(javaCLasses);
    }
}
```
The drawback with this is that `rule.check()` throws at the first package violating the rule. I would rather see all violating packages in the error message.

Is it possible to combine complete `ArcRule`s? I know that one can combine `DescribedPredicate`s or `ArchCondition`s. But that does not help in my case because the combination of predicate and condition has to be defined for each package.

Or is there maybe another way to achieve my goal?

Thanks in advance!

**Comment by codecholeric** [comment]
Does `com.tngtech.archunit.lang.CompositeArchRule` do what you want? It at least makes it possible to combine many rules into one rule (and give it one description if necessary).

**Comment by codecholeric** [comment]
Other than that it is also possible to use `rule.evaluate(..)` instead of `rule.check(..)`. The result could then be freely processed (or combined) and thrown when convenient...

**Comment by daniel-kr** [comment]
`CompositeArchRule` is the one I was looking for. Thanks a lot! :smiley:
