### ISSUE TITLE
Avoid checking against 3rd party libs

### ISSUE THREAD

**Issue by daniel-kr** [TNG/ArchUnit#332]
Hey again,

one more question:
Is it possible to avoid rule checks against 3rd party libs?
I would like to define the following rule:
```
@ArchTest
public static final ArchRule api_only_depend_on_itself = ArchRuleDefinition.classes()
        .that().resideInAnyPackage(API_PACKAGES)
        .should().onlyDependOnClassesThat().resideInAnyPackage(API_PACKAGES);
```
Unfortunately it complains about the classes depending on 3rd party stuff like even the JDK:
```
Method <foo.bar.getSomething()> has return type <java.io.File> in (Foo.java:0)
```
Is it possible to check only against classes that I actually imported?

I tried `resolveMissingDependenciesFromClassPath=false` but it did not help.

As a workaround I kind of negated the rule. But it decreases readability and is a bit unnatural. One has to think about what is actually meant.

```
@ArchTest
public static final ArchRule api_only_depend_on_itself = ArchRuleDefinition.classes()
        .that().resideOutsideOfPackages(API_PACKAGES)
        .should().onlyHaveDependentClassesThat().resideOutsideOfPackages(API_PACKAGES);
```

Thanks in advance!

**Comment by codecholeric** [comment]
There is no way to globally ignore all dependencies to certain packages, but I would suggest do create a combined predicate like

```
import static com.tngtech.archunit.core.domain.JavaClass.Predicates.resideInAnyPackage;
...
ArchRuleDefinition.classes()
    .that().resideInAnyPackage(API_PACKAGES)
    .should().onlyDependOnClassesThat(
        resideInAnyPackage(API_PACKAGES).or(resideInAnyPackage(LIBRARY_PACKAGES)));
```

**Comment by daniel-kr** [comment]
That works for me. Thank you! :smiley:
