### ISSUE TITLE
JUnit 5 support

### ISSUE THREAD

**Issue by echoAlexey** [TNG/ArchUnit#34]
Is there a planned junit 5 support?

**Comment by codecholeric** [comment]
I definitely plan on supporting JUnit 5. 
The problem at the moment is, that ArchUnit still supports Java 7 (there are still many big projects out there, that haven't made the jump to Java 8), but JUnit 5 needs Java 8.
I have already looked into it a little bit, in the past, back then I had the problem, that there was no simple extension mechanism for test case discovery, so discovering `@ArchTest` fields (without introducing some  base class) seemed not easily possible (without writing a whole `TestEngine`).
However, I've opened an issue at JUnit 5: https://github.com/junit-team/junit5/issues/1109
I'll check what they suggest, how to migrate the JUnit 4 support.
I somewhat dread the overhead of maintaining two branches of ArchUnit, one for Java 7 and one for Java 8, but if there is enough demand for JUnit 5, it might be worth it (including some nicer APIs for Java 8 that work better with lambdas)

**Comment by codecholeric** [comment]
I forgot to mention, you can already use ArchUnit with JUnit 5 at the moment, since it runs with any testing framework. Just include
```
com.tngtech.archunit:archunit:0.4.0
```
in your build, instead of the JUnit-Dependency. The only thing missing is caching out of the box, so it might make sense, to import the classes once and hold that in some static variable, to evaluate rules against, instead of importing the classes for every single rule again and again. But you could do
```
static final JavaClasses classes = new ClassFileImporter().importPackages("com.myapp");

@Test
void no_illegal_accesses() {
    classes()
        .that().resideInAPackage("..foo..")
        .should().onlyBeAccessed().byAnyPackage("..bar..")
        .check(classes);
}
```

**Comment by echoAlexey** [comment]
Thanks :) Np, we actually already use it. It was very easy to setup everything on junit5. Hopefully I will get some time to contribute extension for junit5.

**Comment by codecholeric** [comment]
Glad to hear that it's still usable :smiley: I'll keep this issue open though, because I definitely want to provide some support out of the box that takes care of things like caching.

**Comment by oova** [comment]
JUnit5 support would be very much appreciated but I suppose ArchUnit already works with JUnit5's compatibility layer?

**Comment by codecholeric** [comment]
I've just tried it real quick, the `ArchUnitRunner` seems to work fine with the junit5 vintage engine. I'm still on it though, I've just put my priorities on Java 9 support and the website during the last months. Since without Java 9 support it's unusable in any project compiling with JDK 9, without JUnit 5 support, it just means a minor workaround. Nevertheless, it will come :wink:
It's just not a completely trivial implementation, since there is no hook for the discovery mechanism in JUnit 5, so I have to write a separate test engine...

**Comment by codecholeric** [comment]
I've created a working draft, that seems to work as expected(TM) :wink: I would be really happy about anybody testing the current version and providing some feedback if it works in different scenarios. In particular:

* does it work with Maven & Gradle & JUnit ConsoleLauncher
* does it work with IDEs like IntelliJ, Eclipse or Netbeans
* does it work if you select 
  * the whole classpath
  * a package
  * a method
* does it work if you filter
  * classes
  * packages

The current SNAPSHOT can be obtained via Gradle by configuring the repository 

```
repositories {
    maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots'
    }
}
```

and including the dependencies similar to Jupiter

```
dependencies {
    // ...
    testCompile("com.tngtech.archunit:archunit-junit5-api:0.9.0-junit5-SNAPSHOT")
    testRuntime("com.tngtech.archunit:archunit-junit5-engine:0.9.0-junit5-SNAPSHOT")
}
```

For the Maven version, check out https://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven

**Comment by oova** [comment]
Thank you! This is very much appreciated.

Running the tests with Maven 3.5.3 works as expected (inc. running only single test classes or methods). I have not been able to run the test form IntelliJ (2018.1), though. I cannot run a single test class as IntelliJ does not even offer a "Run..." entry in the context menu. When I select the package and click "Run...", I can see the following stack trace:

```
WARNING: TestEngine with ID 'junit-archunit' failed to discover tests
java.lang.NoSuchMethodError: com.tngtech.archunit.junit.ReflectionUtils.withAnnotation(Ljava/lang/Class;)Lcom/tngtech/archunit/junit/ReflectionUtils$Predicate;
	at com.tngtech.archunit.junit.ArchUnitTestDescriptor.createChildren(ArchUnitTestDescriptor.java:86)
	at com.tngtech.archunit.junit.ArchUnitTestDescriptor.createTestDescriptor(ArchUnitTestDescriptor.java:78)
	at com.tngtech.archunit.junit.ArchUnitTestDescriptor.lambda$resolve$0(ArchUnitTestDescriptor.java:63)
	at com.tngtech.archunit.junit.ElementResolver$RequestedButUnresolvedClass.ifRequestedButUnresolved(ElementResolver.java:201)
	at com.tngtech.archunit.junit.ArchUnitTestDescriptor.resolve(ArchUnitTestDescriptor.java:63)
	at com.tngtech.archunit.junit.ArchUnitTestEngine.lambda$resolveRequestedPackages$2(ArchUnitTestEngine.java:105)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.tngtech.archunit.junit.ArchUnitTestEngine.resolveRequestedPackages(ArchUnitTestEngine.java:105)
	at com.tngtech.archunit.junit.ArchUnitTestEngine.discover(ArchUnitTestEngine.java:81)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:82)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:52)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

In my POM, I have
```
<dependencies>
  <dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter-api</artifactId>
    <scope>test</scope>
  </dependency>
  <dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter-engine</artifactId>
    <scope>test</scope>
  </dependency>
  <dependency>
    <groupId>org.junit.platform</groupId>
    <artifactId>junit-platform-launcher</artifactId>
    <scope>test</scope>
  </dependency>
  <dependency>
    <groupId>com.tngtech.archunit</groupId>
    <artifactId>archunit-junit5-api</artifactId>
    <version>${archunit.version}</version>
    <scope>test</scope>
  </dependency>
  <dependency>
    <groupId>com.tngtech.archunit</groupId>
    <artifactId>archunit-junit5-engine</artifactId>
    <version>${archunit.version}</version>
    <scope>test</scope>
  </dependency>
</dependencies>
...
<build>
  <plugins>
    <plugin>
      <artifactId>maven-surefire-plugin</artifactId>
      <dependencies>
        <dependency>
          <groupId>org.junit.platform</groupId>
          <artifactId>junit-platform-surefire-provider</artifactId>
          <version>${junit.surefire.provider.version}</version>
        </dependency>
        <dependency>
          <groupId>com.tngtech.archunit</groupId>
          <artifactId>archunit-junit5-engine</artifactId>
          <version>${archunit.version}</version>
        </dependency>
      </dependencies>
    </plugin>
  </plugins>
</build>
```
Am I doing something wrong?

**Comment by codecholeric** [comment]
Hmm, when I try to run it with IntelliJ 2018.1.5, your setup seems to work.
I've used platform `1.2.0`, what version have you tried? Exactly how described in https://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven?
What I've noticed though, is that IntelliJ did not work, if I've only put the `engine` dependency as config of the surefire plugin (IntelliJ does something weird then and tries to download platform `0.9.0-junit5-SNAPSHOT` then, so I think that is a bug there)
But your config seems to work for me, so I might need some more info.

**Comment by codecholeric** [comment]
Here is the POM I've tried:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>junit5-maven-consumer</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>1.8</java.version>
        <junit.jupiter.version>5.2.0</junit.jupiter.version>
        <junit.platform.version>1.2.0</junit.platform.version>
        <archunit.version>0.9.0-junit5-SNAPSHOT</archunit.version>
    </properties>

    <repositories>
        <repository>
            <id>sonatype-snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
    </repositories>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.7.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.19.1</version>
                <dependencies>
                    <dependency>
                        <groupId>org.junit.platform</groupId>
                        <artifactId>junit-platform-surefire-provider</artifactId>
                        <version>${junit.platform.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit.jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit.jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-launcher</artifactId>
            <version>${junit.platform.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.tngtech.archunit</groupId>
            <artifactId>archunit-junit5-api</artifactId>
            <version>${archunit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.tngtech.archunit</groupId>
            <artifactId>archunit-junit5-engine</artifactId>
            <version>${archunit.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
```

**Comment by oova** [comment]
Thanks for the feedback. It's working for me as well now. I had to manually remove the old (version 0.5) archunit dependencies from my Maven module in IntelliJ's project settings in order to see the "Run..." entries in the context menu. IntelliJ got confused when I migrated my old test classes to the new archunit version, I suppose.

Keep up the great work!

**Comment by codecholeric** [comment]
That's great :smile: Happy that it works!! (it really feels a little bit like being lost on the sea to try to support those hundreds of possible combinations of environments, build tools and IDEs, which is why I'm happy about any sort of feedback)

**Comment by tobiasdiez** [comment]
Looks good! It would be nice if you could also implement an [parameter resolver](https://junit.org/junit5/docs/5.0.2/api/org/junit/jupiter/api/extension/ParameterResolver.html), so that code like this work (personally, I find this more intuitive than the `@ArchTest` form):

````java
@ExtendWith(ArchUnitExtension.class)
class ArchTest {

    @Test
    void describeRule(JavaClasses classes) {
        classes.that().haveNameMatching(".*Dao")
                      .should().resideInAPackage("..dao..");
    }

}
````
This is similar to the old `ArchUnitRunner`.

**Comment by codecholeric** [comment]
Hey, your example shows one of the reasons for the `@ArchTest` field form though, you forgot to check those supplied classes :wink: 
Nevertheless you can already pretty much write a test that looks very similar to what you want, only that ArchUnit JUnit5 does not depend on the Jupiter API, so per se you don't even have `@Test` in your scope, if you only include `archunit-junit5-api` as a dependency.
Long story short, what you can write right now, is

```
@ArchTest
static void describeRule(JavaClasses classes) {
    classes.that().haveNameMatching(".*Dao")
            .should().resideInAPackage("..dao..")
            .check(classes);
}
```

This is consistent with the ArchUnit JUnit 4 support, in the future we'll probably drop the requirement that the method needs to be static to make the tests nicer readable with Kotlin, but for now this is still pretty similar to your suggestion (except for `@ArchTest` instead of `@Test`)

Implementing the `ParameterResolver` would be a pretty separate way from the `ArchUnitTestEngine`, so I'm not sure it's worth it, to support a completely parallel way just for 4 letters optics). It would pretty much require a separate artifact with a separate dependency tree (depending on Jupiter). Originally I wanted to integrate this with Jupiter, but there is no hook into the discovery mechanism, so the recommendation from the JUnit team was to write a separate `TestEngine`.

**Comment by LaunchPairs** [comment]
It works so far with my project. I also have no problems with IntelliJ 2018.1. 

With the following version numbers (JUnit4 + JUnit5 support) I had to make a few exclusions - but this is more of a JUnit problem:

```xml
<jupiter.version>5.2.0</junit.jupiter.version> 
<junit.platform.version>1.2.0</junit.platform.version> 
<junit.version>4.12</junit.version> 
<junit.vintage.version>${junit.version}.2</junit.vintage.version> 
```

**Comment by codecholeric** [comment]
Thanks for letting me know :smiley: 
Can you tell me what conflicts exactly you had? I would think that the ArchUnit API should not depend on any JUnit 5 artifacts, and the ArchUnit Engine should only depend on `org.junit.platform:junit-platform-engine:1.2.0` am I wrong? So I don't see, where they would collide with the versions you listed?
Thanks for the feedback!!

**Comment by LaunchPairs** [comment]
We use the maven dependency convergence check (https://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html) in our projects which says:

```
Dependency convergence error for org.junit.platform:junit-platform-engine:1.2.0 paths to dependency are:
+-my.test:my-archunit-example:4.0.0-SNAPSHOT
  +-com.tngtech.archunit:archunit-junit5-engine:0.9.0-junit5-20180715.221712-1
    +-com.tngtech.archunit:archunit-junit5-engine-api:0.9.0-junit5-SNAPSHOT
      +-org.junit.platform:junit-platform-engine:1.2.0
and
+-my.test:my-archunit-example:4.0.0-SNAPSHOT
  +-org.junit.platform:junit-platform-runner:1.2.0
    +-org.junit.platform:junit-platform-launcher:1.2.0
      +-org.junit.platform:junit-platform-engine:1.2.0
and
+-my.test:my-archunit-example:4.0.0-SNAPSHOT
  +-org.junit.jupiter:junit-jupiter-engine:5.2.0
    +-org.junit.platform:junit-platform-engine:1.2.0
and
+-my.test:my-archunit-example:4.0.0-SNAPSHOT
  +-org.junit.vintage:junit-vintage-engine:4.12.2
    +-org.junit.platform:junit-platform-engine:1.0.2
```

So the problem really shouldn't be related to archunit, but to `org.junit.vintage:junit-vintage-engine:4.12.2`. Declaring a dependency-management entry for this dependency also solves the problem - without exclusions.

```xml
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.junit.platform</groupId>
                <artifactId>junit-platform-engine</artifactId>
                <version>1.2.0</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

**Comment by rweisleder** [comment]
@LaunchPairs JUnit changed the versioning scheme of junit-vintage-engine in 5.1.0 to align with junit-jupiter-engine. So you can use
```
<dependency>
    <groupId>org.junit.vintage</groupId>
    <artifactId>junit-vintage-engine</artifactId>
    <version>5.2.0</version>
    <scope>test</scope>
</dependency>
```

See commit https://github.com/junit-team/junit5/commit/1562208a3111d919b5505514baac87912870f533

**Comment by codecholeric** [comment]
Yes, I would guess that the outdated version of `junit-vintage-engine` should be the problem, but at least the ArchUnit dependency branch looks valid.

**Comment by LaunchPairs** [comment]
Yes, this solved the dependency convergence issue. Thanks @rweisleder
