### ISSUE TITLE
`onlyCallMethodsThat(..)` does not work as expected for non-resolvable methods

### ISSUE THREAD

**Issue by codecholeric** [TNG/ArchUnit#340]
see https://github.com/TNG/ArchUnit/issues/87#issuecomment-610007967

For methods where ArchUnit cannot resolve the target of a method call `onlyCallMethodsThat(..)` reports a violation (since non of the method it tried to resolve, i.e. 0, matched the predicate).
This is a confusing behavior in this case an should be corrected. I.e. if the method cannot be resolved, then the predicate should be satisfied, not failing.
It is in particular relevant, because calls to non-imported classes are typically not resolvable and at the same time probably not important (e.g. the `array.clone()` method in the example below).

An example of the behavior can be found [here](https://github.com/JohT/snippets/tree/master/archunit-enum-reproducer) (thanks a lot to @JohT for providing the example)

**Comment by JohT** [comment]
Thanks a lot for fixing this. I've updated my [reproducer](https://github.com/JohT/snippets/tree/master/archunit-enum-reproducer). It now works fine with ArchUnit 0.14.1.
