### ISSUE TITLE
Make message format of failing rules configurable

### ISSUE THREAD

**Issue by codecholeric** [TNG/ArchUnit#343]
Related to #301 and #214

We should provide a way to adjust the way rules report their violations. There is already `com.tngtech.archunit.lang.ConfiguredMessageFormat` which at the moment has only one configured instance. We might be able to make this configurable by a custom message format via `archunit.properties`:

```
messageFormat=com.my.CustomMessageFormat
```

For this to work `ConfiguredMessageFormat` should be turned into an interface with some sort of factory. We can then ponder if for #301 we should add an additional structured element like `solutions` to the result of an evaluated rule.

:warning: We should definitely consider to pass on a richer context than just raw text lines. It should be simple to pass on the full `ConditionEvent`, which would then also be able to provide the `correspondingObject` (i.e. `JavaMethodCall`, `Dependency`, ...), compare #361

**Comment by idosal** [comment]
@codecholeric Hey, I'm interested in picking this up. Should I implement it similarly to `ViolationLineMatcherFactory`?

**Comment by codecholeric** [comment]
@idosal sorry, I overlooked your offer!! That would be great :smiley: (if I'm not too late meanwhile :disappointed:). And yes, I think it can be done similar to `ViolationLineMatcherFactory`.

I would 

* extract an interface `MessageFormat` from `ConfiguredMessageFormat`, 
* create `DefaultMessageFormat implements MessageFormat` (that contains exactly the logic from `ConfiguredMessageFormat` at the moment) 
* make `ConfiguredMessageFormat.get()` return either the configured `MessageFormat` from `archunit.properties` or as fallback the `DefaultMessageFormat` with the old logic

Of course we could ponder of `ConfiguredMessageFormat` should then be called `MessageFormatFactory` to be consistent with the naming of `ViolationLineMatcherFactory` :thinking: But that part is at least internal, so the important thing to get right from the beginning will be the interface `MessageFormat`.
