### ISSUE TITLE
Cannot create slices for the same package level

### ISSUE THREAD

**Issue by vprudnikov** [TNG/ArchUnit#353]
Hello,

I failed to find in neither API nor documentation on how to create slices for the same package level.
Let's image I have the following package structure:
```
com.example
        |- infrastructure
           |- security
           |- web
        |- sub-domain
           |- infrastructure
              |- persistence
              |- web
```

I don't want those classes from `..sub-domain.infrastructure.web` access classes from `..sub-domain.infrastructure.persistence` and vice-versa.
However, it should still be OK to access e.g. `com.example.infrastructure.security` from `..sub-domain.infrastructure.web`.

My rule looks like so: 
```
slices().matching("..infrastructure.(*)..")
                    .namingSlices("Infrastructure sub-layer '$1'")
                    .should().notDependOnEachOther()
                    .as("Infrastructure sub-layers");
```

However, my test fails when it comes to the dependency between `com.example.infrastructure.security` and `..sub-domain.infrastructure.web`.

**Is it possible to define a rule that checks sub-packages per ONE `infrastructure` package only?**
- all sub-packages of `com.example.infrastructure`
- all sub-packages of `..sub-domain.infrastructure`
- all sub-packages of `..sub-domain2.infrastructure`
and so on...

**Comment by codecholeric** [comment]
I think the standard syntax does not do what you want, but I see two ways to achieve what you want:

1) If you want to use the default API, you can probably only combine several rules, e.g.

```
CompositeArchRule
                .of(slices().matching("com.example.infrastructure.(*)..")
                        .namingSlices("Infrastructure sub-layer '$1'")
                        .should().notDependOnEachOther())
                .and(slices().matching("..sub-domain.infrastructure.(*)..")
                        .namingSlices("Infrastructure sub-layer '$1'")
                        .should().notDependOnEachOther());
```

Here each single rule is specific about the level of the infrastructure slices you want to check.
Pro: Easy to write without custom code
Contra: Less convenient to maintain (if a new level of slices appears you have to add it here).

2) `notDependOnEachOther()` will always check ALL the slices you have assigned for cross dependencies. So if you create slices on "different levels", this is not mapped into the condition. But you can write your own condition, e.g.

```
slices().matching("..(*).infrastructure.(*)..")
    .namingSlices("Infrastructure sub-layer '$1:$2'")
    .should(new ArchCondition<>("not depend on each other on the same level") {
        private List<Slice> allSlices;

        @Override
        public void init(Iterable<Slice> allSlices) {
            this.allSlices = stream(allSlices.spliterator(), false).collect(toList());
        }

        @Override
        public void check(Slice slice, ConditionEvents events) {
            List<Slice> sliceDependencies = slice.getDependenciesFromSelf().stream()
                    .flatMap(d -> allSlices.stream().filter(s -> s.contains(d.getTargetClass())).findFirst().stream())
                    .collect(toList());

            List<Slice> sliceDependenciesOnSameLevel = sliceDependencies.stream()
                    .filter(s -> s.getNamePart(1).equals(slice.getNamePart(1)))
                    .collect(toList());

            sliceDependenciesOnSameLevel.forEach(sliceDependency ->
                    events.add(SimpleConditionEvent.violated(slice, String.format("%s depends on %s", slice.getDescription(), sliceDependency.getDescription()))));
        }
    })
```
(no warranties and you should maybe clean it up a little :wink:)
Pro: Grows automatically if you add new levels of slices, as long as they match the pattern
Contra: More custom code / more complex to understand

That filters the dependencies between slices for the ones where the name part `1` (the package captured before `.infrastructure.` in the pattern) is equal and only for those reports the error (I assume the package before `.infrastructure.` uniquely identifies the level of the slices)

Does that help you?

**Comment by vprudnikov** [comment]
Hi @codecholeric ,
Thanks for the quick reply!

Option 1 is not an option for me because I have this test in a common library.

I also tried the option 2 but it worked! Thanks!

I have just one question: is it possible to check anything else rather than the slice's `namePart`?
I have the following structure so the test fails in one particular case:

```
com.example
        |- infrastructure
           |- security
           |- web
        |- example
           |- infrastructure
              |- persistence
              |- web
```

you can see that `example` matches `example` :)

Thank you!

**Comment by codecholeric** [comment]
Sorry for getting back so late. If you use the pattern matching to define slices, you will always have some parts of the full package name as identifier grouping together the respective classes.
That said, you can use the pattern `(**).infrastructure.(*)..` to match not only the relative package name (being ambiguous), but the full package name before `infrastructure`.
Your pattern solves the problem though, as long as the last two relative packages names before `infrastructure` are a unique combination :wink:

**Comment by vprudnikov** [comment]
@codecholeric thanks for the hint!

`..(**).infrastructure.(*)..` pattern did NOT work but `(**).infrastructure.(*)..` did work fine! :)

**Comment by codecholeric** [comment]
Yeah, that's why I wrote `(**).infrastructure.(*)..` as pattern :wink: 
The pattern `..(**).infrastructure.(*)..` first greedily matches any number of packages, then `(**)` should match one or more packages, but since `..` already matched all the packages before, I would think you arrive at the same semantics as `..(*).infrastructure.(*)..`
Anyway, glad it works for you now!! :smiley:

**Comment by codecholeric** [comment]
BTW. if your issue is solved, is it okay if I close the issue?

**Comment by hankem** [comment]
Issue seems to be solved.
