### ISSUE TITLE
Import of class files is broken on Windows

### ISSUE THREAD

**Issue by rweisleder** [TNG/ArchUnit#356]
I noticed that some tests fail on my Windows with the current master. For example, the test https://github.com/TNG/ArchUnit/blob/0c23de0d5bdf943df3c79a7026f877061eb4b709/archunit/src/test/java/com/tngtech/archunit/core/importer/ClassFileImporterTest.java#L2084-L2089 fails with
```
Expecting:
  <[]>
to contain exactly (and in same order):
  <["com.tngtech.archunit.core.importer.testexamples.simpleimport.ClassToImportOne",
    "com.tngtech.archunit.core.importer.testexamples.simpleimport.ClassToImportTwo"]>
but could not find the following elements:
  <["com.tngtech.archunit.core.importer.testexamples.simpleimport.ClassToImportOne",
    "com.tngtech.archunit.core.importer.testexamples.simpleimport.ClassToImportTwo"]>
```

This error came in after merging #347 into master (commit b7bf88a4d21bd9ac73175ac81b51b60ad9077b84). The state before (commit 06f94b208d18f0f88e37bfd833205151859d900f) looks good.

**Comment by codecholeric** [comment]
Can you provide some info about your JDK version and runtime environment?

**Comment by rweisleder** [comment]
I tried running the tests with Java 1.8.0_60, 11.0.6 and 14.0.0 in IntelliJ (run as JUnit test) and Gradle (`./gradlew :archunit:test`) on Windows 10.

**Comment by rweisleder** [comment]
The cause of this error is that in https://github.com/TNG/ArchUnit/blob/0c23de0d5bdf943df3c79a7026f877061eb4b709/archunit/src/main/java/com/tngtech/archunit/core/importer/Locations.java#L132-L134 we compare `searchedJarEntryPrefix = NormalizedResourceName.from("com/tngtech/archunit/core/importer/testexamples/simpleimport/ClassToImportOne.class")` with `name = NormalizedResourceName.from("com\tngtech\archunit\core\importer\testexamples\simpleimport\ClassToImportOne.class")`
