### ISSUE TITLE
Improve Cycle Detection Report Readability

### ISSUE THREAD

**Issue by jzheaux** [TNG/ArchUnit#361]
When I use `beFreeOfCycles`, the report is comprehensive, but unreadable for large projects:

```
java.lang.AssertionError: Architecture Violation [Priority: MEDIUM] - Rule 'slices assigned from full package slices should be free of cycles' was violated (7 times):
Cycle detected: Slice org.springframework.security.config.web.server -> Slice org.springframework.security.config.web.server.headers -> Slice org.springframework.security.config.web.server
Dependencies of Slice org.springframework.security.config.web.server
Method <org.springframework.security.config.web.server.ServerHeadersDsl.contentTypeOptions(kotlin.jvm.functions.Function1)> calls constructor <org.springframework.security.config.web.server.headers.ServerContentTypeOptionsDsl.<init>()> in (ServerHeadersDsl.kt:49)
Method <org.springframework.security.config.web.server.ServerHeadersDsl.contentTypeOptions(kotlin.jvm.functions.Function1)> calls method <org.springframework.security.config.web.server.headers.ServerContentTypeOptionsDsl.get$spring_security_config()> in (ServerHeadersDsl.kt:49)
Method <org.springframework.security.config.web.server.ServerHeadersDsl.xssProtection(kotlin.jvm.functions.Function1)> calls constructor <org.springframework.security.config.web.server.headers.ServerXssProtectionDsl.<init>()> in (ServerHeadersDsl.kt:64)
Method <org.springframework.security.config.web.server.ServerHeadersDsl.xssProtection(kotlin.jvm.functions.Function1)> calls method <org.springframework.security.config.web.server.headers.ServerXssProtectionDsl.get$spring_security_config()> in (ServerHeadersDsl.kt:64)
Method <org.springframework.security.config.web.server.ServerHeadersDsl.cache(kotlin.jvm.functions.Function1)> calls constructor <org.springframework.security.config.web.server.headers.ServerCacheControlDsl.<init>()> in (ServerHeadersDsl.kt:79)
Method <org.springframework.security.config.web.server.ServerHeadersDsl.cache(kotlin.jvm.functions.Function1)> calls method <org.springframework.security.config.web.server.headers.ServerCacheControlDsl.get$spring_security_config()> in (ServerHeadersDsl.kt:79)
// ...
```

The lack of indentation and numbering makes it difficult to visually parse.

One way to fix this would be to add some indentation to the report:

```
java.lang.AssertionError: Cycles Detected 
Cycle detected: Slice org.springframework.security.config.web.server -> 
                Slice org.springframework.security.config.web.server.headers -> 
                Slice org.springframework.security.config.web.server
	1. Dependencies of Slice org.springframework.security.config.web.server
		 - Method <org.springframework.security.config.web.server.ServerHeadersDsl.contentTypeOptions(kotlin.jvm.functions.Function1)> calls constructor <org.springframework.security.config.web.server.headers.ServerContentTypeOptionsDsl.<init>()> in (ServerHeadersDsl.kt:49)
		 - Method <org.springframework.security.config.web.server.ServerHeadersDsl.contentTypeOptions(kotlin.jvm.functions.Function1)> calls method <org.springframework.security.config.web.server.headers.ServerContentTypeOptionsDsl.get$spring_security_config()> in (ServerHeadersDsl.kt:49)
		 - Method <org.springframework.security.config.web.server.ServerHeadersDsl.xssProtection(kotlin.jvm.functions.Function1)> calls constructor <org.springframework.security.config.web.server.headers.ServerXssProtectionDsl.<init>()> in (ServerHeadersDsl.kt:64)
		 - Method <org.springframework.security.config.web.server.ServerHeadersDsl.xssProtection(kotlin.jvm.functions.Function1)> calls method <org.springframework.security.config.web.server.headers.ServerXssProtectionDsl.get$spring_security_config()> in (ServerHeadersDsl.kt:64)
		 - Method <org.springframework.security.config.web.server.ServerHeadersDsl.cache(kotlin.jvm.functions.Function1)> calls constructor <org.springframework.security.config.web.server.headers.ServerCacheControlDsl.<init>()> in (ServerHeadersDsl.kt:79)
		 - Method <org.springframework.security.config.web.server.ServerHeadersDsl.cache(kotlin.jvm.functions.Function1)> calls method <org.springframework.security.config.web.server.headers.ServerCacheControlDsl.get$spring_security_config()> in (ServerHeadersDsl.kt:79)
// ...
```

However, it may be more desirable to give testers the flexibility to output things how they want to. It appears that ArchUnit is designed to allow testers to customize the output of a given `EvaluationResult` by using `ViolationHandler`:

```java
EvaluationResult result = // ... do test
result.handleViolations((object, message) -> {
    // use object as context for customizing the report
});
```

But, if I want to do this with cycle detection, I can't since `Cycle` isn't part of the public API. Perhaps in due time, the Cycle API will become public, in which case my issue is resolved. 

Are there other ways I should be considering? Happy to provide a PR, given some guidance.

**Comment by codecholeric** [comment]
Yes, you're right, in bigger projects the output pretty much demands you to search through it with CTRL-F or similar, I have noticed that, too.
I like your idea to add indentation, since that would be a super quick thing to implement and probably indeed help a lot to quickly parse the output visually.

I also see your point about `Cycle` not being public and thus `handleViolations` not being applicable :thinking: Maybe every item that gets added to violations by ArchUnit itself should be part of the public API, because otherwise you can't use it with `handleViolations`. I think all other objects added to violations (as the "corresponding item") are already part of the core API and thus public. There is no real reason `Cycle` is not public besides that I haven't wanted to commit to maintaining the structure :wink: But in fact it has been stable for a long time, so maybe we could just make it public...

There is one other issue that probably also touches your point: #343
But I'm wondering if that should be pimped a little to not only provide raw violation lines at the point :thinking: It feels that it  would be a lot more powerful, if the configured message format would get the whole `ConditionEvent` that would also provide the domain object attached, instead of just raw text lines. I'll add a comment.

**Comment by jzheaux** [comment]
Thanks for your thoughtful response. It's helpful to see a bigger picture.

> Maybe every item that gets added to violations by ArchUnit itself should be part of the public API, because otherwise you can't use it with `handleViolations`.

I think that makes sense, although I get your point about not wanting to make something public until it's baked. 

I noticed `handleViolations` is experimental, though, and perhaps that should harden b4 `Cycle` becomes public, unless you see additional reasons for making `Cycle` public.

> I like your idea to add indentation, since that would be a super quick thing to implement and probably indeed help a lot to quickly parse the output visually.

Cool, I'll put together a PR for that.
