### ISSUE TITLE
fluent transformers eg. all mehods of given classes

### ISSUE THREAD

**Issue by hexmind** [TNG/ArchUnit#370]
Hi, thanks for a great tool!
What I want achieve is to use `should` for a different code unit than for `that`.
Is there any possibility to write code like this?
```
ArchRuleDefinition.classes()
  .that().haveSimpleNameEndingWith("Dto")
  .map(classesToMethods) // <- non existing part of API
  .should().bePublic()  // methods, not classes
  .check(classes);
```
Is there a fluent approach to transformers possible or any other than presented below?
https://www.archunit.org/userguide/html/000_Index.html#_rules_with_custom_concepts

**Comment by hankem** [comment]
For members of classes, you can use (cf. [Composing Member Rules](https://www.archunit.org/userguide/html/000_Index.html#_composing_member_rules)):
```java
ArchRuleDefinition.methods()
    .that().areDeclaredInClassesThat().haveSimpleNameEndingWith("Dto")
    .should().bePublic()
```

**Comment by hexmind** [comment]
Great. It looks like what I was looking for but in reverse order (what isn't a problem).
Thanks for a quick response.
