### ISSUE TITLE
A ton of log lines generated when specifying system properties during test run

### ISSUE THREAD

**Issue by ldebruijn** [TNG/ArchUnit#375]
We use ArchUnit extensively and we're loving it. Recently after we added additional tests some of the runs during our CI started failing due to excess logging. 

```
14:27:41.711 [INFO ] com.tngtech.archunit.ArchConfiguration.getMergedProperties() @315 - Merging properties: The following properties have been overwritten by system properties: {freeze.store.default.allowStoreUpdate=false, freeze.store.default.allowStoreCreation=false}
 14:27:41.712 [INFO ] com.tngtec
 Job's log exceeded limit of 4194304 bytes.
```

The `The following properties have been overwritten by system properties: ` is repeatedly logged which seems to be due to the code in https://github.com/TNG/ArchUnit/blob/master/archunit/src/main/java/com/tngtech/archunit/ArchConfiguration.java#L315

```
Properties getMergedProperties() {
            Properties result = createProperties(this.properties);
            Properties overwritten = getSubProperties("archunit", System.getProperties());
            if (!overwritten.isEmpty()) {
                LOG.info("Merging properties: The following properties have been overwritten by system properties: {}", overwritten);
            }
            result.putAll(overwritten);
            return result;
        }
```

Running maven/surefire with debugging enabled and specifying some system properties as described in https://www.archunit.org/userguide/html/000_Index.html#_overriding_configuration seems to hit the log line repeatedly when using a breakpoint on line 315 (as referenced in the code file above)

 ```
mvn -Dmaven.surefire.debug -Darchunit.freeze.store.default.allowStoreUpdate=false -Darchunit.freeze.store.default.allowStoreCreation=false test
```

We use the overriding of configuration during CI to prevent accidentally committing one of the configuration files with properties to allowing freeze store updates to master (the files are committed to the repo, but should be committed with `false`. In the event we make a mistake we rely on the configuration override to not allow store updates during the CI run, causing tests to fail.) https://www.archunit.org/userguide/html/000_Index.html#_configuration

It seems valid that this snippet of code is hit repeatedly. I don't think however it's meant to log this line so excessively.

I'll happily provide a PR with a solution for this, but I'd like to get your opinion as to what would be a fitting solution. Should the log line be deleted, should the log level be configurable, should it only fire x times or something entirely different?

**Comment by codecholeric** [comment]
Thanks for raising this! You're absolutely right, this should definitely not be logged on every property access :thinking: I did want this merge method to be repeatedly called, because I wanted the overridden properties to update during the run if necessary, but I did not consider the log implications :disappointed: 
Thanks for the offer to fix this!! When I'm looking at the code I feel like the closest thing to keep the original behavior would be to

* make `overwrittenProperties` also a field (like the original properties)
* when calling `getMergedProperties()` do an early return if the `overwrittenProperties` have not changed, i.e. if `getSubProperties("archunit", System.getProperties())` is equal to the old `overwrittenProperties`
* if not then update `overwrittenProperties` and execute the log statement

What do you think? Do you think that makes sense?
I guess to mitigate your problem for now you can at least just set the logger of `com.tngtech.archunit.ArchConfiguration` to `WARN`, right?

**Comment by ldebruijn** [comment]
Sounds like a plan! I did indeed increase the log level of the logger to WARN.
I'll see if I can work something out tomorrow.

A colleague of mine had the sharp comment that this behavior was introduced after an update to one of our dependencies. The updated dependency pulled in following new transitive dependencies:

```
org.apache.logging.log4j:log4j-api:jar:2.13.3:compile
org.apache.logging.log4j:log4j-core:jar:2.13.3:compile
org.apache.logging.log4j:log4j-slf4j-impl:jar:2.13.3:compile
```

These dependencies were not in our project before. After checking out the code in ArchUnit I noticed you use the same dependencies for logging, which is likely the reason why this 'issue' suddenly appeared for us.

**Comment by codecholeric** [comment]
Yeah, it might be that you simply didn't have a `SLF4J` binding before, then ArchUnit would log nothing :wink: 
Now after sleeping over it I was wondering though: Yes, that method is suboptimal to log on every property access, but I'm puzzled that that would overload your logs :thinking: This must also mean that the properties are accessed way more often than I would think :thinking:

**Comment by ldebruijn** [comment]
I was thinking the same thing initially, but without all the context I considered it by design. If you like I can get you a few traces that often call the `getMergedProperties()`.

**Comment by codecholeric** [comment]
I already found one: For every class it is determined if the MD5 sum is activated. Could of course cache this parameter somewhere, but I think it's easier to simply cache the properties so it doesn't matter if they are checked often...
