### ISSUE TITLE
Avoid using Optional.getOrThrow(RuntimeException) in our code

### ISSUE THREAD

**Issue by rweisleder** [TNG/ArchUnit#391]
Currently, we have some usages of `Optional.getOrThrow(RuntimeException)` in our code like this:
https://github.com/TNG/ArchUnit/blob/38f6748c4e5d5758cfb3c6509aefb616cf83e475/archunit/src/main/java/com/tngtech/archunit/core/domain/JavaClass.java#L677-L679

The usage of this method requires to create a new `Throwable` object and fill the stack trace, whether the exception is needed or not. See also [The hidden performance costs of instantiating Throwables](http://normanmaurer.me/blog/2013/11/09/The-hidden-performance-costs-of-instantiating-Throwables/).

It may not have a big impact, but I think we should avoid the usage of this method in our code.

**Comment by codecholeric** [comment]
Yeah, I saw that already, too :frowning_face: Didn't want to change it just in one place back then, but yes, we should change it everywhere. We should introduce a `Supplier` version like Java 8 would have out of the box (I'm really wondering how long we should support Java 7, since it would definitely make the code base more consistent and standardized)...

**Comment by Bananeweizen** [comment]
I would like to request a predefined ArchUnit rule (in the examples project?) in addition to the code change in the library, such that users of the library can look for the same issue in their code.

**Comment by hankem** [comment]
@Bananeweizen, I guess you can simply define a rule similar to this one:
```java
    @ArchTest
    static final ArchRule do_not_use_Optional_getOrThrow = noClasses()
            .should().callMethod(Optional.class, "getOrThrow", RuntimeException.class)
            .because("a Throwable should only be instantiated when actually needed");
```

(Just make sure you check for the method you're interested in. My example is for [`com.tngtech.archunit.base.Optional`](https://javadoc.io/doc/com.tngtech.archunit/archunit/latest/com/tngtech/archunit/base/Optional.html). As far as I can see, [`java.util.Optional`](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html) has only the [variant with the `Supplier<Throwable>`](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html#orElseThrow-java.util.function.Supplier-) anyways, and [`com.google.common.base.Optional`](https://guava.dev/releases/29.0-jre/api/docs/com/google/common/base/Optional.html) doesn't seem to have a such a method at all.)
