### ISSUE TITLE
How to ignore abstract classes?

### ISSUE THREAD

**Issue by rhwood** [TNG/ArchUnit#393]
I have a rule that certain classes should be annotated when they implement an interface (`JsonHttpProvider` in this case):

```
    @ArchTest
    public static final ArchRule JsonHttpProviderIsAnnotated = classes()
            .that().areAssignableFrom(JsonHttpProvider.class)
            .should().beAnnotatedWith(ServiceProvider.class);
```

In some cases, I can reduce some code duplication by creating an abstract class `AbstractJsonHttpProvider` that should not be annotated with `ServiceProvider`. Further reductions can be made by creating some abstract subclasses of `AbstractJsonHttpProvider` like `AbstractSetJsonHttpProvider` and `AbstractArrayJsonHttpProvider`.

I know I can provide specific exceptions by patterns based on class name, but is there a way to ignore all abstract classes in a rule?

**Comment by hankem** [comment]
Are you looking for something like this:
```
@ArchTest
public static final ArchRule JsonHttpProviderIsAnnotated = classes()
        .that().areAssignableFrom(JsonHttpProvider.class)
        .and().doNotHaveModifier(JavaModifier.ABSTRACT)
        .should().beAnnotatedWith(ServiceProvider.class);
```

**Comment by rhwood** [comment]
@hankem Thank you. That is precisely what I was looking for.
