### ISSUE TITLE
NPE from getDirectDependenciesFromSelf() called on a JavaClass stub

### ISSUE THREAD

**Issue by hankem** [TNG/ArchUnit#397]
I've run into an issue with transitive dependencies not being imported completely.

Here's a simple example (which, admittedly, looks strange on its own 😃) to illustrate it:
```java
new ClassFileImporter().importClasses(java.lang.Object.class)
        .get(java.lang.Object.class)
        .getMethod("finalize").getThrowsClause().getTypes().get(0)  // java.lang.Throwable
        .getMethod("getStackTrace").getRawReturnType().getComponentType()  // java.lang.StackTraceElement
        .getDirectDependenciesFromSelf();
```
Since 85506e2fcae12c2838e49700ef07635c58faa054, I'm getting a
```
java.lang.NullPointerException
	at com.tngtech.archunit.core.domain.JavaClass.getDirectDependenciesFromSelf(JavaClass.java:894)
```
The line number is for ArchUnit 0.14.1, but [`getDirectDependenciesFromSelf`](https://github.com/TNG/ArchUnit/blob/v0.14.1/archunit/src/main/java/com/tngtech/archunit/core/domain/JavaClass.java#L892-L895) is currently a one-liner anyways; the issue is that `javaClassDependencies` is not initialized, i.e. that `JavaClass.completeFrom(ImportContext)` was not called. But here, I don't know what's expected for stubs.

**Should I be able to `getDirectDependenciesFromSelf()` from a stub `JavaClass`?** (Anyways, the NPE isn't a nice result for sure.)

The hypothesis that the error might be because `Throwable.getStackTrace()` returns `StackTraceElement[]` (which seems to be imported correctly), whereas I'm asking for dependencies from `StackTraceElement`, is supported by the following simpler example:
```java
new ClassFileImporter().importClasses(DependsOnArray.class)
        .get(DependsOnArray.class)
        .getField("array").getRawType().getComponentType()  // Element
        .getDirectDependenciesFromSelf();
```
with
```java
static class DependsOnArray {
    Element[] array;
}

static class Element {
}
```

I'm still puzzled though why the same issue does not show up in:
```java
new ClassFileImporter().importClasses(java.lang.Throwable.class)
        .get(java.lang.Throwable.class)
        .getMethod("getStackTrace").getRawReturnType().getComponentType()  // java.lang.StackTraceElement
        .getDirectDependenciesFromSelf();
```

**Comment by codecholeric** [comment]
To answer your first question, no, you should not be able to get dependencies from a stub class :wink: If you want to analyse a class you should import it. Nevertheless I do agree that a NPE is not particularly nice, so I think we should fix this and give stub classes simply empty dependencies. None of the rules API accesses stub classes that way, that's probably why it hasn't shown so far :wink: 
I might have an explanation for your confusion though :thinking: `Throwable` has a direct dependency to `StackTraceElement`. Thus if you resolve missing dependencies from classpath (the default) you'll end up with a correctly imported class `StackTraceElement`. For `Object`, `Throwable` is already a missing dependency and the resolution of missing dependencies does not work transitively. Thus the transitive dependency `Throwable -> StackTraceElement` is not resolved but replaced by a stub (only direct dependencies are resolved with the configured resolver, after that the chain is cut by introducing stubs). At least that would make sense to me, what do you think?
But yes, a NPE is never correct behavior, so we should fix that :wink:

**Comment by hankem** [comment]
Thanks, @codecholeric!

> If you want to analyse a class you should import it.

Fair enough. When looking for transitive dependencies, I'll anyways limit the recursion to the package I've actually imported.
(Playing with the code, I once just gave it a try to grab everything that's there; this is how my recursion ended up in checking transitive dependencies of `java.lang.Object`... 😃)

> we should fix this and give stub classes simply empty dependencies

That would be great! I guess that this will be as simple as providing an API to recognize a stub `JavaClass`, which does not exist right now, if I'm not mistaken?

**Comment by codecholeric** [comment]
One question is what should happen if you call `getDirectDependencies{From/To}Self()` on a stub class :thinking: If we want to be consistent with other places, it would just return an empty set. It could of course also throw an exception that this class is a stub and you should not do checks like this on it, but I don't know. And kind of orthogonal there is the question if it should be possible to detect / query if a class is a stub. We could add a method like `JavaClass.isImported()` or similar :thinking:
