### ISSUE TITLE
JavaFields and composition hierarchy

### ISSUE THREAD

**Issue by pavetok** [TNG/ArchUnit#405]
It is possible to extend JavaField concept to reflect composition hierarchy?
CompostiteJavaFields would allow to pick fields that have specific superfields or subfileds.
For example `fields().that().haveSuperField().areAssignableTo(Foo.class).should()...`

**Comment by hankem** [comment]
I must admit that I'm not familiar with the term _'superfield'_; does that relate to [hidden fields](https://docs.oracle.com/javase/tutorial/java/IandI/hidevariables.html) from superclasses? For example:
```java
class A {
    char field = '1';
}

class B extends A {
    int field = 2;

    void print() {
        System.out.println(super.field);
    }
}

class C extends B {
    String field = "3";

    void print() {
        super.print();
        System.out.println(super.field);
        System.out.println(field);
    }

    public static void main(String[] args) {
        new C().print();
    }
}
```
Should something like `fields().that().haveASuperFieldAssignableTo(int.class)` refer to `C`'s `field` (because `B`'s `field` is assignable to `int`)?

**Comment by pavetok** [comment]
Term 'superfield' is not standard. I used it by analogy with `superclass`. No, that doesn't relate to hidden fields and doesn't relate to inheritance at all. It's all about composition.
```java
class A {
    char field1;
    char field2;
}

class B {
    List<A> field;
}
```
There is composition relation between `B` and `A`. Consequently `B.field` is `superfield` for `A.field1` and `A.field2`. `A.field1` and `A.field2` are `subfields` of `B.field`.

**Comment by pavetok** [comment]
It seems would be useful to make composition hierarchy explicit. This is just one of the possible implementations which came to mind. Surely there are others.

**Comment by hankem** [comment]
Ah, thanks; I now understand that you're interested in composition.
I'm however still trying to recognize what you actually want to achieve... 😉

----

For direct composition of classes, you can already inspect a field's raw type as a `JavaClass` (including its own fields), via [`JavaField#getRawType()`](https://javadoc.io/doc/com.tngtech.archunit/archunit/latest/com/tngtech/archunit/core/domain/JavaField.html#getRawType()).

So for example (this is a pure fantasy), if I wanted to ensure that every field with a "superfield" assignable to `char` is called `charContent`, I could use
```java
ArchRule rule = fields()
        .that(haveSuperfieldsAssignableTo(char.class))
        .should().haveName("charContent");

DescribedPredicate<JavaField> haveSuperfieldsAssignableTo(Class<?> clazz) {
    return DescribedPredicate.describe(
            "have superfields assignable to " + clazz,
            javaField ->
                    javaField.getRawType().getFields().stream()
                            .anyMatch(superfield -> superfield.getRawType().isAssignableTo(clazz))
    );
}
```

<details>
<summary>Example</summary>

With

```java
class Content {
    char ch;
}
```

such a rule would give me:

```java
class Container {
    Content charContent;   // okay

    Content otherContent;  // violates rule "fields
                           // that have superfields assignable to char
                           // should have name 'charContent'"
}
```
</details>

----

For more general composition, you'd however probably want to recognize collections, such as `List<A>` in [your example](https://github.com/TNG/ArchUnit/issues/405#issuecomment-664952223).
The current release ArchUnit 0.14.1 does unfortunately not provide access to generic type parameters. ☹
(But #398 introduces `JavaField#getType()`, so this can probably be tackled in the not-so-distant future.)

**Comment by pavetok** [comment]
Thanks for detailed answer. This approach allow to select fields in top-down direction. I need to select them in bottom-up direction.

Initially I faced the following problem. I want to select all fields and subfields which defined in class assignable to some interface. Then I want to verify that they have some annotation.
```java
class A {
    @Tag(1)
    char field1;  // valid
    char field2;  // invalid
}

class B implements Z {
    @Tag(1)
    A field;  // valid
}
```
So all that fields satisfy my criterion. How to select them without something like "field hierarchy"? Neither class `A` nor fields of `A` know anything about their "composition usages".

**Comment by hankem** [comment]
So want to build a rule like this?
> For every `@Tag`ged field _`f`_ (like `B.field` in [your example](https://github.com/TNG/ArchUnit/issues/405#issuecomment-665462160)), some fields of _`f`_'s class (i.e. `A`) should be `@Tag`ged as well?

I believe that this should be possible by implementing a custom `ArchCondition<JavaField>` for the `should(`…`)` part instead of the custom `DescribedPredicate<JavaField>` for the `that(`…`)` part from [my previous message](https://github.com/TNG/ArchUnit/issues/405#issuecomment-665297243)).

**Comment by pavetok** [comment]
I want to build a rule like this

> Given class that implements interface `Z`. Every field (nested fields too) should be `@Tag`ged.

So I see. I can implement a custom `ArchCondition<JavaClass>` in which recursively get all fields and check their annotations. It looks like top-down selection in `ArchCondition<JavaClass>`. I thought bottom-up selection in `DescribedPredicate<JavaFiled>` would be more appropriate. But apparently I'm wrong :)

**Comment by codecholeric** [comment]
Then maybe to wrap it up, if I understand correctly the sentence you specify you can put one to one to an `ArchRule` like this:

```
classes().that().implement(SomeInterface.class).should(onlyHaveFieldsAnnotatedWith(Tag.class));

private ArchCondition<JavaClass> onlyHaveFieldsAnnotatedWith(final Class<? extends Annotation> annotationType) {
  return new ArchCondition<JavaClass>("only have fields annotated with @" + annotationType.getSimpleName()) {
    @Override
    public void check(JavaClass javaClass, final ConditionEvents events) {
      javaClass.getAllFields().stream()
          .filter(f -> !f.isAnnotatedWith(annotationType))
          .forEach(f -> events.add(SimpleConditionEvent.violated(f,
              "Field " + f.getFullName() + " is not annotated with @" + annotationType.getSimpleName())));
        }
    };
}
```

`javaClass.getAllFields()` should give you all fields, including the fields of super classes. You might want to filter to only include fields declared in classes within your project though (and maybe non-static fields?), or you'll end up having violations in classes like `java.lang.Object` :wink: 

I'll close this issue for now, feel free to reopen if there is still something unclear!
