### ISSUE TITLE
Add the ability to customize the `ImportPlugin`

### ISSUE THREAD

**Issue by bobtiernay-okta** [TNG/ArchUnit#412]
For really large and complex projects, one can easily get into a situation that many jars are on the classpath. Sometimes the test needs to analyze some of these, but not all. Having the ability to prune off unrelated jars early in the processing would save significant processing time.

**Comment by codecholeric** [comment]
But can't you easily do this with `ImportOption`? -> https://www.archunit.org/userguide/html/000_Index.html#_import

With a custom `ImportOption` you can always have something like

```
Set<String> selectedJarNames = Collections.singleton("some.jar");
JavaClasses selected = new ClassFileImporter()
  .importClasspath(new ImportOptions().with(location -> 
      selectedJarNames.stream().anyMatch(jarName -> location.contains(jarName + "!/"))));
```

Or am I misunderstanding your issue?

**Comment by bobtiernay-okta** [comment]
Maybe you're right. I think I wrote this while trying to optimize a very large code based with many jar dependencies. It was spending a lot of time analyzing the classpath and I ended up doing something very similar. Closing for now.
