### ISSUE TITLE
Assert that all fields that are primitive type or collection of primitive type

### ISSUE THREAD

**Issue by GeeJoe** [TNG/ArchUnit#440]
I want to make sure that all fields of a Class should be primitive type or collection of primitive type:
```java
class MyClass {
 String a;
 int b;
 float c;
 int[] d;
 List<String>;
}
```
How can I achieve that?
I've tried the following code to make part of it works
```java
javaField.rawType.isPrimitive // check whether the field is primitive type
javaField.rawType.simpleName == "String" // check whether it's String
```
But how can I check whether the field is an Array of primitive type, such as `int[]` `byte[]`, or a List of primitive type, such as `List<String>`, etc?

In other words:
- How can I know the generic type inside a `List<T>`?
- How to describe an Array of a primitive type?

**Comment by hankem** [comment]
* ArchiUnit 0.14.1 unfortunately doesn't support generic types yet (#115). 🤷
* For array types, you can easily call `getComponentType()` until you find the "base component type" (e.g. `int[][]` → `int[]` → `int`). Based on that, you can use something like:
```java
        fields()
            .that().areDeclaredIn(MyClass.class)
            .should().haveRawType(DescribedPredicate.describe("that is primitive or an array of primitives", type -> {
                while (type.isArray()) {
                    type = type.getComponentType();
                }
                return type.isPrimitive();
            }));
```

(`JavaClass`  could probably get a `getBaseComponentType()` convenience function at some point, as this is often needed when working with arrays.)

**Comment by GeeJoe** [comment]
When will ArchiUnit support generic types？

**Comment by hankem** [comment]
I'm sorry, I cannot promise a date. I just know that it is a really tough issue... 🤷
However, 💪 @codecholeric has recently mentioned in https://github.com/TNG/ArchUnit/issues/423#issuecomment-701025933 that
> [he] really want[s] to push for the Generics support with all the (very limited) capacity [he has] at the moment!

**Comment by GeeJoe** [comment]
🤝
