### ISSUE TITLE
Meta-annotation not registered unless you analyze the package

### ISSUE THREAD

**Issue by csemrau** [TNG/ArchUnit#450]
We stumbled over the following issue while extending our ArchUnit test coverage.

We have a "platform" module. Some of the public classes, interfaces, enums, and annotations are annoted with a "PublicApi" annotation and intended for use in projects, some are platform-internal (and subject to be refactored in the future).
We have several "project" modules which depend on the "platform". They should only depend on the "public api" of the "platform", i.e. classes annotated with "PublicApi".

This works well for classes, interfaces, and enums, but not for annotations.
* An ArchUnit test which only analyzes the "project" but not the "platform" fails to detect that a "platform" annotation is itself annotated as "PublicApi" and therefore should be usable in the "project". Usage of such annotations is reported as rule violation.
* If the test analyzes both the "project" and the "platform", it succeeds as expected and the annotation is detected as being part of the "public api".

Does this fall into the same group of issues as https://github.com/TNG/ArchUnit/issues/342 and the referenced issues?

Kind regards,
Christian

**Comment by hankem** [comment]
I agree with your conclusion:
If an annotation of an imported object isn't imported itself, ArchUnit 0.14.1 doesn't know the annotation's annotations.

If also importing "platform" classes (at least the package containing the relevant annotation(s)) from your "project" tests has a bad performance impact, you can use the workaround suggested in https://github.com/TNG/ArchUnit/issues/274#issuecomment-575199185 to selectively import the relevant annotation(s).

**Comment by csemrau** [comment]
Thank you for the confirmation and the suggestion.

Since the affected annotations are currently all over the place in the "platform", I compiled a list of them and added them as additionally allowed classes in the rule. The rule is now "classes outside the platform should only depend on classes that reside outside the platform or are annotated with PublicApi or are in the explicit annotations list". That rule is defined in the "platform", so the "projects" can remain unchanged when the list of annotations changes.

Since we have many "projects" that are tested independently, and a "platform" with a way too big surface area, not needing to analyze the "platform" for each "project" saves a total of 8 minutes test runtime. :-)

**Comment by hankem** [comment]
I'm glad to hear that you have a workaround that isn't too inconvenient! Given that there is already a pull request (#408), which looks very promising to me, I'm actually confident that the issue of missing meta-annotations will be fixed with the next release... 🤞
