### ISSUE TITLE
Classes that are only referenced as array components are not resolved themselves

### ISSUE THREAD

**Issue by csemrau** [TNG/ArchUnit#455]
In continuation of #450, we found another unexpected behaviour in ArchUnit.

Given the `@PublicApi` annotation described in that other issue, and a "platform" class `User` that is annotated as public API.
Given a "platform" interface that declares a method `User[] getUsers()`, and a "project" implementation of the interface, where the method is implemented as

    public User[] getUsers() { return new User[0]; }

Furthermore, this method contains the only reference to the `User` class from this "project". (The interface has some more methods that are implemented in the "project" class, but we don't need any "users" for this implementation.)

Then the following rule fails when the "project" is analyzed, but not the "platform":

    @ArchTest
    public static final ArchRule only_use_annotated_platform_classes = ArchRuleDefinition
            .classes()
            .that().resideOutsideOfPackage("platform..")
            .should().onlyDependOnClassesThat(
                    resideOutsideOfPackage("platform..")
                            .or(haveTypeOrArrayComponentType(annotatedWith(PublicApi.class)))
            );

It uses this array-inspecting predicate based on some other thread I found here.

    public static DescribedPredicate<JavaClass> haveTypeOrArrayComponentType(final DescribedPredicate<? super JavaClass> componentTypePredicate) {
        return new DescribedPredicate<JavaClass>("have type or array component type " + componentTypePredicate.getDescription()) {
            @Override
            public boolean apply(JavaClass javaClass) {
                boolean applies = componentTypePredicate.apply(javaClass);
                if (applies || !javaClass.isArray()) {
                    return applies;
                }
                JavaClass componentType = javaClass.getComponentType();
                return this.apply(componentType);
            }
        };
    }

The rule fails with this message:

    Method <project.MyUserService.getUsers()> has return type <[Lplatform.User;> in (MyUserService.java:0)

As a workaround I found that referencing the `User` class directly somewhere in the "project" will resolve that class, and then the usage in the array is no longer reported as a violation:

    private static void workAround(User u) {}

Another workaround is of course to also analyze the package containing the `User` class.

**Comment by codecholeric** [comment]
Thanks for raising this! I think it would make sense to automatically resolve all component types transitively :thinking: 
AFAIS at the moment only referenced types are resolved, but not component types of referenced array types.
I think similarly to recursively importing all missing classes for the type hierarchy and importing all classes missing for accesses to other classes, we should also import all component type of such missing types :thinking:

**Comment by codecholeric** [comment]
This should already be fixed in ArchUnit  0.15.0. At least component types are now automatically resolved.
If there are still problems, feel free to reopen with a minimal example of what is still missing. Thanks!!
