### ISSUE TITLE
Detect the given interfaces extends X

### ISSUE THREAD

**Issue by naspredam** [TNG/ArchUnit#461]
I am using spring-boot JPA, and on spring boot they have the capability to define interfaces to be repositories, like this:

```
package com.example.service;

import com.example.service.model.UserData;
import org.springframework.data.jpa.repository.JpaRepository;

public interface UserRepository extends JpaRepository<UserData, Integer> {

}
```

where we do not need to implement this interface. Here, the extension is the main goal. So that, I would need to extend for a limited amount of classes. For reactive is another set of interfaces to be extended from.

I have tried to define the following arch-test:

```
    @ArchTest
    static final ArchRule repositories_should_extends_jpaFromSpring =
            classes().that()
                    .haveSimpleNameEndingWith("Repository")
                    .should()
                        .implement(JpaRepository.class);
```

But I found this false positives, I tried to change the interface to be List for instance, and it passed... I also tried to use `beAssignedFrom` but again, it does never fails.

Used:
MacOS
Java 15
archunit-junit5:0.14.1

Sorry if this was already reported, tried to check the issues but I was not able to see this.

**Comment by hankem** [comment]
Just as a first quick answer (before I can look into the semantics of `should().implement`): Does 
```
classes().that().haveSimpleNameEndingWith("Repository").should().beAssignableTo(JpaRepository.class)
```
work for you?

**Comment by naspredam** [comment]
Thanks for the reply.

That's the problem, it should, and it actually passes the test... however, if you change to:

```
classes().that().haveSimpleNameEndingWith("Repository").should().beAssignableTo(String.class)
```

It also passes... which is a false positive.

What I am feeling is that, as I am not implementing the class, so keeping as interface, not sure if the methods `implement` / `beAssignableTo` / `beAssignableFrom` does the validation.

**Comment by codecholeric** [comment]
Regarding your original question, I think the terminology "implement" can only apply to a class implementing an interface. ArchUnit does not consider an interface to "implement" anything, because the syntax also does not allow `interface Foo implements ...`, but only `interface Foo extends ...`.
So going with `assignableTo(..)` instead seems correct. As to the question why 

```
classes().that().haveSimpleNameEndingWith("Repository").should().beAssignableTo(String.class)
```

would not be violated, I have no idea :thinking: That does not seem right. What about 

```
classes().should().beAssignableTo(String.class)
```

Are you sure your `UserRepository` really is part of the classes that get checked? And are you really using `assignableTo(..)` and not `assignableFrom(..)`? (which has the opposite semantics)

**Comment by naspredam** [comment]
The point is that I do not have classes implementing the interface.

I would like to validate the interface, regardless of any class implementing it.

What I am trying to do is, I have this code:

```
package com.example.service;

import com.example.service.model.UserData;
import org.springframework.data.jpa.repository.JpaRepository;

public interface UserRepository extends JpaRepository<UserData, Integer> {

}
```

here I would need to check that the **interfaces** with name ending with _Repository_ to be extending the interface _JpaRepository_?

**Comment by naspredam** [comment]
I have just tried _beAssignableTo_ and it worked, I think I change the port and then it was not doing the proper asserts.

With that, I will close this, thanking the responses.
