### ISSUE TITLE
Ignoring Violations Using archunit_ignore_patterns.txt not work

### ISSUE THREAD

**Issue by GeeJoe** [TNG/ArchUnit#467]
I want to ignore some violations by creating a file `archunit_ignore_patterns.txt` in the root of the classpath as below
![image](https://user-images.githubusercontent.com/13412420/98430999-ba9aa600-20ec-11eb-952f-e38d9370fed7.png)

But it seems not work as the output below
![image](https://user-images.githubusercontent.com/13412420/98431021-e1f17300-20ec-11eb-80ba-bd017f57c98e.png)

**Comment by codecholeric** [comment]
Sorry to hear that you have problems with this. It should work the way you are trying to. But are you sure that your `archunit_ignore_patterns.txt` is really in the root of your classpath? From the screenshot it looks like you put it next to the `build.gradle` which is typically not a resource on the classpath.

In standard Gradle layouts you would typically create `src/test/resources` and put it directly in there to have it in the root of the classpath. Maybe try that

* create the folder `src/test/resources`
* refresh your Gradle config in IntelliJ (it should pick up and mark the `resources` folder)
* move `archunit_ignore_patterns.txt` into that folder

Does this help you?

**Comment by GeeJoe** [comment]
Thx! it work!

**Comment by codecholeric** [comment]
Glad to hear id :smiley: Then I'll take the liberty to close this issue :wink: 
Feel free to reopen, if further problems with this should arise!
