### ISSUE TITLE
Question: JPA Converter best practices

### ISSUE THREAD

**Issue by humeurvagabonde** [TNG/ArchUnit#476]
Hi

I'm really sorry to create an issue about that. I try stackoverflow but my question was misunderstood.

My issue is
* I'm using the onion rule
* I'm putting my custom JPA converters inside the persistence adapter
* I'm annotating my domain model using JPA (team decision , alternatives was using XML or creating a separate persistence model

Result : I got a violation about persistence adapter import inside domain model layer. Logic.

How can you handle this usecase ? do you add an entry inside `archunit_ignore_patterns.txt` ?

Thanks

**Comment by codecholeric** [comment]
I would maybe try to go with `OnionArchitecture.ignoreDependency(..)`. You could maybe use the version with predicates, like

```
onionArchitecture()
  ...
  .ignoreDependency(resideInAPackage("..domain.."), assignableTo(Converter.class))
```

I don't know how your concrete setup looks like, so let me know if you have any further questions (or I misunderstood your problem :wink:)

**Comment by humeurvagabonde** [comment]
Thanls a lot !
I already have some ignoreDepency predicates, I don't know why I wanted to use something else.
You clear my mind . 
We can close this issue.

A last one: do  you prefer question here or Stackoverflow ?

**Comment by codecholeric** [comment]
Questions here are fine :wink: I know people always have some sort of hesitance to post here, but in the end I like it to just have one channel to watch and maintain. It's easy to add some label "question" to the issue to separate these from other issues, if necessary. But so far I usually find questions are quick enough to solve that they don't even need that. So no worries, feel free to post further questions :smiley:
