### ISSUE TITLE
How to suppress checking dependencies to 3rd-party packages

### ISSUE THREAD

**Issue by MLThal** [TNG/ArchUnit#489]
Hi,

I am writing some ArchUnit tests checking the dependencies like this:

```
@ArchTest
  public static final ArchRule check_controller_dependencies =
      classes()
          .that()
          .resideInAPackage("..controller..")
          .should()
          .onlyAccessClassesThat()
          .resideInAnyPackage("..controller..", "..service..");
```

These tests fail because, naturally, the classes access some third-party libs (java, spring, logging, ...) as well. I want to suppress checking these classes - or, in other words, I only want to check the dependencies of our own code.

Currently I am going with this solution ([presented here](https://stackoverflow.com/a/57167800/3984221)):

```
  private static final String[] COMMON_PACKAGES = {"java..", "javax..", "org..", "jakarta.."};

  private static String[] commonPackagesAnd(String... packages) {
    return ArrayUtils.addAll(packages, COMMON_PACKAGES);
  }

  @ArchTest
  public static final ArchRule check_controller_dependencies =
      classes()
          .that()
          .resideInAPackage("..controller..")
          .should()
          .onlyAccessClassesThat()
          .resideInAnyPackage(commonPackagesAnd("..controller..", "..service.."));
```
I'd like to ask if there's a more native way to do this?

Thanks in advance

**Comment by codecholeric** [comment]
Principally I think your solution is fine. If you explicitly want to whitelist the dependencies, you have to specify them like this. If your mindset is "I don't care about any external dependencies, but I want to specify exactly which other application packages my package can use", you could also go for something like

```
import static com.tngtech.archunit.base.DescribedPredicate.doNot;
import static com.tngtech.archunit.core.domain.JavaClass.Predicates.resideInAnyPackage;
...
@ArchTest
  public static final ArchRule check_controller_dependencies =
      classes()
          .that()
          .resideInAPackage("..controller..")
          .should()
          .onlyAccessClassesThat(
              resideInAnyPackage("..controller..", "..service..")
                  .or(doNot(resideInAnyPackage("com.myapp..")))
          );
```

where `com.myapp...` identifies the root of your application. I.e. you write "only access class that either are the allowed packages, or the target resides outside of my app".

**Comment by codecholeric** [comment]
Did this solve your question?

**Comment by MLThal** [comment]
Hi,

well, yes, sure. You said, there is no better way, so I have to stick with this approach :) From this point of view, my question is solved, unless I am not happy with that ;)

Thanks for your help, nonetheless! :)

Kind regards!
