### ISSUE TITLE
@ArchTest : Getting No Tests Were Found

### ISSUE THREAD

**Issue by milindbangar79** [TNG/ArchUnit#492]
Hi,

I liked the idea of ArchUnit and started exploring the examples and some applying to my code as well.

I am referring to the following example (https://github.com/TNG/ArchUnit-Examples/blob/master/example-junit5/src/test/java/com/tngtech/archunit/exampletest/junit5/CodingRulesTest.java) , which I updated t my package and just running on IDE (IntelliJ).

Removed the ```private``` qualifier from the tests, but keep getting "No Tests Were Found"

I am using Junit5 dependency and have also added the junit-launcher dependencies in POM.

Where am I be going wrong?

Thanks in advance.

Regards
Milind

**Comment by codecholeric** [comment]
Did you use the setup mentioned in https://www.archunit.org/userguide/html/000_Index.html#_junit_5 ?
The only dependency you should need to run the ArchUnit test is

```
<dependency>
    <groupId>com.tngtech.archunit</groupId>
    <artifactId>archunit-junit5</artifactId>
    <version>0.14.1</version>
    <scope>test</scope>
</dependency>
```

So `junit-jupiter` or launcher dependencies should be unnecessary. What happens if you run the build from the command line? Is Maven executing the test?

**Comment by codecholeric** [comment]
BTW. I think I also had problems with a too old version of IntelliJ (when JUnit 5 support was fairly fresh). So if your IntelliJ is very dated, you could also check, if you also have the problem with a newer version.

**Comment by milindbangar79** [comment]
Hi @codecholeric ,

thanks for the response. 

Updated the dependencies and made the changes .. The tests are now running.

However , from coding rules perspective, I am not sure why the following is failing , as it's n agreed approach to set values of private variables in class (primitive types to be specific).

 <com.springboot.jwt.security.jwt.JWTUtils.jwtExpirationMs> is annotated with @Value -- Which should not be flagged.

```@Autowired
JWTUtils jwtUtils;``` ---> should be flagged, which is correct.

Thanks
Milind

**Comment by milindbangar79** [comment]
Forgot to mention, I am using latest version of IntelliJ (2020.3)

**Comment by codecholeric** [comment]
I'm not sure I understand you correctly, so maybe you could specify

* what rule are you executing exactly?
* what is the outcome you would expect?
* what happens instead?

Thanks!

**Comment by milindbangar79** [comment]
Hi @codecholeric ,

- what rule are you executing exactly? -- ```NO_CLASSES_SHOULD_USE_FIELD_INJECTION```
- what is the outcome you would expect? -- For class level fields , where ```@Value``` annotation is used , it should not throw a violation, but expected for properties which are essentially beans annotated with ```@Autowired``` (IMHO, its  debatable )
- what happens instead? --- for ```@Value``` I am getting a rule violation and test fails.

From the logs 👍 
``` Field <com.springboot.jwt.security.jwt.JWTUtils.jwtExpirationMs> is annotated with @Value in (JWTUtils.java:0)```

Hope I was clear.

**Comment by hankem** [comment]
The `ArchRule NO_CLASSES_SHOULD_USE_FIELD_INJECTION = noFields().should(BE_ANNOTATED_WITH_AN_INJECTION_ANNOTATION)` relies on
```java
static ArchCondition<JavaField> beAnnotatedWithAnInjectionAnnotation() {
    ArchCondition<JavaField> annotatedWithSpringAutowired = beAnnotatedWith("org.springframework.beans.factory.annotation.Autowired");
    ArchCondition<JavaField> annotatedWithSpringValue = beAnnotatedWith("org.springframework.beans.factory.annotation.Value");
    ArchCondition<JavaField> annotatedWithGuiceInject = beAnnotatedWith("com.google.inject.Inject");
    ArchCondition<JavaField> annotatedWithJakartaInject = beAnnotatedWith("javax.inject.Inject");
    ArchCondition<JavaField> annotatedWithJakartaResource = beAnnotatedWith("javax.annotation.Resource");
    return annotatedWithSpringAutowired.or(annotatedWithSpringValue)
            .or(annotatedWithGuiceInject)
            .or(annotatedWithJakartaInject).or(annotatedWithJakartaResource)
            .as("be annotated with an injection annotation");
}
```
It was discussed whether `org.springframework.beans.factory.annotation.Value` should be included, but it was argued that 
> `@Value` can be used on constructor parameters. So there is no need to use `@Value` on fields.

cf. https://github.com/TNG/ArchUnit/pull/289#discussion_r365860944.

But anyways, if your architectural constraints are different, you can always introduce custom rules for your specific needs.
(I personally see ArchUnit's [`GeneralCodingRules`](https://github.com/TNG/ArchUnit/blob/master/archunit/src/main/java/com/tngtech/archunit/library/GeneralCodingRules.java) – in particular such a sophisticated one – mostly as an inspiration... 😉)

**Comment by milindbangar79** [comment]
Thanks @hankem for sharing the rationale. It was helpful.

I will close the issue now.

**Comment by hankem** [comment]
Always happy to help! 😃

**Comment by milindbangar79** [comment]
There is kind of an edge case for this rule, if using Lombok ```@RequiresArgConsturctor(onConstructor= @__(@Autowired))``` and have properties annotated with ```@Value```...

I de-Lomboked the class and understood that Lombok only takes care for properties which were essentially classes/beans created and managed by Spring or otherwise. 

Because if i want to use constructor injection only for fields, compiler complains on the Lombok annotation and essentially need to create an explicit constructor for the class.

Understand that it comes to what the developer is comfortable with.. what you have to say?

**Comment by hankem** [comment]
I don't know much about Lombok, but did I understand correctly that you were able to fix this "issue" after you _de-Lomboked_ and adapted the class?

But anyways: if your architecture doesn't forbid using `@Value`-injection on fields, just adapt the `ArchRule` to your needs.
