### ISSUE TITLE
isEnum method for JavaClass

### ISSUE THREAD

**Issue by storozhukBM** [TNG/ArchUnit#5]
Hi @codecholeric,

Thank you for this great library. It is awesome and saves me a lot of time.
Recently I've faced a case where i wanted to check that `JavaClass` is `enum`.
Currently I can solve this by: `javaClass.reflect().isEnum()`, but it would be more convenient to have such check in `JavaClass`.

If you don't mind I'll create corresponding PR.

**Comment by codecholeric** [comment]
Hey,

glad it helps you :-) I actually thought about this myself in the past, the reason it's not in, is simply, that I wanted to wait, if this is really relevant in daily life. Which you just proved it is ;-)
I think this should be part of `JavaClass`, so performance is better, and it's decoupled from the classpath.

A PR would be highly appreciated of course :-) In case it helps to get started, I think this would involve

- Adding a test to `ClassFileImporterTest`
- In `JavaClassProcessor` check the `access` parameter for `org.objectweb.asm.Opcodes.ACC_ENUM` (similar to `Opcodes.ACC_INTERFACE`, which is already checked)

I wonder, if it would make sense, to support `List<JavaEnumConstant> getEnumConstants()` as well (or `List<String> getEnumConstants()`?)...
What do you think?

**Comment by storozhukBM** [comment]
I've some simple changes in PR #6 
As for `getEnumConstants()` I'm also not sure about it, currently I don't have such use case.

**Comment by codecholeric** [comment]
Thanks a lot, I've merged your PR :-) If you want to try the current 0.5.0-SNAPSHOT version with your changes, you can include the Sonatype snapshot repo

```
<repository>
    <id>sonatype-snapshots</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
</repository>
```
(note that there is a breaking change where `@AnalyzeClasses(importOption = ...)` became `@AnalyzeClasses(importOptions = ...)`)

As for `getEnumConstants()`, guess I'll handle that like `isEnum()` and wait, if anybody ever really needs this feature.

Anyway, thanks for contributing, I'll close this issue.

**Comment by storozhukBM** [comment]
Thank you to, @codecholeric.
