### ISSUE TITLE
areAnnotatedWith seems to fail for Repeatable class annotations

### ISSUE THREAD

**Issue by rbri** [TNG/ArchUnit#507]
I like to make sure some method annotations are only used in annotated classes.

    public static final ArchRule jsxGetterAnnotationJsxClass = methods()
            .that().areAnnotatedWith(JsxGetter.class)
                    .or().areAnnotatedWith(JsxSetter.class)
                    .or().areAnnotatedWith(JsxFunction.class)
            .should().beDeclaredInClassesThat().areAnnotatedWith(JsxClass.class);

This works fine in most cases but i have some classes having multiple JsxClass annotations e.g.

    @JsxClass({CHROME, EDGE, FF, FF78})
    @JsxClass(className = "WorkerGlobalScope", value = IE)
    public class DedicatedWorkerGlobalScope extends ....

The above check fails for these classes.

JsxClass is defined as

    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.TYPE)
    @Repeatable(JsxClasses.class)
    public @interface JsxClass {
        ....
    }

ArchUnit 0.15.0 / junit 4

**Comment by codecholeric** [comment]
If I'm not mistaken, this is a duplicate of #419?

**Comment by rbri** [comment]
Yes you are right - i was blind. Sorry and many thanks for the great tool.

**Comment by codecholeric** [comment]
No problem, glad you like it :smiley:
