### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by gopf** [TNG/ArchUnit#509]
I tried to check out the source and build it (on a Macbook), but it fails with the following error:

Execution failed for task ':archunit:compileJdk9mainJava'.
> Could not target platform: 'Java SE 9' using tool chain: 'JDK 8 (1.8)'.

The build.gradle for compileJdk9mainJava specifies a compatibility version of 1.9, so I don't know why gradle isn't using the right JDK here (I don't normally use gradle).

I also get errors in IntelliJ:

```
error: reference to assertThat is ambiguous
            assertThat(actual).as("ThrowsClause").hasSize(classes.length);
            ^
  both method <ELEMENT>assertThat(Iterable<? extends ELEMENT>) in org.assertj.core.api.Assertions and method assertThat(ThrowsClause<?>) in com.tngtech.archunit.testutil.Assertions match
  where ELEMENT is a type-variable:
    ELEMENT extends Object declared in method <ELEMENT>assertThat(Iterable<? extends ELEMENT>)
```

**Comment by codecholeric** [comment]
It sounds like you have JDK 8 configured to run Gradle. What does `./gradlew --version` tell you? At least I understand the exception that Gradle tries to build the project with JDK 8 but needs JDK >= 9.
You could try to run 

```
JAVA_HOME=/path/to/jdkGreater9 ./gradlew build
```

or set the Gradle JDK via 

```
> gradle.properties (e.g. in ~/.gradle/gradle.properties)
--------
org.gradle.java.home=/path/to/jdkGreater9
```

**Comment by codecholeric** [comment]
BTW. in IntelliJ you should configure

```
File | Settings | Build, Execution, Deployment | Build Tools | Gradle > build and run using: Gradle
```

Because AFAIK IntelliJ does not understand the ArchUnit build itself...

**Comment by hankem** [comment]
Due to a `javadoc` bug in Java 9/10 (cf. #305), you might even need JDK 11, see also [CONTRIBUTING.MD](https://github.com/TNG/ArchUnit/blob/master/CONTRIBUTING.md).

**Comment by gopf** [comment]
Aha, thanks a lot. Building with Gradle was the default, but when checking that I found the setting for the Gradle JVM. I thought it would use the project JVM, but obviously not.

Using Adopt JDK 11 I can now build.

Should I make a PR to add this information to the project?

**Comment by codecholeric** [comment]
Where would you add this information? As @hankem pointed out the requirements for JDK 11 are already documented here https://github.com/TNG/ArchUnit/blob/master/CONTRIBUTING.md#how-to-build-the-project
The other issue was more, that IntelliJ in your environment did something unexpected (i.e. not use the project JVM for Gradle, which in fact I also stumbled over at some point in the past :roll_eyes:). But I'm not sure where/if to document such things, because it's not really connected to ArchUnit and more to "how to build Java 11 projects with Gradle in your specific dev environment".

**Comment by gopf** [comment]
I think you're right. This is probably OK as it is. I'll close the issue.
