### ISSUE TITLE
Covariant return types cause non-deterministic JavaCalls

### ISSUE THREAD

**Issue by iTitus** [TNG/ArchUnit#513]
We have this:
```java
public interface SuperInterface {
    Object foo();
}
public interface ChildInterface extends SuperInterface {
    @Override
    String foo();
}
```
And:
```java
public class SuperClass {
    public Object bar() {
        return null;
    }
}
public class ChildClass extends SuperClass {
    @Override
    public String bar() {
        return "bar";
    }
}
```
As you can see we change the return type in the overriding method from `Object` to `String`, which is valid.

Now we try to add an ArchRule that disallows calls to methods in the same class (that do not have a special annotation, but that is not relevant to the issue):
```java
    @ArchTest
    static final ArchRule methodsAndConstructorsCalledFromSameClassMustBeClassOnly = codeUnits()
            .should(onlyCallSameClassTargetsWithClassOnly());

    private static ArchCondition<JavaCodeUnit> onlyCallSameClassTargetsWithClassOnly() {
        return new ArchCondition<>("only call targets in the same class that are annotated with @ClassOnly") {

            @Override
            public void check(JavaCodeUnit item, ConditionEvents events) {
                for (JavaCall<?> call : item.getCallsFromSelf()) {
                    if (call.getOriginOwner().equals(call.getTargetOwner())) {
                        if (call.getTarget().isAnnotatedWith(ClassOnly.class)) {
                            events.add(satisfied(call, call.getDescription()));
                        } else {
                            System.out.println("origin: " + item.getFullName() + " " + item.getDescriptor()
                                    + " modifier=" + item.getModifiers());

                            Set<? extends JavaCodeUnit> targets = call.getTarget().resolve();
                            if (targets.size() != 1) {
                                throw new RuntimeException();
                            }

                            JavaCodeUnit target = targets.iterator().next();
                            System.out.println("target: " + target.getFullName() + " " + target.getDescriptor()
                                    + " modifier=" + target.getModifiers());
                            events.add(violated(call, call.getDescription()));
                        }
                    }
                }
            }
        };
    }
```

When running this with the IntelliJ Test Runner and JUnit we get this output:
```
origin: covidtracer.ChildInterface.foo() ()Ljava/lang/String; modifier=[PUBLIC, ABSTRACT]
target: covidtracer.ChildInterface.foo() ()Ljava/lang/String; modifier=[PUBLIC, ABSTRACT]

origin: covidtracer.ChildClass.bar() ()Ljava/lang/Object; modifier=[PUBLIC, BRIDGE, SYNTHETIC]
target: covidtracer.ChildClass.bar() ()Ljava/lang/String; modifier=[PUBLIC]
```

When running this with the IntelliJ Test Runner and JUnit in _Debug_ Mode we get this:
```
origin: covidtracer.ChildInterface.foo() ()Ljava/lang/String; modifier=[PUBLIC, ABSTRACT]
target: covidtracer.ChildInterface.foo() ()Ljava/lang/String; modifier=[PUBLIC, ABSTRACT]

origin: covidtracer.ChildClass.bar() ()Ljava/lang/String; modifier=[PUBLIC]
target: covidtracer.ChildClass.bar() ()Ljava/lang/String; modifier=[PUBLIC]
```

When running this with the Gradle Test Runner (still in IntelliJ) _Debug_ Mode we get this:
```
origin: covidtracer.ChildInterface.foo() ()Ljava/lang/String; modifier=[PUBLIC, ABSTRACT]
target: covidtracer.ChildInterface.foo() ()Ljava/lang/String; modifier=[PUBLIC, ABSTRACT]

origin: covidtracer.ChildClass.bar() ()Ljava/lang/String; modifier=[PUBLIC]
target: covidtracer.ChildClass.bar() ()Ljava/lang/String; modifier=[PUBLIC]
```

When running this externally with `./gradlew test --info` we get this output:
```
origin: covidtracer.ChildInterface.foo() ()Ljava/lang/String; modifier=[PUBLIC, ABSTRACT]
target: covidtracer.ChildInterface.foo() ()Ljava/lang/String; modifier=[PUBLIC, ABSTRACT]

origin: covidtracer.ChildClass.bar() ()Ljava/lang/String; modifier=[PUBLIC]
target: covidtracer.ChildClass.bar() ()Ljava/lang/String; modifier=[PUBLIC]
```

ArchUnit does detect a call from `ChildClass.bar()` to `ChildClass.bar()` and a call from `ChildInterface.foo()` to `ChildInterface.foo()`. 
But it will see different calling methods. Why is that the case? Is this related to #256 ?

As you can see there is no way to reliable detect if this is a "real" method call with all methods of running the tests.

I do not know the internals of `javac` - so it eludes me whether a `synthetic` method is _supposed_ to be there or not.

PS: These outputs changed when I added the second test suite with the class (instead of interfaces)...

**Comment by codecholeric** [comment]
AFAIK the existence of a bridge method here is actually expected. If you look into the bytecode of `ChildClass`, you see

```
 public java.lang.String bar();
    descriptor: ()Ljava/lang/String;
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=1, locals=1, args_size=1
         0: ldc           #3                  // String bar
         2: areturn

  public java.lang.Object bar();
    descriptor: ()Ljava/lang/Object;
    flags: (0x1041) ACC_PUBLIC, ACC_BRIDGE, ACC_SYNTHETIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokevirtual #4                  // Method bar:()Ljava/lang/String;
         4: areturn
```

So you see there is now a synthetic method `Object bar()` that just "bridges" to the covariantly overridden method `String bar()`. 

I would imagine the bridge method logic was added in Java 5 (when covariant return types were added AFAIK) to be backwards compatible. #256 is more related to looking for a method by name and parameters, which is indeterministic when covariantly overwritten return types come to play :thinking: But in your case AFAIS the origin behaves unpredictable? That's definitely something different than described there I think (even though it's probably related to the same cause, multiple methods with the same name and parameters).

One thing I definitely noticed is that the behavior changes with the language level. E.g. with `target < 1.8` you will not have any call `ChildInterface.foo() -> ChildInterface.foo()` ever (which makes sense, because interface default implementations were only added with this version).

Anyway, I think I need to look into it a little more. At least on my machine the modifiers are also different depending on running the test in IntelliJ in debug mode or not :thinking: Please have a little patience, I'll try to get to the bottom of this!

**Comment by iTitus** [comment]
Thanks for looking into it!

**Comment by codecholeric** [comment]
Really sorry that it took me so long :see_no_evil:
