### ISSUE TITLE
Dependency do not support constant 

### ISSUE THREAD

**Issue by GeeJoe** [TNG/ArchUnit#515]
I tried to scan a class's dependency using `JavaClass.directDependenciesToSelf` but I found the constant in the class which is using by another class was not in the dependency list.

What should I do?

**Comment by hankem** [comment]
I believe that the statement from https://github.com/TNG/ArchUnit/issues/298#issuecomment-583745288 is unfortunately still true:
> there is at the moment no workaround with ArchUnit to detect a dependency that is only observable through the constant pool.

Somebody needs to find some time to implement #309.

**Comment by codecholeric** [comment]
I just played around a little and I think it will work to inspect `ldc` instructions with the current ASM version :smiley: I'll see if I can find some time the next days to implement this!

**Comment by GeeJoe** [comment]
> I just played around a little and I think it will work to inspect `ldc` instructions with the current ASM version 😃 I'll see if I can find some time the next days to implement this!

Did you resolve this issue? I find the problem still exits in com.tngtech.archunit:archunit:0.17.0

**Comment by codecholeric** [comment]
Are you sure? Can you show me an example? AFAIS something like this should now be detected, right?

```
class One {
    private Class<?> causesDependency = Two.class;
}

class Two {
}
```

What is your concrete case?

**Comment by GeeJoe** [comment]
Like
```java 
class One {
    public static final String TAG = "Hello";
}

class Two {
     private String tag = One.TAG;
}
```
If I try to get `getDirectDependenciesFromSlef()` on class Two，the result won't contain class One

**Comment by hankem** [comment]
There is some confusion: Since [ArchUnit 0.16.0](https://github.com/TNG/ArchUnit/releases/tag/v0.16.0), `JavaClass`/`JavaCodeUnit` know their references to other _class objects_ (like `Two.class` in the example above), but _primitive constants_ (like your `String TAG`) have a different signature in the bytecode (see also #298).

<details><summary>The bytecode for your example</summary>

```
class Two
  minor version: 0
  major version: 55
  flags: (0x0020) ACC_SUPER
  this_class: #5                          // Two
  super_class: #6                         // java/lang/Object
  interfaces: 0, fields: 1, methods: 1, attributes: 1
Constant pool:
   #1 = Methodref          #6.#15         // java/lang/Object."<init>":()V
   #2 = Class              #16            // One
   #3 = String             #17            // Hello
   #4 = Fieldref           #5.#18         // Two.tag:Ljava/lang/String;
   #5 = Class              #19            // Two
   #6 = Class              #20            // java/lang/Object
   #7 = Utf8               tag
   #8 = Utf8               Ljava/lang/String;
   #9 = Utf8               <init>
  #10 = Utf8               ()V
  #11 = Utf8               Code
  #12 = Utf8               LineNumberTable
  #13 = Utf8               SourceFile
  #14 = Utf8               OneAndTwo.java
  #15 = NameAndType        #9:#10         // "<init>":()V
  #16 = Utf8               One
  #17 = Utf8               Hello
  #18 = NameAndType        #7:#8          // tag:Ljava/lang/String;
  #19 = Utf8               Two
  #20 = Utf8               java/lang/Object
{
  private java.lang.String tag;
    descriptor: Ljava/lang/String;
    flags: (0x0002) ACC_PRIVATE

  Two();
    descriptor: ()V
    flags: (0x0000)
    Code:
      stack=2, locals=1, args_size=1
         0: aload_0
         1: invokespecial #1                  // Method java/lang/Object."<init>":()V
         4: aload_0
         5: ldc           #3                  // String Hello
         7: putfield      #4                  // Field tag:Ljava/lang/String;
        10: return
}
```

</details>

initializes `Two.tag` from the result of a `ldc #3` instruction to load a constant that is actually copied into `Two`'s own pool:
```
   #3 = String             #17            // Hello
  // ...
  #17 = Utf8               Hello
```
That's why the usage of the primitive constant `One.TAG` is currently not recognized as a dependency.

**Comment by GeeJoe** [comment]
Thanks for your detailed explanation! Hope that you can implement this soon. :)
