### ISSUE TITLE
Question: Driven adapters in Onion Architecture

### ISSUE THREAD

**Issue by JCook21** [TNG/ArchUnit#523]
I have a question about Onion Architecture and how it is tested with ArchUnit. My understanding is that the implementation only allows adapters to call application services but not each other, with application services knowing nothing about other adapters. 

This seems completely reasonable to me for driving adapters but I'm struggling to see how this allows for driven adapters. For example, if we wanted to model all calls to a persistence layer through a driven adapter how could this be allowed? If services know nothing about any adapter and adapters can't know about each other, it seems that this would be impossible to model and test. It seems that the only option would be to allow the outermost layer (web controller, etc) to receive a response from the application and to then call the persistence layer through the driving adapter itself, and this doesn't seem right to me. 

Am I missing something in my understanding about onion architecture? Is there something in ArchUnit that allows driving adapters to be created that I've missed? I'd appreciate any thoughts on this.

**Comment by codecholeric** [comment]
As far as I understand you, your concern is for example, how a domain service would be able to persist the changes it made to domain entities, if it can't call the driven adapter for e.g. MySQL?

If that is what you meant, then maybe the reason for your confusion is the distinction of "call" and "dependency". ArchUnit's Onion Architecture is all about dependencies. So for ArchUnit's Onion Architecture you can call a `repository.save(domainObject)` at any point from a domain service. But the point is, that this interface `MyDomainRepository` belongs to the domain service, not to the adapter (i.e. is driven by the domain).

Maybe this diagram can help

![diagram](http://www.plantuml.com/plantuml/svg/VP9DRp8n38Jl-HMMtijRgN3e4I54Fuv5gENOHPMxCMnAOcyJmsfLzRztWHxO3t6TyJpsA9adnQZxu8r9EySbHWoGIoY5YNMbjITetBiX5xuDm8D4I_5Hl4JujurK7pNCTzieUxP_UbKu9VDZJDauk2Mm4j3nUw9uS3cTG01lY_hffA_Eyhgjlb8foQd4UWtJgMEbkC6SPhC6pA84dZOAikd09x2iE46VSfkn6zDum860cXUKCjQ2W8biwdExPRebbX-VbElwilMYNdtvUukbKkoENtgdq63lqMZMsp01BsWJ85j8UA1a1g6jS8iw0HTAJu5OhsIRTF-5ccW2nySxo89ZbMk0mUDtB5M2GYfGWQGIAUFsKCE51lRoRBhxhtKwSuLzdV5_P0i1QyZH-njZviJs-ET_0G00)

The point for me is, that the domain service owns the interface (and only knows the interface), the infrastructure is a secondary thing that gets adjusted to the domain's needs (and that is irrelevant for the domain).

At least that's how I understand it, and how it makes sense to me. About such things you can always fight a lot :joy: 

Does this clarify things for you? Or did I simply misunderstand your concerns?

**Comment by JCook21** [comment]
@codecholeric thanks for this, it makes a lot of sense to me and definitely helps to clear this up in my mind. I really appreciate you taking the time to explain it this way. :)
