### ISSUE TITLE
ArchRules doesn't consider static ArchRule fields

### ISSUE THREAD

**Issue by OLibutzki** [TNG/ArchUnit#525]
As far as I can see `com.tngtech.archunit.junit.ArchRules` scans the given `definitionLocation` for methods and fields which are annotated with `com.tngtech.archunit.junit.ArchTest`.

I would like to include a class which defines fields of type `com.tngtech.archunit.lang.ArchRule` like `com.tngtech.archunit.library.GeneralCodingRules`. 

```
@AnalyzeClasses
public class CodingRuleTest {

	@ArchTest
	static ArchRules generalRules = ArchRules.in(GeneralCodingRules.class);
	
}
```

**Comment by hankem** [comment]
Could you elaborate what is not considered in your opinion?

Including rules via `ArchRules.in` should actually work, cf. [`RuleSetsTest`](https://github.com/TNG/ArchUnit-Examples/blob/master/example-junit5/src/test/java/com/tngtech/archunit/exampletest/junit5/RuleSetsTest.java) and [`RuleLibraryTest`](https://github.com/TNG/ArchUnit-Examples/blob/master/example-junit5/src/test/java/com/tngtech/archunit/exampletest/junit5/RuleLibraryTest.java) of the [ArchUnit-Examples](https://github.com/TNG/ArchUnit-Examples).

**Comment by OLibutzki** [comment]
The fields/methods of the class referenced by `ArchRules.in` have to be annotated with `@ArchTest`.

In my opinion it should be sufficient to scan the fields/methods pretty much the arch-unit-maven-plugin does.

The `@AnalyzeClasses` annotation is provided by the test class which includes the other test classes... Therefore there is no need to use archunit-junit API in the classes you include by using `ArchRules.in`.

**Comment by hankem** [comment]
Ah, I see: [`GeneralCodingRules`](https://github.com/TNG/ArchUnit/blob/v0.16.0/archunit/src/main/java/com/tngtech/archunit/library/GeneralCodingRules.java) does not have `@ArchTest` annotations, but you'd still want to include its `ArchRule`s.

Thanks for the clarification! 💙

**Comment by codecholeric** [comment]
Hmm, I'm not completely sure how this would go :thinking: Because `ArchRules.in(..)` is also a little specific to `@ArchTest`. For example, it will also evaluate methods like

```
@ArchTest
static void my_rule(JavaClasses classes) {
    // evaluate something on classes
}
```

And some things in a class like `GeneralCodingRules` could also be a "rule factory", i.e. a method that returns you a rule :thinking: 
In other words, I had considered `GeneralCodingRules` very generic so far, and `ArchRules.in(..)` very specific to JUnit support. Because if you take all `@ArchTest` in another class, it's very easy to explain. It's the same behavior as slapping `@AnalyzeClasses`directly on the imported class.

That said, it's certainly possible technically, to simply pull in all static fields as well (but then `@ArchTest` also works for non-static fields to support e.g. Kotlin in a nicer way :wink: ). But it would also be a breaking change, e.g. take something like

```
class MyRules {
  private static final ArchRule firstPartialRule = classes()...
  private static final ArchRule secondPartialRule = classes()...

  @ArchTest
  static final ArchRule myComposite = CompositeArchRule.of(firstPartialRule).and(secondPartialRule);
}
```

Now `ArchRules.in(MyRules.class)` would suddenly execute three rules, instead of one. Sure, could take the visibility into account, but that's still a slippery slope :man_shrugging: 
Alternatively we could supply an `@ArchTest` version of the `GeneralCodingRules` within the JUnit support, but then that would have to be maintained in the future :thinking:

**Comment by OLibutzki** [comment]
Just to make it clear: I do not want to use the _GeneralCodingRules_  which are shipped by the ArchUnit library. I target for my own ruleset.

> Because `ArchRules.in(..)` is also a little specific to `@ArchTest`. For example, it will also evaluate methods like
> 
> ```
> @ArchTest
> static void my_rule(JavaClasses classes) {
>     // evaluate something on classes
> }
> ```

Yes, pretty much like the _arch-unit-maven-plugin_ does.

My motivation for raising this issue was my confusion that `@ArchRules` expects the fields/methods to be annotated with `@ArchTest`. `@ArchRules` does not have a Javadoc and from the naming I derived that it is a `ArchRule` and not a `ArchTest` collection.

So improving/adding Javadoc would have solved my confusion quickly. Instead I had to explore the source code to get to know why my static `ArchRule` fields have not been processed.

**Comment by codecholeric** [comment]
Ah, okay! Yeah, absolutely fair point about the Javadoc, I added it to the [user guide](https://www.archunit.org/userguide/html/000_Index.html#_grouping_rules), but forgot to also write some Javadoc :disappointed: You're right, that it is not self-explanatory :wink: I'll add some Javadoc!

**Comment by codecholeric** [comment]
Also, `ArchRules.in(..)` could actually throw an exception if there are no valid `@ArchTests` in the supplied type and explain the problem :thinking:

**Comment by OLibutzki** [comment]
> Also, `ArchRules.in(..)` could actually throw an exception if there are no valid `@ArchTests` in the supplied type and explain the problem 🤔

That's a breaking change, too. Image you reference a class which contains one `@ArchTest`. After the `@ArchTest` is deleted the referenced test class is still executable without executing any test, but the test class which references fails as there are no valid arch tests. IMO that behaviour is inconsistent.



> I added it to the [user guide](https://www.archunit.org/userguide/html/000_Index.html#_grouping_rules),

To be honest the docs could be more precise, too.

> The runner will evaluate all rules within ServiceRules and PersistenceRules against the classes declared at ArchitectureTest. This also allows an easy reuse of a rule library in different projects or modules.

There is a code example with `@ArchTest` in place, but rephrasing the sentence to clarify that ArchRules does not evaluate all rules but all `@ArchTest`s  would clarify the behaviour.

Javadoc and an improved user guide helps for sure, but most importantly is the class naming. `ArchRules` led me into the wrong direction. `ArchTests` as the pluar of `@ArchTest` is the perfect choice.

Sure, this is a (hard) breaking change, too, and I understand that you want to prevent that for good reasons... Mayb it's an option to introduce `ArchTests` and deprecate `ArchRules`?

**Comment by codecholeric** [comment]
Yeah, that's true, I think it was pretty clear to me when I coded this down what the wording meant :wink: 
But I can see how it is confusing looking at it from the outside, I'll try to improve it! Thanks for your suggestions how to do that :+1: :smiley:
