### ISSUE TITLE
Feature Request: Classes that contain annotated methods

### ISSUE THREAD

**Issue by nils-christian** [TNG/ArchUnit#545]
Hello,

First of all I would like to thank you for providing us with ArchUnit. It is a very helpful tool during our development.

Now about my feature request. We have some use cases where we want to find classes that contain methods annotated with a specific annotation. Currently it seems like this is not possible. Assume we want to find classes that contain at least one method annotated with _EventHandler_ and want to make sure that those classes are annotated with _ProcessingGroup_. This would lead to following code:

    public static final ArchRule EVENT_HANDLERS_SHOULD_BE_EXPLICITLY_ASSIGNED_TO_A_PROCESSING_GROUP = classes( )
		.that( containEventHandlers( ) )
		.should( ).beAnnotatedWith( ProcessingGroup.class )
		.because( "Event handlers should be explicitly assigned to a processing group." );

    private static DescribedPredicate<JavaClass> containEventHandlers( ) {
	  return new DescribedPredicate<>( "contain event handlers" ) {

		@Override
		public boolean apply( final JavaClass input ) {
			return input.getAllMethods( ).stream( ).anyMatch( m -> m.isAnnotatedWith( EventHandler.class ) );
		}
	};

    }

I would like to use something like the following

    public static final ArchRule EVENT_HANDLERS_SHOULD_BE_EXPLICITLY_ASSIGNED_TO_A_PROCESSING_GROUP = classes( )
		.that( ).containMethodsAnnotatedWith( EventHandler.class )
		.should( ).beAnnotatedWith( ProcessingGroup.class )
		.because( "Event handlers should be explicitly assigned to a processing group." );

**Comment by hankem** [comment]
Thanks for your feedback! Do I understand correctly that your statement
> it seems like this is not possible

refers to the fluent API only? (Because your predicate-based solution seems to be functional to me. 😉)

**Comment by nils-christian** [comment]
Hi,

You are correct of course. It works like a charm, but I would prefer if we could express the rule with your fluent API.

**Comment by codecholeric** [comment]
Thanks for the input :smiley: I'm always trying to balance what should go in the core API and what should just patched in by users via `Predicates` the way you did it.
I feel the `containMethodsAnnotatedWith(..)` extension would still be fair, since it's generic enough to bring benefit to various users :+1: 
Just that I personally don't think I'll find the time to do this in the near future. If you should want to provide this as a PR I'd be more than happy to merge it :wink: Otherwise to manage expectations, my own work pipe is super full for the next time, so it would need a while.

**Comment by nils-christian** [comment]
Hi,

Seems fair 😃

I took a look at your code and added the feature request in a fork. I will add a pull request once the current main branch is stable again.

**Comment by hankem** [comment]
Thanks a lot!

> once the current main branch is stable again

There was _some kind of network issue(?)_ for one of the build jobs. I've rerun the build and now it's passing as it should. ✅

One thought on the naming: I wonder whether `classes().that().containMethodsAnnotatedWith(…)` leaves room for the misinterpretation that this means `containOnlyMethods…`, whereas `getAllMethods( ).stream( ).anyMatch(…)` actually has the semantics of `containsAtLeastOneMethod`? Maybe the name is good enough when the JavaDoc will just be clear about it.

**Comment by nils-christian** [comment]
Hi,

I added a pull request: https://github.com/TNG/ArchUnit/pull/547

I chose the method name "containMethodsThatAreAnnotatedWith" for the API and "containMethodsThatAre" for the internal predicate. Feel free to reject the pull request if you do not agree with the names or if I missed something else (which is very likely ;)). Your tests are very thorough by the way.

**Comment by nils-christian** [comment]
As discussed in the old PR, I added a new one with the squashed commits: https://github.com/TNG/ArchUnit/pull/553

**Comment by codecholeric** [comment]
Already resolved with #553 :slightly_smiling_face:
