### ISSUE TITLE
In ArchCondition the methods violated() and satisfied() for SimpleConditionEvent seem to be the inverse of what is expected

### ISSUE THREAD

**Issue by robert-bor** [TNG/ArchUnit#550]
**Problem**

On using ArchCondition and dealing with a violation, adding an event with ```SimpleConditionEvent.violated()``` adds a non-violating error, undesiredly letting the test pass. When the event is added with ```SimpleConditionEvent.satisfied()``` it adds a violating error resulting in the desired test fail. 

**Assumption**

It seems that violated() and satisfied() fulfill each other's conditions, ie violated() leading to a non-violating event and satisfied() leading to a violating event.

**Code used in the setup**

```java
    ArchCondition<JavaMethod> notHaveAParameterCalledInitiativeIdOfTypeLong =
            new ArchCondition<>("not have a parameter called initiativeId of type Long") {
        @Override
        public void check(JavaMethod item, ConditionEvents events) {
            InitiativeIdVerifier initiativeIdVerifier = new InitiativeIdVerifier(item);
            if (!initiativeIdVerifier.hasInitiativeId()) {
                events.add(SimpleConditionEvent.satisfied(
                        item, item.getFullName() + " does not have a parameter with name initiativeId, but does have: " + initiativeIdVerifier.getParameterNames()));
                return;
            }
            if (!initiativeIdVerifier.isOfTypeLong()) {
                events.add(SimpleConditionEvent.satisfied(
                        item, "in " + item.getFullName() + " parameter with name initiativeId is not of type Long, but of type " + initiativeIdVerifier.getType()));
            }
        }
    };
```

```java
    @Test
    public void serviceMethodsThatHaveAccessForOwnerOfInitiativeMustHaveAnInitiativeIdOfTypeLong() {
        noMethods().that()
                .areDeclaredInClassesThat().areAnnotatedWith(Service.class)
                .and().arePublic()
                .and().areAnnotatedWith(AccessForOwnerOfInitiative.class)
                .should(notHaveAParameterCalledInitiativeIdOfTypeLong)
                .check(importedClasses);
    }
```

**Workaround**

The current workaround is to make use of the knowledge of the inversion, which gives the desired result. However, when this is found to be a bug and it is fixed, it will break the workaround.

**Comment by robert-bor** [comment]
Problem solved: I used noMethods(), but should have used methods() instead.

**Comment by hankem** [comment]
Right: `SimpleConditionEvent.violated` (or in general any `ConditionEvent` reporting `isViolated() == true`) indicates that _the condition_ is not satisfied. It depends on the specific `ArchRule` whether this causes _the architecture rule_ to fail or not.

Additional remark: I'd usually recommend to avoid negations when defining concepts. So in your case, it might be easier to define an `ArchCondition<JavaMethod> haveAParameterCalledInitiativeIdOfTypeLong` and use [`ArchConditions.`_`not`_](https://javadoc.io/doc/com.tngtech.archunit/archunit/latest/com/tngtech/archunit/lang/conditions/ArchConditions.html#not(com.tngtech.archunit.lang.ArchCondition)):
`.should(`[_`not`_](https://javadoc.io/doc/com.tngtech.archunit/archunit/latest/com/tngtech/archunit/lang/conditions/ArchConditions.html#not(com.tngtech.archunit.lang.ArchCondition))`(haveAParameterCalledInitiativeIdOfTypeLong)`﻿`)`

**Comment by robert-bor** [comment]
What a great tip! I followed your advice and the puzzle pieces snapped together. My compliments with your library, it is truly a gem of craftmanship.
