### ISSUE TITLE
TestMethodExecution isn't passing method annotations

### ISSUE THREAD

**Issue by michaelbenoit** [TNG/ArchUnit#552]
Dear all,

ArchUnit isn't passing original Annotations of test methods to the corresponding _org.junit.runner.Description_. This becomes a concrete issue if the ArchUnit runner is used in combination with e.g. Allure. Allure related method annotations like **Feature** or **Story** are completely ignored.
 
**Fix**
The issue can easily be fixed within _com.tngtech.archunit.junit.ArchTestMethodExecution.describeSelf_ by passing the method annotations to the creation of the description:

`return Description.createTestDescription(this.testClass, this.testMethod.getName(), this.testMethod.getAnnotations());`

**Comment by codecholeric** [comment]
Sorry that it took me a little. You're right, annotations of test members are not passed to the description right now, I wasn't aware that there were frameworks that relied on this!
I tried to create a little PR to fix this, which will resolve the issue on merge. Feel free to reopen if there are still problems!
