### ISSUE TITLE
Reference to constant in class is not recognized

### ISSUE THREAD

**Issue by zhoujia1974** [TNG/ArchUnit#554]
Hi,

We are using archunit-junit5:0.17.0. In our test, we have a rule as below.

```    
    noClasses()
        .that()
        .resideInAPackage("com.example.package1..")
        .should()
        .dependOnClassesThat()
        .resideInAnyPackage("com.example.package2..")
        .check(classes);
```
In package1, we have a controller reference to a constant defined in a constant class in package2. See below.
```
package com.example.package1.controller;

import com.example.package2.MessageConstant;

public class SomeController {
  ...
  private Message addHeader(final Message message) throws JMSException {
    message.setStringProperty(MessageConstant.REQUEST_ID_PROPERTY, requestContext.getRequestId());
    ...
    return message;
  }
}
```

In package2, we define the constant class.
```
package com.example.package2;
public final class MessageConstant {
  public static final String REQUEST_ID_PROPERTY = "request_id";
 
  private MessageConstant() {}
}
```

The rule doesn't fail. Is it a bug or did I misunderstand how the dependOnClassesThat() should work? When I debug the rule, I found dependOnClassesThat condition evaluation doesn't return MessageConstant class as a target.

Thanks,

**Comment by hankem** [comment]
A String constant is actually no runtime (but only a compile-time) dependency; its value is copied into the constant pool of the using class, cf. https://github.com/TNG/ArchUnit/issues/298#issuecomment-577038056. This is why ArchUnit currently doesn't detect it as a dependency.

**Comment by zhoujia1974** [comment]
Thanks @hankem.
