### ISSUE TITLE
Alternatives of sharing ArchUnit tests between repositories?

### ISSUE THREAD

**Issue by junhuhdev** [TNG/ArchUnit#557]
Hi, foremost thanks for building this great library. 

My question is what alternatives are there to share common ArchUnit tests between repositories? 

I've seen the approach where maven plugin is used https://github.com/societe-generale/arch-unit-maven-plugin

Is that the best approach? Is there a way to share the tests and trigger them programmatically?

**Comment by OLibutzki** [comment]
You might take a look at `@ArchTests` as it provides the capabilty of comoosing your ArchUnit tests, see https://www.archunit.org/userguide/html/000_Index.html#_grouping_rules

You can develop your ArchUnit tests in a library and reference them by including a dependency to that library.

Nevertheless, the maven plugin is a valid alternative for sure.

**Comment by codecholeric** [comment]
Yes, my main approach so far in bigger projects was exactly what's described in the user guide link from @OLibutzki, i.e. to have some common library and then include its rule groups via 

```
@ArchTest
static final commonRules = ArchTests.in(CommonRules.class);
```

in all relevant submodules.

But in the end `ArchRules` are just Java code, so any distribution you would use for normal Java libaries works fine. Add a dependency on your rule library Jar / Maven project / ... and include the rules, extend some base class, whatever you would do to distribute common unit tests between multiple projects :man_shrugging:
If your projects are Maven based, then the Maven plugin might be an easy way to distribute rules and include them in every build.

To me it's a little bit depending on, if you want to treat arch rules more like tests, that each project also has some custom ones, and you want to debug them sometimes, etc., then maybe it's more convenient to include them as classical tests. If you want to consider them more as part of the build and projects just want to run a couple of central rules as quality gate, then maybe it's more consistent / concise to simply add the Maven plugin.

**Comment by junhuhdev** [comment]
Thanks for the great answers. Just dumb question so I guess in this case CommonRules.class should exist under src/main/java/.. instead of /src/test/java/... ?

**Comment by OLibutzki** [comment]
Yes, if you want to ship the rules as a library you have to include ArchUnit as a compile dependency and put your rules under src/main/java.

**Comment by junhuhdev** [comment]
Great thank you for all the help!

**Comment by codecholeric** [comment]
I guess your questions are solved :wink: If not, feel free to reopen the issue!
