### ISSUE TITLE
Ignoring external/3rd-party dependencies

### ISSUE THREAD

**Issue by ScottG489** [TNG/ArchUnit#558]
Is there a way to ignore external/3rd-party dependencies?

I'm attempting what I would think would be a common use case, so I imagine I'm doing something wrong. I'm trying to verify my core library only depends on itself (within the project), particularly that it doesn't depend on the higher level packages which are meant to implement it.

The problem I'm encountering is that violations are being reported because the package depends on  classes external to my project, some of which I quite literally wouldn't ever be able to avoid (e.g. `java.lang.Object`)

This is an example of what I have so far as a workaround:
```java
        JavaClasses importedClasses = new ClassFileImporter().importPackages("myapp..");

        classes()
                .that().resideInAPackage("myapp.core..")
                .should().onlyDependOnClassesThat().resideInAnyPackage(
                "myapp.core..",
                "com..",
                "org..",
                "net..",
                "java..",
                "lombok..")
                .check(importedClasses);
```

I've manually included common package prefixes, but this is clearly a hack.

**In the documentation I came across the import options to not include "jars" or "archives" and tried these options but it didn't seem to have an effect. From the documentation it does seem like this is what I want though.**

For example the following reports violations:

```java
        JavaClasses importedClasses = new ClassFileImporter()
                .withImportOption(ImportOption.Predefined.DO_NOT_INCLUDE_JARS)
                .withImportOption(ImportOption.Predefined.DO_NOT_INCLUDE_ARCHIVES)
                .importPackages("myapp..");
                
        classes()
                .that().resideInAPackage("myapp.core..")
                .should().onlyDependOnClassesThat().resideInAnyPackage("myapp.core..")
                .check(importedClasses);
```

Perhaps there is something different about my project setup? I'm using a fairly standard **gradle** project. If that's the case, how would I go about troubleshooting what the issue is?

Thanks and I love the concept for this project!

**Comment by hankem** [comment]
These `ImportOption`s configure which classes are analyzed in first place.
The dependencies of classes that are imported do not depend on `ImportOption`s.

If you only want to test dependencies within `myapp`, you can probably express that with corresponding predicates:
<details><summary>imports</summary>

```java
import static com.tngtech.archunit.base.DescribedPredicate.doNot;
import static com.tngtech.archunit.core.domain.JavaClass.Predicates.resideInAPackage;
```

</details>

```java
.should().onlyDependOnClassesThat( resideInAPackage("myapp.core..").or(doNot(resideInAPackage("myapp.."))) )
```

**Comment by ScottG489** [comment]
Thanks @hankem! This seems like what I was looking for.
