### ISSUE TITLE
Add support to test caught exceptions

### ISSUE THREAD

**Issue by cpollet** [TNG/ArchUnit#591]
I would like to be able to assert that some method calls are wrapped in a try/catch block catching certain type of exceptions.

Typical use case would be to make sure that runtime `WebApplicationExceptions` are caught when calling a remote resource using JAX-RS.

I'd be happy to try to contribute with a PR, if it could eventually be merged.

**Comment by hankem** [comment]
ArchUnit currently does not recognize
<details><summary>the bytecode signature of <code>try</code>/<code>catch</code> blocks,</summary>

For a simple example
```java
    try {
        RemoteService.method();
    } catch (WebApplicationException e) {
        e.printStackTrace();
    }
```
the byte code looks like this (see also [JVM Spec §3.12](https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-3.html#jvms-3.12)):
```
   0: invokestatic  #2      // Method RemoteService.method:()V
   3: goto          11
   6: astore_1
   7: aload_1
   8: invokevirtual #4      // Method javax/ws/rs/WebApplicationException.printStackTrace:()V
  11: return
Exception table:
   from    to  target type
       0     3     6   Class javax/ws/rs/WebApplicationException
```

<details><summary>Try-with-resources statements are even more complex.</summary>

For example,

```java
    try (RemoteService remoteService = new RemoteService()) {
        remoteService.method();
    } catch (WebApplicationException e) {
        e.printStackTrace();
    }
```

compiles to the following byte code:

```
   0: new           #2      // class RemoteService
   3: dup
   4: invokespecial #3      // Method RemoteService."<init>":()V
   7: astore_1
   8: aload_1
   9: invokevirtual #4      // Method RemoteService.method:()V
  12: aload_1
  13: invokevirtual #5      // Method RemoteService.close:()V
  16: goto          35
  19: astore_2
  20: aload_1
  21: invokevirtual #5      // Method RemoteService.close:()V
  24: goto          33
  27: astore_3
  28: aload_2
  29: aload_3
  30: invokevirtual #7      // Method java/lang/Throwable.addSuppressed:(Ljava/lang/Throwable;)V
  33: aload_2
  34: athrow
  35: goto          43
  38: astore_1
  39: aload_1
  40: invokevirtual #9      // Method javax/ws/rs/WebApplicationException.printStackTrace:()V
  43: return
Exception table:
   from    to  target type
       8    12    19   Class java/lang/Throwable
      20    24    27   Class java/lang/Throwable
       0    35    38   Class javax/ws/rs/WebApplicationException
```

</details>

</details>

but ASM offers [MethodVisitor.html.visitTryCatchBlock](https://asm.ow2.io/javadoc/org/objectweb/asm/MethodVisitor.html#visitTryCatchBlock(org.objectweb.asm.Label,org.objectweb.asm.Label,org.objectweb.asm.Label,java.lang.String)), which could be implemented in [ArchUnit's `MethodProcessor`](https://github.com/TNG/ArchUnit/blob/v0.18.0/archunit/src/main/java/com/tngtech/archunit/core/importer/JavaClassProcessor.java#L307-L375).

How would you want to make the information available in ArchUnit's domain objects?
Should [`JavaCall`](https://javadoc.io/doc/com.tngtech.archunit/archunit/0.18.0/com/tngtech/archunit/core/domain/JavaCall.html) have something like `List<JavaClass> getCaughtExceptions()`?

**Comment by codecholeric** [comment]
This might be a nice addition, but I would propose a type `CaughtException` or sth. like that (similar to `InstanceOfCheck`) that can offer you type and source code location (and possibly more info in the future).

**Comment by crizzis** [comment]
[PR](https://github.com/TNG/ArchUnit/pull/813/files) attached. 

(Sorry if sth is not quite done the 'ArchUnit way', but this is my first PR here)
