### ISSUE TITLE
How to get the parameter of a method call

### ISSUE THREAD

**Issue by GeeJoe** [TNG/ArchUnit#596]
```kotlin
class A {
  fun testA() {
    B().testB("hello")
  }
}

class B {
  fun testB(param: String) {
    
  }
}
```

I can get the method `testB(param: String)` by 
```kotlin
val method = importedClass.get(B::class.java).getMethod("testB", String::class.java)
```
then I called
```kotlin
method.callsOfSelf
```
to get the JavaMethodCall happens on class A，and I can get the param's type by `methodCall.target.rawParameterTypes`, but how can I get the real param value "hello"?

**Comment by hankem** [comment]
You unfortunately can't: ArchUnit currently does not analzye method call parameter values.

**Comment by GeeJoe** [comment]
ok,thank you

**Comment by davidgiga1993** [comment]
I'm having a similar use case where I need to verify that no `null` value is passed as a parameter. I would be fine to only anaylze directly passed constants in my case. How would you get the instructions by line of the origin?

**Comment by codecholeric** [comment]
I'm sorry, my last comment might be a little misleading. While it is theoretically possible to load constant values like `String` from the bytecode, ArchUnit at the moment only does it for `Class` constants. So loaded class constants (including the line number) you can access by `JavaClass.getReferencedClassObjects()`, but all other types of constants are currently not read from the bytecode.
