### ISSUE TITLE
The API should support testing for "equivalence" to classes

### ISSUE THREAD

**Issue by codecholeric** [TNG/ArchUnit#60]
Sometimes a rule only targets a single class (e.g. class `Foo` is only accessed by classes matching a certain pattern). It should be possible to supply the class object in that case, instead of writing `classes().that().haveFullyQualifiedName(Foo.class.getName())`. Thus I propose an API extension:

* `classes().that().areEquivalentTo(Foo.class)`
* `classes().should().beEquivalentTo(Foo.class)`

which just pipes to `JavaClass.isEquivalentTo(Foo.class)`.

**Comment by alex0ptr** [comment]
I like the idea, but I feel the proposal looks kind of verbose and could be more precise.
Maybe `the(Foo.class)` would be more readable. However `theClass(Foo.class)` or `singleClass(Foo.class)` would be closer to `classes()`.

I would prefer
`the(Foo.class).should()...`
over
`classes().that().areEquivalentTo(Foo.class).should()...`

**Comment by codecholeric** [comment]
You're right, that would be more concise :smiley:
Guess the should part could then also be `should().be(Foo.class)`? Sounds a little strange maybe, since the rule clearly talks about a single class, so why do I have to start with `classes()`...
I think I like `theClass(Foo.class)` the best, since as you mentioned, it's closer to `classes()`, so it might be easier to find, if you just browse methods. (my favorite one would be `class(Foo.class)` if that was possible :wink: )
Hmm, maybe an empty one would make sense for the point above
```
theClass().that().isAnnotatedWith(Bar.class).should().be(Foo.class)
```
Or `theOnlyClass()`? Either way it could automatically ensure, that the that clause really only leaves one class.
