### ISSUE TITLE
Ignore Patterns on message is too greedy

### ISSUE THREAD

**Issue by DennisRippinger** [TNG/ArchUnit#62]
I learned about the `archunit_ignore_patterns` before the new documentation and treated the Regex as a way to ignore classes within the package. Today I learned that it is applied on the whole violation message. This is too much in my case, because the signature of a violating method uses a class from an ignored package.

Could there be a way to improve the `FailureReport` class and the global ignore file to allow more specific ignoring rules?

**Comment by codecholeric** [comment]
I know the `ignore_patterns.txt` is pretty crude, e.g. often it would be better to be able to customize this per rule. However, I have no clear vision yet, what would be necessary, and in which form it could be provided. Maybe I need to collect some more use cases.
In your case though, couldn't you solve your concrete problem by specifying more of the message? For example sth. like
```
class .*(IgnoredClassOne|IgnoredClassTwo) (calls|accesses) .*
```
to ignore all violations originating from certain classes you want to ignore?
I think a more structured format might be good, to specify origins or targets, but some rules also don't have these concepts (like class has wrong name).
That is why so far I haven't added a more sophisticated way to ignore violations.

In my project we often ignore this programmatically, like
```
@Test
public void foo() {
    ArchRule rule = ignoreKnownViolations(classes().that())...should()...
}

private GivenClassesThat ignoreKnownViolations(GivenClassesThat classesThat) {
    for (String fqn : classesToIgnore) {
        classesThat = classesThat.dontHaveFullyQualifiedName(fqn).and();
    }
    return classesThat;
}
```
Of course in these cases you probably need to overwrite the generated rule text :wink:

**Comment by codecholeric** [comment]
Was this sufficient for your use case, or do you have any suggestion, how the ignore patterns should be improved?

**Comment by codecholeric** [comment]
If there's no suggestion, how the ignore patterns could be improved, I'll close this issue for now, until something more concrete will come up.

**Comment by codecholeric** [comment]
I agree with your points, there is definitely room for improvement here. However, as you say, it's more than this issue was originally about, so I've opened a new one: #66 
Do you find your points correctly reflected there?
If yes, I'd close this issue and move discussion / implementation over to the new one.

**Comment by DennisRippinger** [comment]
Thanks for the follow up. I close the Issue.
