### ISSUE TITLE
onionArchitecture loses ignored dependencies when overriding description

### ISSUE THREAD

**Issue by thmuch** [TNG/ArchUnit#622]
When adding a because() or as() to an onionArchitecture() rule, all specified ignored dependencies are lost – which causes the architecture check to fail:

```java
    ArchRule rule = onionArchitecture()
            .domainModels("...")
            .adapter("... a name...", "....")
            .ignoreDependency(MySource.class, MyTarget.class)
            .because("docs/adr/001-hex-arch.md");
```

PR with test case and fix will follow shortly.

**Comment by hankem** [comment]
Oops, thanks for catching that!
