### ISSUE TITLE
Replace Optional class with java.util.Optional

### ISSUE THREAD

**Issue by mustaphazorgati** [TNG/ArchUnit#644]
Hey there!

I've was a little confused because you have a custom implementation of the `java.util.Optional` class. 
Because I've expected `java.util.Optional` instead of your custom implementation I was wondering why all the methods I know don't work.

Is there a specific reason for that? Can we replace your custom implementation with `java.util.Optional`?

**Comment by hankem** [comment]
ArchUnit is currently meant to be compatible with Java 7 – which didn't have `java.util.Optional` yet. 🤷‍♂️

But future versions will drop the Java 7 support and use the built in `Optional`, see also #634.

**Comment by mustaphazorgati** [comment]
Thank you for the quick response! :)
