### ISSUE TITLE
Junit-5 @ArchTests are not executed with maven surefire groups

### ISSUE THREAD

**Issue by SebastianDietrich** [TNG/ArchUnit#645]
I have some Junit-5 architecture-tests (i.e. annotated with @AnalyzeClasses but without @RunWith) based on @ArchTest static final ArchRule
They run fine using e.g. eclipse.
But when running them via maven, they are not executed since maven-surefire-plugin obviously only runs @Test annotated methodes.
archunit-0.20.1

**Comment by hankem** [comment]
Which version of the `maven-surefire-plugin` are you using?
I think you [need](https://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven) version ≥ 2.22 (or some extra plugin dependencies) to run Junit 5 tests with Maven.

In fact, the example from https://github.com/TNG/ArchUnit-Examples/tree/main/example-junit5 works for me with the following

<details><summary><code>pom.xml</code></summary>

```xml
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>ArchUnit-Examples</groupId>
  <artifactId>example-junit5</artifactId>
  <version>0.20.1</version>
  <properties>
    <maven.compiler.target>1.8</maven.compiler.target>
    <maven.compiler.source>1.8</maven.compiler.source>
  </properties>
  <dependencies>
    <dependency>
      <groupId>javax.annotation</groupId>
      <artifactId>javax.annotation-api</artifactId>
      <version>1.3.2</version>
    </dependency>
    <dependency>
      <groupId>org.apache.geronimo.specs</groupId>
      <artifactId>geronimo-ejb_3.1_spec</artifactId>
      <version>1.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.geronimo.specs</groupId>
      <artifactId>geronimo-jpa_2.0_spec</artifactId>
      <version>1.0</version>
    </dependency>
    <dependency>
      <groupId>joda-time</groupId>
      <artifactId>joda-time</artifactId>
      <version>2.0</version>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-beans</artifactId>
      <version>5.2.2.RELEASE</version>
    </dependency>
    <dependency>
      <groupId>com.google.inject</groupId>
      <artifactId>guice</artifactId>
      <version>4.2.3</version>
    </dependency>
    <dependency>
      <groupId>com.tngtech.archunit</groupId>
      <artifactId>archunit-junit5</artifactId>
      <version>0.20.1</version>
    </dependency>
  </dependencies>
  <build> <!-- without this block, I get: Tests run: 0, Failures: 0, Errors: 0, Skipped: 0 -->
    <plugins>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.22.2</version>
      </plugin>
    </plugins>
  </build>
</project>
```

</details>

– but only when I explicitly configure the `maven-surefire-plugin`, even with [the lastest release](https://maven.apache.org/download.cgi) Maven 3.8.1.

**Comment by SebastianDietrich** [comment]
My surefire and failsafe are on 2.22.2 (via spring-boot-starter-parent 2.5.3). 
To make JUnit5 tests run with maven I had to add surefire and failsafe as plugins to the build in pom.xml.

The problem was that I included the types of tests using
```	
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-surefire-plugin</artifactId>
	<!-- configure the build to test only tests annotated with @Tag("UnitTest"), @Tag("IntegrationTest"), or @Tag("FunctionalTest") -->
	<configuration>
		<groups>UnitTest,IntegrationTest,ArchitectureTest</groups>
	</configuration>
</plugin>
```
and added @Tag("ArchitectureTest") to the test classes.
This led to the problem, that the archunit tests were not executed although archunit was "started" (logged "ArchConfiguration - No configuration found...")

So the solution / workaround was to remove the configuration, now also the archunit tests are executed.

--> Please make sure that @ArchTests annotated ArchRules are run when surefire plugin is configured to use groups.

**Comment by codecholeric** [comment]
Sorry, but `@Tag` is JUnit Jupiter API, while ArchUnit has no dependency on JUnit Jupiter (but only JUnit Platform). In short that means that ArchUnit has its own `@ArchTag` annotations that work in the same way together with the `ArchUnitTestEngine`. Can you try if that works in your setup? If you use `@ArchTag` instead of `@Tag` for your ArchUnit tests?

**Comment by SebastianDietrich** [comment]
Thanks, that worked indeed.

**Comment by SebastianDietrich** [comment]
.

**Comment by codecholeric** [comment]
Glad to hear it :smiley:
