### ISSUE TITLE
Feature proposal: Provide "extended" package matching support

### ISSUE THREAD

**Issue by Pfoerd** [TNG/ArchUnit#662]
### Story
As an ArchUnit test developer, I would like to be able to use an extended syntax for package identifiers, since the existing one based on PackageMatcher is very limited. At least, I would like to be able to define alternatives such as `(a|b)`. This allows to support architectures that for some reasons need a namespace for some components by using different packages even though they logically belong to the same architectural entity like a layer, domain, etc. This is especially useful if your code needs to satisfy some "overarching" structural requirements that come from outside your actual project, e.g. from an enterprise architecture.

### Sample Use Case
You have a structure `org.my.app.subdomain1` and `org.my.app.subdomain2` and want to logically place them in the same top-level domain `domain1` in your ArchUnit tests, but for certain reasons you are not allowed to introduce another package level.

### Known Alternatives:
Most ArchUnit APIs we use offer an alternative to the "straightforward" variant of just providing a `packageIdentifier` String e.g. by using custom `Predicate`s oder `SliceAssignment`s. But this makes the tests very verbose, complex and hard to understand.

### API proposals:
* Extend the existing PackageMatcher in a backward compatible way
* Alternatively a new "PackgeMatcherExt" (name WIP 😉) could be introduced, together with corresponding SliceAssignements and Predicates. The advantage of sending something like this upstream is that it could share the basic matching algorithms for the existing syntax with the existing PackageMatcher. This is currently not possible due to its current design (final monolithic class without interfaces). In addition, special API extensions could be introduced for using the "extended" package identifier syntax, e.g. something like `layer("domain").definedByExtendedPkgId("org.my.app.(subdomain1|2)..")` (name WIP 😉).

### Further ideas
Further "nice-to-haves" that could be achieved by such a solutions are non-capturing group alternatives like `(?:a|b)` and a "not" operator like `(!a|b).(?:!a)`

If you're interested, let me know, because we have an existing solution and would be happy to share the relevant parts with you and send it upstream.

P.S.: I really appreciate your work on ArchUnit, it's a really cool tool 😃!

**Comment by Pfoerd** [comment]
I really like your approaches. I wonder if there is a way we can bring them all together, because I think all approaches have their pros and cons:
* add minor syntax extensions to support, for example, simple alternatives like `en.foo.(a|b)` and perhaps `en.(foo.a|bar)`. Since support for the latter can be considered a compatible extension to the former, it could be added incrementally
* Add API support to provide a full regex-based PackageMatcher. For this case, I would also prefer an explicit solution by adding a corresponding foo(packageMatcher : PackageMatcher) function to all APIs that get a string-based package identifier today.

**Comment by codecholeric** [comment]
Sounds good! Would you want to create a PR for those minor extensions to start with? I would really only support the or-case via pipe then inside of brackets. Probably supporting dots inside of these alternatives does not add much complexity :slightly_smiling_face:

**Comment by Pfoerd** [comment]
Okay i will provide a PR for the minor extensions! Just to make sure that I'm on the right track: after some prototyping I ended up just adding some replacements in the `convertToRegex` method:

```
private String convertToRegex(String packageIdentifier) {
    return packageIdentifier.
            replaceAll("(\\([\\w*]*)(?:\\|)([\\w*]*\\))", "$1%OR%$2"). // replacing all '(a|b)' with '(a%OR%b)'
            replaceAll("([\\w*]*)(?:\\|)([\\w*]*)", "(?:$1|$2)"). // replacing all 'a|b' with '(?:a|b)'
            replace("%OR%", "|"). // replacing all '(a%OR%b)' with '(a|b)'
            replace(TWO_STAR_CAPTURE_LITERAL, TWO_STAR_REGEX_MARKER).
            replace("*", "\\w+").
            replace(".", "\\.").
            replace(TWO_STAR_REGEX_MARKER, TWO_STAR_CAPTURE_REGEX).
            replace("\\.\\.", TWO_DOTS_REGEX);
}
```

Some basic tests confirm that this should do the job. Do you think a refactored variant of this should match the requirements?

**Comment by codecholeric** [comment]
What we should definitely do is double check if we would solve https://github.com/TNG/ArchUnit/issues/685#issuecomment-936309667 with this :thinking: 
I guess in this case it would then be `(?:..application.(*).*..)|(?:..domain.api|logic.(*)..)`? Because if you want to demand one subpackage of `application` you can't pull it together, no? What I'm wondering then is, will users really understand this? Except for 0.01% power users that dream of regex at night? :thinking: Or am I missing something?
Of course it could also be that we should just support both, multiple patterns in the Slices API and the extended syntax :man_shrugging: Then this wouldn't need to easily solve #685

**Comment by Pfoerd** [comment]
You are right, i think if it should ensure subpackages for application and infrastructure but not for domain the expression is getting very complex in any case. 

That's why i suggested to support both: minor syntax extensions for **simple** alternatives (like my issue here) and API support to provide a full regex-based PackageMatcher (this could be used for the usecase of #685 ).

**Comment by Pfoerd** [comment]
@codecholeric maybe you can check the commit I just pushed, it adds the syntax support for simple alternatives:
* `pack.[a.c|b*].d` matches `pack.a.c.d` or `pack.bar.d`, but neither `pack.a.d` nor `pack.b.c.d`
* `..service.(a|b*)..` matches `a.service.bar.more` and group 1 would be `bar`
* Nested alternatives like `(?:..application.(*).*..)|(?:..domain.api|logic.(*)..)` are not allowed

This should be sufficient for the use cases mentioned in this issue. If you like it I can create a pull request.

**Comment by Pfoerd** [comment]
@codecholeric, do you have time for some feedback on the suggested solution? Thanks!
