### ISSUE TITLE
INTELLIJ_TEST_PATTERN doesn't work with multi module projects

### ISSUE THREAD

**Issue by JCook21** [TNG/ArchUnit#696]
Firstly, thanks for creating this library. It's an awesome and very useful tool. 

I've come across a small issue when trying to exclude test classes when importing classes. It seems that the IntelliJ test pattern in `ImportOption.java` doesn't work with multi-module projects. In the project I work in I had to use `.*/out/test/.*` to exclude test classes properly. Would be possible to look into this and possibly expand the pattern to support multi module projects?

**Comment by codecholeric** [comment]
Hmm, but usually all classes are compiled into `.*/out/test/classes/.*`, no? So far that pattern seems to have worked okay :thinking: Can you provide an example to what path your classes are compiled to that is not matched by this pattern, but by `.*/out/test/.*`?

**Comment by JCook21** [comment]
I'm not sure if this is project specific but what I'm seeing in the multi module project I'm working in is that classes are being written to a path consisting of the module name, with a sub path consisting of the package name. E.g. if the module was called 'foo' and the package was 'com.foo.bar' I'd see this path: `out/test/foo/com/foo/bar/class_name.class`. This may be highly specific to the project I work in but I wonder if `.*/out/test/classes/.*` may be a little too generic.

**Comment by codecholeric** [comment]
Okay, I played around a little bit and I can reproduce it with a plain IntelliJ project without any build tool :thinking: Then it seems to create a subfolder with the method name... I guess we could just adjust the pattern to `.*/out/test/.*` then as you did, since in the end everything inside of `.*/out/test/.*` can be considered test scope :man_shrugging:
