### ISSUE TITLE
How to use ArchUnit library in product code?

### ISSUE THREAD

**Issue by gprsphone** [TNG/ArchUnit#712]
Hi,

Since the Archunit library can be used to parser java class or Jar package, so I plan to use Archunit lib to create a tool. use the tool to check Jar packages or class files.

But when I import Archunit in product code, VS code shows "com.tngtech cannot be resolved to a type". but if I use Archunit lib in the test code, everything is OK 

Is there any specific method to use archunit lib in product code?

Thanks!
Philip

**Comment by hankem** [comment]
This shouldn't be a problem. The following minimal example works for me:
<details><summary><code>build.gradle</code></summary>

```groovy
apply plugin: 'java'

repositories {
  mavenCentral()
}

dependencies {
  implementation 'com.tngtech.archunit:archunit:0.22.0'
}
```
</details>

<details><summary><code>src/main/java/Issue712.java</code></summary>

```java
import com.tngtech.archunit.core.domain.JavaClass;
import com.tngtech.archunit.core.domain.JavaMethod;
import com.tngtech.archunit.core.importer.ClassFileImporter;

class Issue712 {
    public static void main(String[] args) {
        JavaClass javaClass = new ClassFileImporter().importClass(Issue712.class);
        for (JavaMethod method : javaClass.getMethods()) {
            System.out.println(method.getFullName());
        }
    }
}
```
</details>

Did you maybe include the archunit dependency only in test scope?

**Comment by gprsphone** [comment]
Many thanks!

I use Maven embedded in VS code, It takes me some time to find the place to remove the test scope limitation from pom.xml.

Now it works.
