### ISSUE TITLE
adhereToPlantUmlDiagram swallows unparseable diagrams

### ISSUE THREAD

**Issue by pfichtner** [TNG/ArchUnit#735]
Some days ago I defined an ArchUnit rule that uses a plantUML via adhereToPlantUmlDiagram. 
I asked myself whether ArchUnit also accepts the generated PNG, so I changed passing the diagram.puml to passing the diagram.png and everything seems to work fine. 
Later I wondered why a violation was not detected by that ArchUnit rule. I played around and realized that if the file does not contain valid plantUML source it is ignored silently. 
That's bad because if the file does not contain valid content (e.g. you pass files of the wrong type or the file became corrupted) the test should fail, not pass.

**Comment by pfichtner** [comment]
Is there any valid use case where it makes sense to load diagrams without any components? If yes, the issue should be approached alternatively,

**Comment by codecholeric** [comment]
Thanks a lot for also immediately providing a fix :smiley: I fully agree, a diagram with no components doesn't make sense to be used in a test but is much more likely hiding some error :+1:
