### ISSUE TITLE
archunit has a stackoverflowError, when scan a class which has been proguard

### ISSUE THREAD

**Issue by junsignal** [TNG/ArchUnit#754]
archunit has a stackoverflowError, when scan a class which has been proguard.  the origin class is "androidx.core.util.Pools"
[log.zip](https://github.com/TNG/ArchUnit/files/7792733/log.zip)

**Comment by junsignal** [comment]
sorry, the origin class maybe is "androidx.constraintlayout.solver.Pools" or "androidx.core.util.Pools"

**Comment by hankem** [comment]
Disassembling your class with `javap -p g.class` shows:
```java
public class b.f.a.g<T> implements b.f.a.g<T> {
  public final java.lang.Object[] a;
  public int b;
  public b.f.a.g(int);
  public T a();
  public void a(T[], int);
  public boolean a(T);
}
```
I'm therefore not surprised that `com.tngtech.archunit.core.domain.JavaClass.getAllRawInterfaces` recurses into itself...

**Comment by hankem** [comment]
But anyways, changing this code
```java
            for (JavaClass i : interfaces.getRaw()) {
                result.add(i);
                result.addAll(i.getAllRawInterfaces());
            }
```
in `JavaClass`'s `Supplier<Set<JavaClass>> allRawInterfaces` to
```java
            for (JavaClass i : interfaces.getRaw()) {
                if (!result.build().contains(i)) {
                    result.add(i);
                    result.addAll(i.getAllRawInterfaces());
                }
            }
```
would prevent `StackOverflowError` in this case.

**Comment by junsignal** [comment]
thank you for answer, I will try it and reply

**Comment by hankem** [comment]
Sorry, @junsignal; I realize that my previous comment was misleading: that code would have to be changed in ArchUnit. I didn't understand yet how/why ProGuard produces a `class g implements g`, but as it doesn't hurt to be more defensive, we should probably just change it. 🤔

**Comment by codecholeric** [comment]
Hmm, I'm not super sure about it. The bytecode up there looks utterly illegal? A class "implementing" itself seems wrong on so many levels :thinking: For once implementing/extending oneself is already illegal, the JLS has e.g.

```
It is a compile-time error if an interface depends on itself.

If circularly declared interfaces are detected at run time, as interfaces are loaded, then a ClassCircularityError is thrown (§12.2.1).
```

Secondly if it's a class it can't "implement" itself, because it's a class. It should "extend" itself, no?

So yes, we could be more defensive by adding guards to catch something that is clearly illegal by the JLS. But it also makes the code more complicated and less efficient. So what if the next bytecode processor decides to hack in some other illegal code? Are we gonna cover each such case? I'm not convinced of this :thinking: 

I would rather prefer one of these ways:

* run tests against unobfuscated classes (i.e. run the Arch tests before Proguard has been run on the classes). That makes more sense from the point of getting reasonable error messages anyway (otherwise it will report some obfuscated class `a.b.c.d` violating some rule)
* if you want to run it on the obfuscated code, then just don't call `getAllInterfaces()`, but write your own method for that which does the same but has the additional guard. You can simply copy the code from `getAllInterfaces()` and add additional guards :man_shrugging:

**Comment by hankem** [comment]
> don't call `getAllRawInterfaces()`

The bad news is that with ArchUnit 0.22.0, this already happens while importing the class:
```
𝄆
	at com.tngtech.archunit.core.domain.JavaClass.getAllRawInterfaces(JavaClass.java:735)
	at com.tngtech.archunit.core.domain.JavaClass$2.get(JavaClass.java:109)
	at com.tngtech.archunit.core.domain.JavaClass$2.get(JavaClass.java:103)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
𝄇
	at com.tngtech.archunit.core.domain.JavaClass.getAllRawInterfaces(JavaClass.java:735)
	at com.tngtech.archunit.core.domain.JavaClassMembers$2.get(JavaClassMembers.java:73)
	at com.tngtech.archunit.core.domain.JavaClassMembers$2.get(JavaClassMembers.java:69)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
	at com.tngtech.archunit.core.domain.JavaClassMembers.getAllFields(JavaClassMembers.java:114)
	at com.tngtech.archunit.core.domain.JavaClass.getAllFields(JavaClass.java:838)
	at com.tngtech.archunit.core.importer.AccessRecord$Factory$RawFieldAccessRecordProcessed.getTarget(AccessRecord.java:233)
	at com.tngtech.archunit.core.importer.AccessRecord$Factory$RawFieldAccessRecordProcessed.getTarget(AccessRecord.java:208)
	at com.tngtech.archunit.core.importer.ClassGraphCreator.accessBuilderFrom(ClassGraphCreator.java:240)
	at com.tngtech.archunit.core.importer.ClassGraphCreator.createFieldAccessesFor(ClassGraphCreator.java:211)
	at com.tngtech.archunit.core.domain.JavaCodeUnit.completeAccessesFrom(JavaCodeUnit.java:241)
	at com.tngtech.archunit.core.domain.JavaClassMembers.completeAccessesFrom(JavaClassMembers.java:275)
	at com.tngtech.archunit.core.domain.JavaClass.completeFrom(JavaClass.java:1377)
	at com.tngtech.archunit.core.domain.JavaClasses.of(JavaClasses.java:200)
	at com.tngtech.archunit.core.domain.DomainObjectCreationContext.createJavaClasses(DomainObjectCreationContext.java:62)
	at com.tngtech.archunit.core.importer.ClassGraphCreator.complete(ClassGraphCreator.java:118)
	at com.tngtech.archunit.core.importer.ClassFileProcessor.process(ClassFileProcessor.java:63)
	at com.tngtech.archunit.core.importer.ClassFileImporter.importLocations(ClassFileImporter.java:336)
```

But the good news is that commit a11085a28a2656a93dd59545f260182d48a703f2 already fixes the issue; with the next release, `b.f.a.g` will no longer be a raw interface of `b.f.a.g<T>`, and there won't be a `StackOverflowError` during class file import or even explicit call to `getAllRawInterfaces()`. 🎉

So PR #760 is in fact not even needed.

**Comment by junsignal** [comment]
Thanks you

> > don't call `getAllRawInterfaces()`
> 
> The bad news is that with ArchUnit 0.22.0, this already happens while importing the class:
> 
> ```
> 𝄆
> 	at com.tngtech.archunit.core.domain.JavaClass.getAllRawInterfaces(JavaClass.java:735)
> 	at com.tngtech.archunit.core.domain.JavaClass$2.get(JavaClass.java:109)
> 	at com.tngtech.archunit.core.domain.JavaClass$2.get(JavaClass.java:103)
> 	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
> 𝄇
> 	at com.tngtech.archunit.core.domain.JavaClass.getAllRawInterfaces(JavaClass.java:735)
> 	at com.tngtech.archunit.core.domain.JavaClassMembers$2.get(JavaClassMembers.java:73)
> 	at com.tngtech.archunit.core.domain.JavaClassMembers$2.get(JavaClassMembers.java:69)
> 	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
> 	at com.tngtech.archunit.core.domain.JavaClassMembers.getAllFields(JavaClassMembers.java:114)
> 	at com.tngtech.archunit.core.domain.JavaClass.getAllFields(JavaClass.java:838)
> 	at com.tngtech.archunit.core.importer.AccessRecord$Factory$RawFieldAccessRecordProcessed.getTarget(AccessRecord.java:233)
> 	at com.tngtech.archunit.core.importer.AccessRecord$Factory$RawFieldAccessRecordProcessed.getTarget(AccessRecord.java:208)
> 	at com.tngtech.archunit.core.importer.ClassGraphCreator.accessBuilderFrom(ClassGraphCreator.java:240)
> 	at com.tngtech.archunit.core.importer.ClassGraphCreator.createFieldAccessesFor(ClassGraphCreator.java:211)
> 	at com.tngtech.archunit.core.domain.JavaCodeUnit.completeAccessesFrom(JavaCodeUnit.java:241)
> 	at com.tngtech.archunit.core.domain.JavaClassMembers.completeAccessesFrom(JavaClassMembers.java:275)
> 	at com.tngtech.archunit.core.domain.JavaClass.completeFrom(JavaClass.java:1377)
> 	at com.tngtech.archunit.core.domain.JavaClasses.of(JavaClasses.java:200)
> 	at com.tngtech.archunit.core.domain.DomainObjectCreationContext.createJavaClasses(DomainObjectCreationContext.java:62)
> 	at com.tngtech.archunit.core.importer.ClassGraphCreator.complete(ClassGraphCreator.java:118)
> 	at com.tngtech.archunit.core.importer.ClassFileProcessor.process(ClassFileProcessor.java:63)
> 	at com.tngtech.archunit.core.importer.ClassFileImporter.importLocations(ClassFileImporter.java:336)
> ```
> 
> But the good news is that commit [a11085a](https://github.com/TNG/ArchUnit/commit/a11085a28a2656a93dd59545f260182d48a703f2) already fixes the issue; with the next release, `b.f.a.g` will no longer be a raw interface of `b.f.a.g<T>`, and there won't be a `StackOverflowError` during class file import or even explicit call to `getAllRawInterfaces()`. 🎉
> 
> So PR #760 is in fact not even needed.

Thank you! the problem has resolved.
