### ISSUE TITLE
Fields in test cases should not fail assertions

### ISSUE THREAD

**Issue by dsyer** [TNG/ArchUnit#762]
I think a test case ought to be able to have a private field of type `@AggregateRoot` without causing an assertion failure. I did this:

```java
@AnalyzeClasses(packagesOf = Owner.class)
class ArchVerificationTests {

  @ArchTest
  void verifyModel(JavaClasses classes) {
    JMoleculesDddRules.all().check(classes);
  }
}
```

and got a nasty surprise:

```
Field o.s.s.p.o.OwnerControllerTests.george refers to an aggregate root (o.s.s.p.o.Owner). Rather use an identifier reference or Association!
```

**Comment by hankem** [comment]
I'm confused: Is this an issue for ArchUnit, or for [jmolecules-integrations](https://github.com/xmolecules/jmolecules-integrations)?

**Comment by dsyer** [comment]
I have no idea. If this is the wrong repo, I would not have known (it looked like archunit was throwing the assertions). If you think it is fixed with Ollie's change, please close.

**Comment by hankem** [comment]
As ArchUnit knows nothing about `@AggregateRoot` nor `JMoleculesDddRules`, some more context might be helpful here. 🤷‍♂️

@odrotbohm, as your issue xmolecules/jmolecules-integrations#91 referencing this one was already solved with xmolecules/jmolecules-integrations@2a7f1c2c0c27971ad46f49e4de4f6e9f9acd7e39: can you maybe comment on whether something is left to be done on ArchUnit's side?

**Comment by odrotbohm** [comment]
I don't think we have anything left here. Was able to fix this on our end. Thanks!

**Comment by hankem** [comment]
All right, thanks! Then we can close this issue.
