### ISSUE TITLE
Text pattern check 

### ISSUE THREAD

**Issue by shail2810** [TNG/ArchUnit#763]
Is there a way to restrict a certain text pattern in entire project?

Use case: Restrict any other date formatter string except 'MM/dd/yyyy' in entire project.

**Comment by hankem** [comment]
ArchUnit analyzes dependencies between classes, but no string constants used as method parameters.

If you encapsulate date formatting in your project in a class, say `MyDateFormatter`, you could however formulate an `ArchRule` that no classes other than `MyDateFormatter` may use a generic date formatter.

**Comment by codecholeric** [comment]
Gonna close this for now, since I don't know what else we can add here. I would also go with the solution proposed by @hankem as it is IMHO cleaner anyway to encapsulate this invariant in a custom `Formatter` and to ensure only that one is used.
