### ISSUE TITLE
Improve handling of JUnit support with regard to Kotlin

### ISSUE THREAD

**Issue by codecholeric** [TNG/ArchUnit#77]
When Kotlin is used together with the JUnit support, writing rules becomes too bloated, since it's necessary to create a companion object due to the static requirements for fields.
I.e. at the moment ArchUnit JUnit tests in Kotlin have to be written like

```
@RunWith(ArchUnitRunner::class)
@AnalyzeClasses(packages = ["com.mycompany.myapp"])
class MyArchitectureTest {

    companion object {
        @ArchTest @JvmField val myRule = classes()
            .that().resideInAPackage("..service..")
            .should().onlyBeAccessed().byAnyPackage("..controller..", "..service..")
    }
}
```

This seems unnecessary bloated, what we would want, is

```
@RunWith(ArchUnitRunner::class)
@AnalyzeClasses(packages = ["com.mycompany.myapp"])
class MyArchitectureTest {

     @ArchTest val myRule = classes()
            .that().resideInAPackage("..service..")
            .should().onlyBeAccessed().byAnyPackage("..controller..", "..service..")

}
```

**Comment by maheshksd** [comment]
I am working on this

**Comment by codecholeric** [comment]
Thanks :smiley: Let me know if you need any further support!!

**Comment by codecholeric** [comment]
I've noticed, that another problem is, that non-Java source files create wrong links, e.g. `MyClass.kt` will be reported as 

```
violation in (MyClass.java:20)
```

or similar, which is obviously wrong. The info seems commonly recorded in Java/Kotlin class files, so I'll fix this on this issue as well.

**Comment by codecholeric** [comment]
Also what is your status on this issue @maheshksd? Because this weekend I'll probably merge the JUnit 5 feature branch back into master, which will mean, that this issue needs to be tackled in two places.
(I'm happy to provide some hints though or work together with you if you want)
