### ISSUE TITLE
[How to] Get all members of classes which have a specific type

### ISSUE THREAD

**Issue by omuomugin** [TNG/ArchUnit#777]
Hey thanks for the great tool and my team heavily relying on this right now.

I'm trying to check all the members which type is `java.time.LocalTime` have some sorts of annotations.

Right now I'm doing like below
```
val allClassesInController = ClassFileImporter()
    .withImportOption(ImportOption.Predefined.DO_NOT_INCLUDE_TESTS)
    .importPackages("some.package")

val rule: ArchRule = ArchRuleDefinition.
      .that().areDeclaredInClassesThat().areAssignableFrom(LocalTime::class.java)
      .should().beAnnotatedWith(Schema::class.java)
      .andShould().beAnnotatedWith(JsonFormat::class.java)
      .because("some reason here")

rule.check(allClassesInController)
```

But not detecting. I guess I misunderstanding some thing here.
```
data class Some(
   val time: LocalDateTime? // not annotated !!
)
```

Anyway again this is saving my life so please just keep up the great work.

**Comment by hankem** [comment]
I'm not super familiar with Kotlin, but I assume that your `rule` definition should start with `ArchRuleDefinition.`_**`fields()`**_, right?

With `fields().that().areDeclaredInClassesThat().areAssignableFrom(LocalTime.class)`, you'd bascially only select fields in the class `LocalTime` (which is `final`, so there can't be subclasses – at least not in Java).

Did you maybe want to use `fields().that().haveRawType(LocalTime.class)` instead?

Also note that your example has a field of type `LocalDateTime`, which is not in an inheritance hierarchy with `LocalTime`.
The example
```kt
import java.time.LocalTime

data class Some(
   val time: LocalTime?
)
```
would actually be caught by the following rule (sorry, I stick to Java):
```java
ArchRule rule = ArchRuleDefinition.fields()
    .that().haveRawType(LocalDateTime.class)
    .should().beAnnotatedWith(Schema.class)
    .andShould().beAnnotatedWith(JsonFormat.class);
```

**Comment by omuomugin** [comment]
@hankem 
Thanks for quick reply.

> haveRawType(LocalDateTime.class)

This was the one I was looking for and it works perfect.

By the way what is the difference between `fields` and `members` ?

**Comment by hankem** [comment]
The [ArchUnit User Guide](https://www.archunit.org/userguide/html/000_Index.html#_domain) documents the domain model:
The [members](https://javadoc.io/doc/com.tngtech.archunit/archunit/latest/com/tngtech/archunit/core/domain/JavaMember.html) of a class consist of all of its [fields](https://javadoc.io/doc/com.tngtech.archunit/archunit/latest/com/tngtech/archunit/core/domain/JavaField.html) and [code units](https://javadoc.io/doc/com.tngtech.archunit/archunit/latest/com/tngtech/archunit/core/domain/JavaCodeUnit.html) (i.e. [methods](https://javadoc.io/doc/com.tngtech.archunit/archunit/latest/com/tngtech/archunit/core/domain/JavaMethod.html), [constructors](https://javadoc.io/doc/com.tngtech.archunit/archunit/latest/com/tngtech/archunit/core/domain/JavaConstructor.html) and [static initializers](https://javadoc.io/doc/com.tngtech.archunit/archunit/latest/com/tngtech/archunit/core/domain/JavaStaticInitializer.html)).

**Comment by omuomugin** [comment]
Thanks for the information and your help.
Closing this issue.
