### ISSUE TITLE
[Question]ArchUnit rule to negate package access?

### ISSUE THREAD

**Issue by kkocel** [TNG/ArchUnit#783]
I stumbled upon the following snippet.

```java
ArchRule myRule = classes()
    .that().resideInAPackage("..core..")
    .should().onlyBeAccessed().byAnyPackage("..controller..");
```

I wonder how I can negate this condition so, the test should check if the `core` package is not accessed by the `controller` package?

**Comment by hankem** [comment]
You can use [`ClassesShould.accessClassesThat()`](https://javadoc.io/doc/com.tngtech.archunit/archunit/latest/com/tngtech/archunit/lang/syntax/elements/ClassesShould.html#accessClassesThat()), which (as its JavaDoc suggests) _usually makes more sense the negated way:_
<details><summary>Static import</summary>

```java
import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.noClasses;
```
</details>

```java
  noClasses()
      .that().resideInAPackage("..controller..")
      .should().accessClassesThat().resideInAPackage("..core..");
```

You can also stick to `classes()` and use [`GivenClasses.should(…)`](https://javadoc.io/doc/com.tngtech.archunit/archunit/latest/com/tngtech/archunit/lang/syntax/elements/GivenClasses.html#should(com.tngtech.archunit.lang.ArchCondition)) or [`GivenClassesConjunction.should(…)`](https://javadoc.io/doc/com.tngtech.archunit/archunit/latest/com/tngtech/archunit/lang/syntax/elements/GivenClassesConjunction.html#should(com.tngtech.archunit.lang.ArchCondition)) with a flexible  [`ArchCondition`](https://javadoc.io/doc/com.tngtech.archunit/archunit/latest/com/tngtech/archunit/lang/ArchCondition.html). For your case, it can be easily composed from pre-defined conditions and [predicates](https://javadoc.io/doc/com.tngtech.archunit/archunit/latest/com/tngtech/archunit/base/DescribedPredicate.html):


<details><summary>Static imports</summary>

```java
import static com.tngtech.archunit.core.domain.JavaClass.Predicates.resideInAPackage;
import static com.tngtech.archunit.lang.conditions.ArchConditions.accessClassesThat;
import static com.tngtech.archunit.lang.conditions.ArchConditions.not;
import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.classes;
```
</details>

```java
    classes()
        .that().resideInAPackage("..controller..")
        .should(not(accessClassesThat(resideInAPackage("..core.."))));
```

**Comment by kkocel** [comment]
Thanks a lot!
