### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by zhangchunzhao12** [TNG/ArchUnit#790]
My I ask some compile issue 
1. How to compile module archunit only and produce archunit-0.22.1-SNAPSHOT.jar
   For I use command `./gradlew clean build -P archunit`,  for my opinion it would only compile archunit module, but it will also execute `archunit-junit`, it would not only cause unexpected error but also make every debug longer; 
2. How to execute junit case only, like code below
    ```java
    @Test
    public void should_skip_ignored_rule() {
        ArchTestExecution satisfiedRule = getRule(IGNORED_FIELD_NAME);

        runner.runChild(satisfiedRule, runNotifier);

        verify(runNotifier).fireTestIgnored(descriptionCaptor.capture());
        assertThat(descriptionCaptor.getValue().toString()).contains(IGNORED_FIELD_NAME);
    }
    ```
Thanks very much!

**Comment by codecholeric** [comment]
1) If I understand you, what you want to do is execute only the build of the subproject `archunit`? You should be able to do that with
```
./gradlew :archunit:build
```
The root question is how to build Gradle subprojects in isolation (you can find more info [here](https://docs.gradle.org/current/userguide/intro_multi_project_builds.html#sec:executing_tasks_by_fully_qualified_name))

2) I don't exactly know what environment you're referring to. This looks like a plain JUnit 4 test? You can e.g. execute only that in isolation by running it from your IDE directly? If you want to do it from Gradle you can append something like `--tests com.myapp.SomeTest.test_method_name`. You can find more info about test filtering with Gradle [here](https://docs.gradle.org/current/userguide/java_testing.html#test_filtering).

Does that answer your questions?

**Comment by zhangchunzhao12** [comment]
It's very helpful to me, thanks very much!
