### ISSUE TITLE
Add locations of architecture violations to stack trace

### ISSUE THREAD

**Issue by dstango** [TNG/ArchUnit#791]
I'm exploring ArchUnit for a little while now and am excited with all the things possible! Great!

I was wondering how to make navigation to code that violates some rules easier. Currently I'm using eclipse and in the JUnit-View I can easily double-click on any element of the stack trace of a failed test to directly navigate to the corresponding location in the code. Other IDEs hopefully have similar support.

Yet ... ArchUnit creates an expressive error message, listing the places that violate it, but I have to untangle it all through my brain to get to the location mentioned, which makes it cumbersome, especially when trying to bring some order into a legacy project ;-) ...

Thus I came up with the idea to manipulate the stack trace, and add a StackTraceElement for any place that violates the rule. See the code of my current experiment below, which is just some exploration if that idea could work at all (it does :-)...).

Better than doing regex on the error-message (which is bound to be error-prone) would it be if ArchUnit itself could put the places of architecture violations directly into the stack trace. :-)

As I guess this feature request might trigger some opinions whether this is abuse of the stack trace or not, one or two configuration options might be appropriate for the following results:
* enable stack-trace-manipulation to contain the locations of architecture violations
* hide listing the architecture violation locations in the error message in the first place (thus only listing them in the stack trace)

I guess such an option would be especially useful when using annotation-style to define the rules (which I currently don't).

Here comes the current code of experimentation, which grew directly in an ArchUnit-test-class:
```java
private void check(ArchRule rule) {
    try {
        rule.check(jc);
    } catch (AssertionError e) {
        // Wir fügen dem Stacktrace die von ArchUnit identifizierten Klassen/Methoden hinzu
        // damit diese in der Eclipse-Ansicht direkt mit Doppelklick angesteurt werden können.
        List<StackTraceElement> stackTrace = new ArrayList<>(Arrays.asList(e.getStackTrace()));
        addFailureElementsToStackTrace(e.getMessage(), stackTrace);
        e.setStackTrace(stackTrace.toArray(new StackTraceElement[0]));
        throw e;
    }
}

private void addFailureElementsToStackTrace(String errorMessage, List<StackTraceElement> stackTrace) {
    addDelimiter(stackTrace);
    stackTrace.addAll(0, findFieldErrors(errorMessage));
    stackTrace.addAll(0, findMethodErrors(errorMessage));
    stackTrace.addAll(0, findConstructorErrors(errorMessage));
    stackTrace.addAll(0, findClassErrors(errorMessage));
}

private List<StackTraceElement> findConstructorErrors(String errorMessage) {
    List<StackTraceElement> l = new ArrayList<>();

    Matcher matcher = Pattern.compile("Constructor <([\\w\\s\\.\\(\\)\\<\\>\\,]+)>.* in \\(([\\w\\.]+):(\\d+)\\)")
            .matcher(errorMessage);

    while (matcher.find()) {
        String qualifiedMethodName = StringTools.subStringBefore(matcher.group(1), "(");
        String declaringClass = StringTools.subStringBeforeLast(qualifiedMethodName, ".");
        String methodName = StringTools.subStringAfterLast(qualifiedMethodName, ".");
        String fileName = matcher.group(2);
        int lineNumber = StringTools.parseIntDef(matcher.group(3), 0);

        StackTraceElement method = new StackTraceElement(declaringClass, methodName, fileName, lineNumber);
        l.add(method);
    }
    addDelimiter(l);
    return l;
}

private List<StackTraceElement> findMethodErrors(String errorMessage) {
    List<StackTraceElement> l = new ArrayList<>();

    Matcher matcher = Pattern.compile("Method <([\\w\\s\\.\\(\\)\\,]+)>.* in \\(([\\w\\.]+):(\\d+)\\)").matcher(errorMessage);

    while (matcher.find()) {
        String qualifiedMethodName = StringTools.subStringBefore(matcher.group(1), "(");
        String declaringClass = StringTools.subStringBeforeLast(qualifiedMethodName, ".");
        String methodName = StringTools.subStringAfterLast(qualifiedMethodName, ".");
        String fileName = matcher.group(2);
        int lineNumber = StringTools.parseIntDef(matcher.group(3), 0);

        StackTraceElement method = new StackTraceElement(declaringClass, methodName, fileName, lineNumber);
        l.add(method);
    }
    addDelimiter(l);
    return l;
}

private List<StackTraceElement> findClassErrors(String errorMessage) {
    List<StackTraceElement> l = new ArrayList<>();

    Matcher matcher = Pattern.compile("Class <([\\w\\.\\(\\)]+)>.* in \\(([\\w\\.]+):(\\d+)\\)").matcher(errorMessage);

    while (matcher.find()) {
        String declaringClass = matcher.group(1);
        String methodName = "";
        String fileName = matcher.group(2);
        int lineNumber = StringTools.parseIntDef(matcher.group(3), 0);

        StackTraceElement method = new StackTraceElement(declaringClass, methodName, fileName, lineNumber);
        l.add(method);
    }
    addDelimiter(l);
    return l;
}

private List<StackTraceElement> findFieldErrors(String errorMessage) {
    List<StackTraceElement> l = new ArrayList<>();

    Matcher matcher = Pattern.compile("Field <([\\w\\.\\(\\)]+)>.* in \\(([\\w\\.]+):(\\d+)\\)").matcher(errorMessage);

    while (matcher.find()) {
        String qualifiedFieldName = StringTools.subStringBefore(matcher.group(1), "(");
        String declaringClass = StringTools.subStringBeforeLast(qualifiedFieldName, ".");
        String fieldName = StringTools.subStringAfterLast(qualifiedFieldName, ".");

        String fileName = matcher.group(2);
        int lineNumber = StringTools.parseIntDef(matcher.group(3), 0);

        StackTraceElement method = new StackTraceElement(declaringClass, fieldName, fileName, lineNumber);
        l.add(method);
    }
    addDelimiter(l);
    return l;
}

private void addDelimiter(List<StackTraceElement> l) {
    if (!l.isEmpty()) {
        StackTraceElement delimiter = new StackTraceElement(
                "----------------------------------------------------------------------------------------------------------------------------------------------------------------------------",
                "", "", -1);
        l.add(0, delimiter);
    }
}    
```

**Comment by hankem** [comment]
I agree that being able to navigate conveniently to the source code location of violations of your architecture rules is key to address them efficiently.

I don't want to advertise any product, but just FYI report that [ArchUnit's `SourceCodeLocation.toString()`](https://github.com/TNG/ArchUnit/blob/v0.22.0/archunit/src/main/java/com/tngtech/archunit/core/domain/SourceCodeLocation.java#L118-L126) is recognized by [IntelliJ IDEA](https://www.jetbrains.com/idea/) as a link already, so you don't have to ~abuse~ 😉 _introduce a new concept of_ stacktraces to get that.

For [example](https://github.com/TNG/ArchUnit-Examples/), this is the output of [`com.tngtech.archunit.exampletest.CodingRulesTest.no_classes_should_access_standard_streams_or_throw_generic_exceptions`](https://github.com/TNG/ArchUnit-Examples/blob/91e8f44e28766844316fce7c2d2ba951bd60e588/example-plain/src/test/java/com/tngtech/archunit/exampletest/CodingRulesTest.java#L64-L68):

![Output of Architecture Violation with links to source code locations in IntelliJ IDEA](https://user-images.githubusercontent.com/4208552/153951137-f68bf82f-ad46-403d-868f-3445553ce0ff.png)

Just as the gray underlined stacktrace elements (in their conventional semantics), underlined blue filenames are indeed clickable and navigate to the corresponding source code location.

**Comment by dstango** [comment]
I was suspecting that IntelliJ might have support for it ;-) ... yet that doesn't help in environments where something else is used... 

Thus: As SourceCodeLocation is already there I'm wondering if it would be possible to easily hook into this already existing mechanism, to realize such a dreaded *introduction of a new concept of stacktraces* ;-) at least on a per-project base ...

**Comment by hankem** [comment]
`ArchRule`s' `EvaluationResults` are quite generic (cf. e.g. #749), but in order to infer source code locations, the following might work for many rules:
```java
private void checkSourceCodeLocations(ArchRule rule, JavaClasses javaClasses) {
    EvaluationResult result = rule.evaluate(javaClasses);
    List<SourceCodeLocation> sourceCodeLocations = new ArrayList<>();
    result.handleViolations((violatingObjects, message) ->
            violatingObjects.forEach(violatingObject -> {
                if (violatingObject instanceof HasSourceCodeLocation) {
                    sourceCodeLocations.add(((HasSourceCodeLocation) violatingObject).getSourceCodeLocation());
                }
            }));
    // ...
    assertNoViolation(result);
}
```
```

**Comment by codecholeric** [comment]
To me (ab-)using the stacktrace like this just for one specific platform also feels a little bit too hacky. If there was a unified API or convention that ArchUnit violates which could be fixed I would be all open. But this way I would also prefer if clients would enhance this for their specific platform in this case. Could also be done e.g. by writing some wrapper around `ArchRule` that evaluates the delegate and then creates an `AssertionError` as necessary for the respective platform. That way it would also be possible to e.g. use the JUnit support.
For now I would close this issue, feel free to reopen if you disagree!
