### ISSUE TITLE
Dismatch of linenumber when Field violation

### ISSUE THREAD

**Issue by zhangchunzhao12** [TNG/ArchUnit#797]
I'm exploring ArchUnit for a little while now and am excited with all the things possible! Great!
And I have a small question, like rule pattern as below:
```
Field <com.tngtech.archunit.example.layers.ClassViolatingCodingRules.log> does not have modifier FINAL in (ClassViolatingCodingRules.java:0)
```
I find that if the violation object is Filed,  the line number always zero, is that correct ? 
Is there any way to make the line number correct ?
Thanks very much!

**Comment by hankem** [comment]
Unfortunately, fields don't have a line number information in the bytecode; that's why you usually see `0`.
I think that we add the `:0` because it still helps some IDEs to conveniently navigate to the file, cf. https://github.com/TNG/ArchUnit/issues/791#issuecomment-1039606812.

**Comment by hankem** [comment]
Indeed: For me (using IntellIJ IDEA 2021.2.3), the additional `:0` makes the difference whether I can navigate to the file or not (the underlined blue text is a clickable link):

![text represenation of source code location with and without :0 in IntellIJ IDEA](https://user-images.githubusercontent.com/4208552/154257887-4abfc4d5-43b5-43e2-875b-22c3edecfc56.gif)

**Comment by zhangchunzhao12** [comment]
Thanks for your reply, thanks very much!
