### ISSUE TITLE
How to avoid access to static fields

### ISSUE THREAD

**Issue by S-Man42** [TNG/ArchUnit#799]
Hi,

I have something like:

```
classes()
  .that()
  .resideInPackage("..a..")
  .should()
  .onlyBeAccessed()
  .byClassesThat()
  .resideInPackage("..b..");
```

My class `a.A`:

```
package com.a;

class A {
    public static String A_FIELD = "foo";
}
```

Well, a class `C` in package `c` accesses `A.A_FIELD`. I don't want a class in package `c` accessing package `a`. The test fails if I call the constructor `A()`, but not if I call the static member here. (Btw. what is the difference between member and field in the ArchUnit context?)

So I tried something like:

```
classes()
  .that()
  .resideInPackage("..c..")
  .should()
  .onlyAccessMembersThat(are(not(declaredIn(
     GET_PACKAGE_NAME.is(
       PackageMatchers.of("..a..")
     )
  ))));
```

Well, first I am not quite sure about the `GET_PACKAGE_NAME` thing, I just found it somewhere in a tutorial. I hope, there's an easier way to achieve this.
Second, is this way correct at all? Is there a better way? However, this test does not fail as expected....

Thanks for any hint!

**Comment by hankem** [comment]
For primitive or String constants, the compiler "unfortunately" does not reference the other class, but just inline the value, see #298.

**Comment by codecholeric** [comment]
I'm going to close this issue for now as there has not been any activity for quite a while. Feel free to reopen if you still have problems!
