### ISSUE TITLE
How to location java source position?

### ISSUE THREAD

**Issue by zhangchunzhao12** [TNG/ArchUnit#824]
Hi all:
    I have been using archunit form months and find it very helpful in my project ;
    But I recently I have a feature that need to location the java source position,  so could tell where is the file violating rules ;
    First I consider using JavaClass.getSource Method, like
    Optional<Source> source = arg0.getSource();
    Log.i(TAG, " print source uri = {}" + source.get().getUri());
    But it only locate where .jar files position, and if  .jar file is not in the same directory with source directory, it became useless
    Example:
    Jar file position: out\soong\.intermediates\frameworks\opt\telephony\telephony-common\android_common\jarjar\telephony-common.jar
    Source file: frameworks\base\core\java\android\os\Registrant.java 
    So when there is a rule vialation, how could I show the source java path ?
    Hoping for your reply, thanks very much!

**Comment by codecholeric** [comment]
Sorry for the late reply!! I'm not sure I fully understand the problem. The source within a JAR file should be something like `jar:file:///some/folder/my-jar.jar!/my/app/SomeClass.class`. So it shows you where the bytecode comes from.
If you're more interested in the source code location you could also try

```
JavaClass.getSourceCodeLocation()
```

Have you tried that yet?

**Comment by zhangchunzhao12** [comment]
Yes , this could help my issue ,thanks very much!
