### ISSUE TITLE
Improve ArchRule to test if a test method is in a properly named test class

### ISSUE THREAD

**Issue by DManstrator** [TNG/ArchUnit#830]
Hello,

in the past it happend several times that Test methods were in classes with improper naming. Due to that, those tests were not executed in the CI and the mistakes were unnoticed for a long time.

In order to face that, I wrote an ArchRule to check for that:

```java
@ArchTest
public static final ArchRule checkTestMethodsShouldBeInProperTestClasses =
        ArchRuleDefinition.methods()
                .that()
                .areMetaAnnotatedWith(Test.class)
                .should()
                .beDeclaredInClassesThat().haveSimpleNameStartingWith("Test").orShould()
                .beDeclaredInClassesThat().haveSimpleNameStartingWith("IT").orShould()
                .beDeclaredInClassesThat().haveSimpleNameEndingWith("Test").orShould()
                .beDeclaredInClassesThat().haveSimpleNameEndingWith("Tests").orShould()
                .beDeclaredInClassesThat().haveSimpleNameEndingWith("TestCase").orShould()
                .beDeclaredInClassesThat().haveSimpleNameEndingWith("IT").orShould()
                .beDeclaredInClassesThat().haveSimpleNameEndingWith("ITCase")
                .as("Test methods should be in proper Test classes.");
```

My question is if that code can be optimized since I don't think I do it right with using `beDeclaredInClassesThat` that many times.

I tried

```java
// Needs a DescribedPredicate and I don't know how to get it.
// SimpleNameStartingWithPredicate / SimpleNameEndingWithPredicate are private for example.
.beDeclaredInClassesThat().haveSimpleNameStartingWith("Test")
    .orShould(beDeclaredInClassesThat().haveSimpleNameStartingWith("IT"))

// Required type: ArchCondition<? super JavaMethod>
// Provided: ArchCondition<JavaClass>
.beDeclaredInClassesThat().haveSimpleNameStartingWith("Test")
    .orShould(haveSimpleNameStartingWith("IT"))
```

but both are not working as explained in the code comments.

Can you perhaps tell me how I can improve it or is that already the intended way?

Kind regards,

Daniel

**Comment by hankem** [comment]
You probably want to use [the variant of `beDeclaredInClassesThat` that accepts a `DescribedPredicate`](https://javadoc.io/doc/com.tngtech.archunit/archunit/latest/com/tngtech/archunit/lang/syntax/elements/MembersShould.html#beDeclaredInClassesThat(com.tngtech.archunit.base.DescribedPredicate)) instead of the fluent API:

<details><summary>static imports</summary>

```java
import static com.tngtech.archunit.core.domain.JavaClass.Predicates.simpleNameEndingWith;
import static com.tngtech.archunit.core.domain.JavaClass.Predicates.simpleNameStartingWith;
import static com.tngtech.archunit.lang.conditions.ArchPredicates.have;
import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.methods;
```

</details>

```java
ArchRule testMethodsShouldBeInProperTestClasses = methods()
        .that().areMetaAnnotatedWith(Test.class)
        .should().beDeclaredInClassesThat(have(
                simpleNameStartingWith("Test")
                        .or(simpleNameStartingWith("IT"))
                        .or(simpleNameEndingWith("Test"))
                        .or(simpleNameEndingWith("Tests"))
                        .or(simpleNameEndingWith("TestCase"))
                        .or(simpleNameEndingWith("IT"))
                        .or(simpleNameEndingWith("ITCase"))
        ));
```
(If you still want to overwrite the rule's `description` with `.as("Test methods should be in proper Test classes.")`, you can even drop the `have` method call, which is just syntactic sugar.)

**Comment by DManstrator** [comment]
Hello Manfred,

thank you for your fast response. Also thanks for the code and the explanation, it works perfectly as expected. :)

I added the `as` back and left the `have` there since it's - as you said - smoother to read.

For everyone who is wondering about the String values: They are defined by Sonar ([java:S3577](https://rules.sonarsource.com/java/RSPEC-3577)).

Thanks again. :)
