### ISSUE TITLE
how to know if a JavaMethod is a lambda or not ?

### ISSUE THREAD

**Issue by vincent-fuchs** [TNG/ArchUnit#839]
Hi,

I see that since v0.23 (especially https://github.com/TNG/ArchUnit/pull/649) , we should be able to know if a given method is a lambda or not, however, I am a bit struggling. 

The way I do it right now is based on the method name : 

```java
  DescribedPredicate<JavaMethod> areNotLambdas =
      new DescribedPredicate<JavaMethod>("are not lambda"){
        @Override
        public boolean apply(JavaMethod input) {
          return !input.getName().contains("lambda$new");
        }
      };  
```
but I am quite sure this is not the right way ;-) 

I am inspecting the methods available on JavaMethod, but I am not finding something that would help me achieve the same but in a more robust way. 

what is the recommended approach here ? 

thanks

**Comment by codecholeric** [comment]
#649 only deals with method references, not lambdas :thinking: So it doesn't really add anything to help with this. I think at the moment your approach actually is the only possible way :grimacing: 
Can you tell me the use case though? Because we're at the moment working on making these methods vanish, i.e. in the future we would have

```
List<Target> origin() {
  return someList.stream().filter(e -> target(e)).collect(toList());
}

private Target target(Element e) {
  // ...
}
```

reporting a single `JavaMethodCall` from `origin` to `target` (i.e. the `lambda$...` methods would pretty much vanish from the import). We thought that that would match all typical use cases (the alternative would be an additional type of "lambda dependency" or sth. like that). Do you have a use case where you actually need this info, that a lambda is involved?

**Comment by vincent-fuchs** [comment]
yes, I have a use case - maybe you'll actually think of another solution that makes my request irrelevant.

You can have a look at https://github.com/societe-generale/arch-unit-build-plugin-core/pull/55/files : 

- I have a rule (https://github.com/societe-generale/arch-unit-build-plugin-core/blob/master/src/main/java/com/societegenerale/commons/plugin/rules/DontReturnNullCollectionTest.java ) that checks that methods that return List or Set, are annotated with `@Nonnull `

- this rule works well, except when there are lambdas. See below class :  

```
public class ObjectWithLambdasReturningListsInside {

	private final Supplier<List<Object>> someCache;

	public ObjectWithLambdasReturningListsInside(Supplier<List<Object>> someSupplier) {

		someCache =  Suppliers.memoizeWithExpiration(
				()-> someSupplier.get(),
				6, TimeUnit.HOURS);

	}
}
```

Archunit "sees" a method returning a List here, and the rule fails. The "workaround" to make the rule pass is to replace the lamba with an anonymous inner class, on which I can put the `@Nonnull` annotation... I'd rather make the rule slightly more lenient and avoid to consider lambdas in that case ;-)

**Comment by codecholeric** [comment]
Yes, but this sounds to me like the problem is that the synthetic `lambda$` methods actually are there at all, right? If we remove those methods altogether (making it a method call from the method that defines the lambda), then your problem would vanish, wouldn't it?

**Comment by vincent-fuchs** [comment]
I am not sure I understand what you mean..

If I don't check if the method is a lambda, then this will fail (same as my example before, slightly rewritten) :

```java
public class ObjectWithLambdasReturningListsInside {

	private final Supplier<List<Object>> someCache;

	public ObjectWithLambdasReturningListsInside(ListProvider someListProvider) {
		someCache =  Suppliers.memoizeWithExpiration(
				()-> someListProvider.getObjectsFromSource(),
				6, TimeUnit.HOURS);
	}
	
}
```

and this will also fail - is it your proposal ? :  

```java
public class ObjectWithLambdasReturningListsInside {

	private final ListProvider someListProvider;

	private final Supplier<List<Object>> someCache;

	public ObjectWithLambdasReturningListsInside(ListProvider someListProvider) {
		this.someListProvider=someListProvider;

		someCache =  Suppliers.memoizeWithExpiration(
				()-> internalCalltoGetObjects(),
				6, TimeUnit.HOURS);
	}

	@Nonnull
	private List<Object> internalCalltoGetObjects(){
		return someListProvider.getObjectsFromSource();
	}
}
```

message is `Method <com.societegenerale.aut.main.ObjectWithLambdasReturningListsInside.lambda$new$0()> is not annotated with @Nonnull`


to make the rule pass without checking if a method is a lambda in the rule , I have to write the code like :

```java
public class ObjectWithLambdasReturningListsInside {

	private final ListProvider someListProvider;

	private final Supplier<List<Object>> someCache;

	public ObjectWithLambdasReturningListsInside(ListProvider someListProvider) {
		this.someListProvider=someListProvider;

		someCache =  Suppliers.memoizeWithExpiration(

				new com.google.common.base.Supplier<List<Object>>() {
					@Nonnull
					@Override
					public List<Object> get() {
						return  someListProvider.getObjectsFromSource();
					}
				}
				,
				6, TimeUnit.HOURS);
	}
}
```
otherwise, I need to check if it's a lambda and apply the check only if it's not.

does that help ?

**Comment by codecholeric** [comment]
Yes, I think I understand what you mean, but with my proposal there would not be any method `ObjectWithLambdasReturningListsInside.lambda$new$0()` anymore, thus there would also not be any need to exclude it or check if it is a lambda, no? :thinking: 
With the change as we intend it you would only have an access `ObjectWithLambdasReturningListsInside.<init>(..) -> internalCalltoGetObjects()`, the methods of `ObjectWithLambdasReturningListsInside` would not contain any `lambda$...` methods anymore.

**Comment by vincent-fuchs** [comment]
great, thanks ! I will keep my "hack" for now, and when your change gets released, I'll see if I can remove the hack and it works "naturally"
