### ISSUE TITLE
Onion architecture check not working as expected (always passing)

### ISSUE THREAD

**Issue by husam-e** [TNG/ArchUnit#842]
In a Kotlin-only project, I have a test set up as follows:

Dependency: `com.tngtech.archunit:archunit-junit5:0.23.1`

```
@AnalyzeClasses(
    packages = ["com.myapp.svc.."],
    importOptions = [ImportOption.DoNotIncludeTests::class]
)
class ArchitectureConstraintTest {

    // other test cases

    @ArchTest
    fun `Onion architecture`(importedClasses: JavaClasses) {
        // println("importedClasses: $importedClasses")
        val rule = Architectures.onionArchitecture()
            .domainModels("..api..", "..domain..model..")
            .domainServices("..service..")
            .applicationServices("..routing..")
            .adapter("webserver", "..webserver..")

        rule.check(importedClasses)
    }

    @ArchTest
    fun `Onion architecture dupe layers - should fail`(importedClasses: JavaClasses) {
        // println("importedClasses: $importedClasses")
        val rule = Architectures.onionArchitecture()
            .domainModels("..api..", "..domain..model..")
            .domainServices("..routing..") // dupe of below
            .applicationServices("..routing..")
            .adapter("webserver", "..webserver..")

        rule.check(importedClasses)
    }

    @ArchTest
    fun `Onion architecture flipped layers - should fail`(importedClasses: JavaClasses) {
        // println("importedClasses: $importedClasses")
        val rule = Architectures.onionArchitecture()
            .domainModels("..api..", "..domain..model..")
            .domainServices("..routing..") // flipped
            .applicationServices("..service..") // flipped
            .adapter("webserver", "..webserver..")

        rule.check(importedClasses)
    }
```

And they all pass! The layers aren't empty as it would fail if they were (confirmed by playing around with `.withOptionalLayers(true)`).

Any ideas as to why?

**Comment by husam-e** [comment]
Sure! Let me put together a code sample. In general though I would expect that if test case #1 above passes, by definition the others should fail, so long as `..service..` and `..routing..` are mutually exclusive packages.

**Comment by codecholeric** [comment]
Well, if you e.g. only have classes without any dependencies it would always pass, no matter how the components are defined :wink: But to debug having a little sample makes is a lot simpler! (there are of course automated tests for the onion architecture, so I'm pretty sure it doesn't always report no violations :man_shrugging:)

**Comment by codecholeric** [comment]
I'm going to close this for now as there has not been any activity for quite a while. Feel free to reopen if you still have the problem and want to supply a little example!
