### ISSUE TITLE
[How to] Do whitelist access to same class (private) methods

### ISSUE THREAD

**Issue by sebarthel89** [TNG/ArchUnit#871]
We use a layered architecture where one layer is called "application". You might know that from a domain driven design package structure, which comes with layers for interfaces, application, domain and infrastructure.

We have the following code to do not allow access from classes with suffix `ApplicationService` to other classes called `ApplicationService`.

```
            ArchRuleDefinition.noClasses()
                .that()
                .resideInAnyPackage("${assertions.basePackageName}..")
                .and()
                .haveSimpleNameEndingWith(settings.applicationServiceSuffix)
                .should()
                .accessClassesThat()
                .haveSimpleNameEndingWith(settings.applicationServiceSuffix)
```

This worked nicely with version `0.11.0`. Now, we updated to version `0.23.0` which causes problems. The presented rule shows violation method calls of the same class. The following class violates the rule:

```
internal class SelfAccessPrivateMethodApplicationService() {

    fun method() {
        privateMethod()
    }

    private fun privateMethod() {}

}
```

To be concrete, it violates because the method `method` calls a method `privateMethod` of a class with the suffix `ApplicationService`, that is the same class. We would like to exclude this rule violating for any access within the same class that worked like that in previous versions.

Maybe I do miss something here that is now available in newer version. I would appreciate suggestions or maybe it's a bug?

Thanks in advance !

**Comment by hankem** [comment]
This was a conscious breaking change with [ArchUnit 0.12.0](https://github.com/TNG/ArchUnit/releases/tag/v0.12.0) for #209.

You can use a custom [ArchCondition](https://javadoc.io/doc/com.tngtech.archunit/archunit/latest/com/tngtech/archunit/lang/ArchCondition.html) that excludes accesses to self:

```java
// ...
.should(new ArchCondition<JavaClass>("access other classes that have simple name ending with Service") {
    @Override
    public void check(JavaClass javaClass, ConditionEvents events) {
        javaClass.getAccessesFromSelf().stream().filter(access ->
                !access.getTargetOwner().equals(javaClass) && access.getTargetOwner().getName().endsWith("Service")
            )
            .forEach(access -> events.add(SimpleConditionEvent.satisfied(javaClass, access.getDescription())));
    }
});
```

**Comment by sebarthel89** [comment]
thank you !
