### ISSUE TITLE
not finding the class with reflect() , when inspecting its fields

### ISSUE THREAD

**Issue by vincent-fuchs** [TNG/ArchUnit#872]
Hi,

I am facing an iissue using v0.23.1 - I've found a workaround, but I would like to know if I am missing something or not, and improve my knowledge on how archUnit works internally 

I have a predicate like below (I added the Sysout to try to understand what was going on, because I was not able to reproduce in a unit test) : the goal is to get all the methods of a given class, and check if these methods return either a List or a Set :

https://github.com/societe-generale/arch-unit-build-plugin-core/blob/fd45bd513e902984a7ecca7c316de620f65311fe/src/main/java/com/societegenerale/commons/plugin/rules/DontReturnNullCollectionTest.java#L53-L63

 ```java
 DescribedPredicate<JavaMethod> returnCollections =
      new DescribedPredicate<JavaMethod>("return collections"){
        @Override
        public boolean apply(JavaMethod input) {

          System.out.println("about to apply on "+input.getFullName());

          JavaClass returnedJavaClass = input.getReturnType().toErasure();
          System.out.println("\t returned class "+returnedJavaClass.getFullName());

          Class returnedClass = returnedJavaClass.reflect();

          return returnedClass.equals(List.class) || returnedClass.equals(Set.class) ;

        }
      };

ArchRule rule = methods().that(returnCollections)...

rule.check(classesToCheck);
```

The first class that gets analyzed is a nested class, the Lombok generated builder on a regular class : 

    my.project.domain.models.Partner$PartnerBuilder

and when running it, I get this log and error : 

> about to apply on my.project.domain.models.Partner$PartnerBuilder.supplierNumber(java.lang.Long)
>          returned class my.project.domain.models.Partner$PartnerBuilder
> 
> com.tngtech.archunit.base.ArchUnitException$ReflectionException: java.lang.ClassNotFoundException: my.project.domain.models.Partner$PartnerBuilder
>         at com.tngtech.archunit.core.domain.JavaClassDescriptor$From$AbstractClassDescriptor.resolveClass(JavaClassDescriptor.java:177)
>         at com.tngtech.archunit.core.domain.JavaClass$ReflectClassSupplier.get(JavaClass.java:2628)
>         at com.tngtech.archunit.core.domain.JavaClass$ReflectClassSupplier.get(JavaClass.java:2623)
>         at com.tngtech.archunit.thirdparty.com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
>         at com.tngtech.archunit.core.domain.JavaClass.reflect(JavaClass.java:1440)
>         at com.societegenerale.commons.plugin.rules.DontReturnNullCollectionTest$2.apply(DontReturnNullCollectionTest.java:78)
> ...
> Caused by: java.lang.ClassNotFoundException: my.project.domain.models.Partner$PartnerBuilder
>         at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
>         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
>         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
>         at java.base/java.lang.Class.forName0(Native Method)
>         at java.base/java.lang.Class.forName(Class.java:398)
>         at com.tngtech.archunit.core.domain.JavaClassDescriptor$From$AbstractClassDescriptor.classForName(JavaClassDescriptor.java:183)

What I don't understand is that Archunit was able to find the methods on the class, like `supplierNumber(java.lang.Long)`, so the class IS there. but somehow when calling `reflect()` on it, it's not found (the javadoc indeed says that _This method will throw an exception, if the respective Class or any of its dependencies can't be found on the classpath._ )

is it normal ?

I ended up rewriting the predicate so that I use `reflect()` only on the implemented interfaces, which happens a lot less than the types returned by the methods :   

```java

    DescribedPredicate<JavaMethod> returnCollections =
      new DescribedPredicate<JavaMethod>("return collections"){
        @Override
        public boolean apply(JavaMethod input) {

          JavaClass returnedJavaClass = input.getReturnType().toErasure();

          return returnedJavaClass.getAllRawInterfaces().stream()
              .anyMatch(implementedInterface -> implementedInterface.reflect().equals(Collection.class));
          
        }
      };
```

the implementation is actually probably better, but still I am curious as to why the other implementation doesn't work.

any idea ?

Thanks

**Comment by hankem** [comment]
I don't know why the ClassLoader doesn't like to resolve `Class.forName("my.project.domain.models.Partner$PartnerBuilder")` (you can check whether that works for you; I think that's an issue with lombok independent of ArchUnit) – but the good news is that you don't need to `reflect` the `JavaClass` for your usecase:
```java
         Class returnedClass = returnedJavaClass.reflect();
         return returnedClass.equals(List.class) || returnedClass.equals(Set.class) ;
```
can be simplified to
```java
        return returnedJavaClass.isEquivalentTo(List.class) || returnedJavaClass.isEquivalentTo(Set.class) ;
```

**Comment by codecholeric** [comment]
This seems to be a mismatch between the classpath and the imported java classes. If it is *normal* depends completely on the way how you import classes. Say you do

```
importer.importPath("/some/file/path/on/my/drive")
```

Then it is very likely, that you get this exception, because the `ClassLoader` you're running your tests with does not know those classes. If you on the other hand import via

```
importer.importPackages("some.pkg")
```

Then it's quite unlikely, because then the classes are searched exactly on the classpath of your `ClassLoader`. Things might change though, if you have any non-standard class loading there.

Other than that as @hankem said, you should barely ever need `reflect()`. In the past it was useful for missing features, like when ArchUnit didn't support generics yet. But meanwhile ArchUnit supports almost all the attributes you could query via Reflection. Note also, that a rule using `reflect()` is substantially slower than one that just uses ArchUnit native versions to achieve the same.

**Comment by vincent-fuchs** [comment]
Thanks a lot to both of you ! I've made the change https://github.com/societe-generale/arch-unit-build-plugin-core/commit/d7534dd86652d619376e65965ea32da118862df9

**Comment by codecholeric** [comment]
Cool! But are you sure `isAssignableFrom` is what you want? This is the same as the Reflection API, i.e.

```
someClass.isAssignableFrom(Collection.class) => Collection instance of someClass
```

In other words, this should also return `true` if `someClass == Object.class` for example. I don't know the context but I was just wondering if you actually wanted `isAssignableTo(..)` instead? :thinking:

**Comment by vincent-fuchs** [comment]
argh, you may be right... I've just tried with isAssignableTo , and my tests are still passing. So I need to add more tests to be clearer on the expectation : using one of them should fail !

Thanks a lot !

**Comment by hankem** [comment]
Hehehe, I've just yesterday seen a statement about testing ArchUnit tests in [this blog](https://www.mobileit.cz/Blog/Pages/arch-unit-1.aspx#:~:text=Test%20the%20tests) pointed out by https://github.com/TNG/ArchUnit/issues/668#issuecomment-1136029518... 😀

**Comment by vincent-fuchs** [comment]
actually, it's still not clear.. I've put some changes in a branch, and tried with both `isAssignableTo `and `isAssignableFrom`, and I get the same result (both passing and both same Sysout output), when executing https://github.com/societe-generale/arch-unit-build-plugin-core/blob/995b868e745bfd14af3a3c25b4b6a666b43939ec/src/test/java/com/societegenerale/commons/plugin/rules/DontReturnNullCollectionTestTest.java : 


> nb implemented interfaces : 2. is java.util.List a collection ? true
> nb implemented interfaces : 2. is java.util.List a collection ? true
> nb implemented interfaces : 2. is java.util.List a collection ? true
> nb implemented interfaces : 2. is java.util.List a collection ? true
> nb implemented interfaces : 2. is java.util.List a collection ? true
> nb implemented interfaces : 2. is java.util.Set a collection ? true
> nb implemented interfaces : 0. is com.societegenerale.aut.main.lombok_builder.ObjectWithLombokBuilder$ObjectWithLombokBuilderBuilder a collection ? false
> nb implemented interfaces : 0. is com.societegenerale.aut.main.lombok_builder.ObjectWithLombokBuilder a collection ? false
> nb implemented interfaces : 3. is java.lang.String a collection ? false
> nb implemented interfaces : 0. is com.societegenerale.aut.main.lombok_builder.ObjectWithLombokBuilder$ObjectWithLombokBuilderBuilder a collection ? false
> nb implemented interfaces : 2. is java.util.List a collection ? true
> nb implemented interfaces : 0. is com.societegenerale.aut.main.lombok_builder.ObjectWithLombokBuilder$ObjectWithLombokBuilderBuilder a collection ? false
> nb implemented interfaces : 0. is com.societegenerale.aut.main.lombok_builder.ObjectWithLombokBuilder a collection ? false
> nb implemented interfaces : 3. is java.lang.String a collection ? false
> nb implemented interfaces : 0. is com.societegenerale.aut.main.lombok_builder.ObjectWithLombokBuilder$ObjectWithLombokBuilderBuilder a collection ? false
> nb implemented interfaces : 2. is java.util.List a collection ? true
> nb implemented interfaces : 2. is java.util.Set a collection ? true
> nb implemented interfaces : 3. is java.lang.String a collection ? false
> nb implemented interfaces : 0. is boolean a collection ? false
> nb implemented interfaces : 0. is boolean a collection ? false
> nb implemented interfaces : 0. is int a collection ? false
> nb implemented interfaces : 3. is java.lang.String a collection ? false
> nb implemented interfaces : 1. is com.societegenerale.aut.main.ObjectWithMethodsReturningInterfaceOtherThanCollections$SomeImplementation a collection ? false
> nb implemented interfaces : 0. is java.lang.Object a collection ? false
> nb implemented interfaces : 1. is com.societegenerale.aut.main.ObjectWithMethodsReturningInterfaceOtherThanCollections$SomeImplementation a collection ? false
> nb implemented interfaces : 0. is java.lang.Object a collection ? false
> nb implemented interfaces : 2. is java.util.List a collection ? true
> nb implemented interfaces : 2. is java.util.List a collection ? true
> nb implemented interfaces : 2. is java.util.Set a collection ? true

So yes, given your explanation, we probably need `isAssignableTo`.. but I am not clear in which case it would fail when using `isAssignableFrom `

**Comment by vincent-fuchs** [comment]
because of the way my rule is implemented, I don't think I will be able to find a way to prove it through a test, even if one option is "truer" than the other, as you pointed out : 

```java
DescribedPredicate<JavaMethod> returnCollections =
      new DescribedPredicate<JavaMethod>("return collections"){
        @Override
        public boolean apply(JavaMethod input) {

          JavaClass returnedJavaClass = input.getReturnType().toErasure();

          return returnedJavaClass.getAllRawInterfaces().stream()
              .anyMatch(implementedInterface -> implementedInterface.isAssignableTo(Collection.class));

        }
      };
```

I've tried with a method returning an Iterable, but Iterable has no parent interface, so the stream of raw interfaces is empty and nothing matches. It's not seen as a collection - which is correct. so in that case, using either `isAssignableTo `or `isAssignableFrom` is the same, because it's not called anyway ;-/
