### ISSUE TITLE
Docs: incorrect/outdated reference to `areSubtypeOf` static method

### ISSUE THREAD

**Issue by perlun** [TNG/ArchUnit#874]
The following Javadoc example:

https://github.com/TNG/ArchUnit/blob/a96bf1e90d9ed232b7e86e268539b4313c18725d/archunit/src/main/java/com/tngtech/archunit/lang/syntax/elements/MembersThat.java#L476-L479

..refers to a method `areSubtypeOf()`, but no such method seems to be defined in ArchUnit AFAICT. I was thinking about submitting a PR but I don't even know what this should be replaced with, so it's probably better if you fix this properly @codecholeric. :slightly_smiling_face:

**Comment by codecholeric** [comment]
I think this was just an example, so I assumed `areSubtypeOf` to be some custom predicate. But I see that it might be a little bit confusing :wink: So I'll just replace it with `assignableTo` then and also replace `Object.class` by something that makes more sense :joy:

**Comment by codecholeric** [comment]
-> https://github.com/TNG/ArchUnit/pull/876/commits/474988e83cca2fcab34ef65eaf7421e407dc8eb1
