### ISSUE TITLE
ArchUnit: how can one silence references to arrays of basic types for method mayOnlyAccessLayers(...)?

### ISSUE THREAD

**Issue by mmoser18** [TNG/ArchUnit#887]
For a big GWT-based application I am defining an architecture check to prevent that our junior programmers accidentally reference classes that are not GWT-serializable and the resulting objects then can not make it "over the wire" (which then throws exceptions at runtime).

For this I am using a layer-check like so:
```
	@ArchTest
	void checkGWTAccess(JavaClasses classes) {
		LayeredArchitecture layers = Architectures.layeredArchitecture()
			.layer("Client").definedBy("..client..")
			.layer("Shared").definedBy("..shared..")
			... <many entries omitted here> ...
			;

		ArchRule rule = layers
			.whereLayer("Client").mayOnlyAccessLayers("Shared", "DomDtos", "DomBase", "DomConfig",  								
			                                          ... <many entries omitted here> ...
			                                         );
			;
		rule.check(classes);
```

"In principle" this works ok EXCEPT that I am still getting errors for all fields that are arrays of basic types or collections of basic types (i.e. e.g. `int[] digits;`, `char[] buffer;`, `List<Integer> allowedValues;`) as well as methods returning such arrays or collections (i.e. e.g. `int[] methodA(...) {...}`, `String[] methodB(...) {...}`, `List<Character> methodC(...) {...}`, etc.).

These error read e.g.: 
```
Field <com.example.client.ui.components.converter.TimeFieldConverter.timeNumberDigits> has type <[I> in (TimeFieldConverter.java:0)
```

IMHO this is a bug in ArchUnit. I can not fancy any reason arrays of basic types should possibly violate any layer-check rule. 

In case this is NOT a bug: 
How can one exclude these types from a `<layer>.mayOnlyAccessLayers(...)`-check? 

Or - alternatively - can one *include* these types to the list of allowed layers (if it's possible to identify the and/or declare them as "layer")?

The purpose is simply, to avoid getting any rule violations for these references, so that the tests run green.

**Comment by codecholeric** [comment]
Yes, `LayeredArchitecture` is missing an option to specify how to deal with dependencies, similar to `PlantUmlArchCondition`. You can probably find an answer and how to mitigate your problem here though ->  #841
Does that help you?

**Comment by mmoser18** [comment]
Re-reading the referenced append I finally found an expression that helped:

I added the following clause to the layeredArchitecture()-definition:
```
			.ignoreDependency(DescribedPredicate.alwaysTrue(), JavaClass.Predicates.simpleNameContaining("["))
```
... and that did the trick!  :-)

**Comment by mmoser18** [comment]
Hi again - pardon my ignorance, but how do I 'simply ignore package ""'? 

My own solution was:
`.ignoreDependency(DescribedPredicate.alwaysTrue(), JavaClass.Predicates.simpleNameContaining("[]"))`

but triggered by your BTW-remark I tried your suggestion and instead added
`.ignoreDependency(DescribedPredicate.alwaysTrue(), JavaClass.Predicates.simpleName(""))` but that did not work. 

With the latter I am still getting errors like `Field ... has type <[I> in (<code location here>)`.

How would I ignore package "" correctly?

**Comment by codecholeric** [comment]
FYI: With the next release you should simply be able to write

```
layeredArchitecture().consideringOnlyDependenciesInAnyPackage("com.myapp..")
```

or 

```
layeredArchitecture().consideringOnlyDependenciesInLayers()
```

That should also solve the problem without any custom ignore...
