### ISSUE TITLE
Make `PlantUmlArchCondition.Configuration` public

### ISSUE THREAD

**Issue by tmohme** [TNG/ArchUnit#888]
I'm using ArchUnit capability to check rules expressed by PlantUML syntax and I'm generally really happy with this.

There is just one minor issue: I get a Kotlin compile-warning for code that is shown in an example in the User Guide.

```
classes().should(adhereToPlantUmlDiagram(myDiagram, consideringAllDependencies()))
```

gives me

```
Type PlantUmlArchCondition.Configuration! is inaccessible in this context due to: public/*package*/ interface Configuration defined in com.tngtech.archunit.library.plantuml.PlantUmlArchCondition
```

It took me a moment to understand the root cause: While both functions exchanging the `Condition` are public, the interface itself is not public but package protected.  
It works because one function's result is directly used as parameter for the other (so I don't need to import `Condition`), but it would fail if I wanted store the intermediate result of `consideringAllDependencies()` in a typed variable.

It would be nice to get rid of this warning.

**Comment by codecholeric** [comment]
Thanks for raising the issue! Yes, this has already been mentioned here https://github.com/TNG/ArchUnit/issues/826#issuecomment-1078919435

I'm a little confused why it's a problem in Kotlin and not in Java :man_shrugging: (but in Kotlin it also still works if you use the public subclasses, there just is a warning, right? At least for me)

Originally it was intended like this, that you couldn't directly use or implement the base interface as a user, but only the specific three subclasses. I.e. I didn't want this as a public API for users to extend, but instead only use those 3 predefined ones. But maybe that was also a little too restrictive, so I'll look into it if it's fine to just make it public or if I want to refactor something then first :+1:
