### ISSUE TITLE
Add support for beVolatile and notBeVolatile for Fields

### ISSUE THREAD

**Issue by phermsdorf** [TNG/ArchUnit#890]
Hi,

I wanted to check a OSGi Component Definition which looks like this

```
@Component
public class SomeService {

	@Reference(policy = ReferencePolicy.DYNAMIC)
	private  IRemoteServiceRegistration registration;

	... 
}
```

The Problem here is, that the member does need to be volatile otherwise this definition will not work at runtime. Sadly the Eclipse tooling does not detect this problem and I wanted to validate this with an ArchUnit Test like this:

`fields().that().areAnnotatedWith(Reference.class).should().beVolatile()`

like `beStatic()` etc. but this seems not possible.

Is this known / intended / corret or is there another way of checking this?

Thank you!

Bye Peter

**Comment by codecholeric** [comment]
Thanks for raising the issue! Have you tried to use

```
fields().that().areAnnotatedWith(Reference.class).should().haveModifier(JavaModifier.VOLATILE)
```

? Or am I misunderstanding your problem? Except for visibility like public / package-private / ... this is typically the way to test for arbitrary modifiers that classes / members could have.

**Comment by phermsdorf** [comment]
Ah thanks! i did not knew this version.

Bonus Question: is there any way to check the `policy = ReferencePolicy.DYNAMIC` property from the above example?
Actually the volatile keyword is only required for dynamic references.

Thank you.

Bye Peter

**Comment by codecholeric** [comment]
Yes, you should be able to use the `areAnnotatedWith(predicate)` version and do it similar to here: https://github.com/TNG/ArchUnit/blob/main/archunit-integration-test/src/test/java/com/tngtech/archunit/PublicAPIRules.java#L316

**Comment by phermsdorf** [comment]
I can't get that to work (technically). 
I don't see where the overridden test method should come from in the DescribedPredicate type.
My IDE either.

?

**Comment by phermsdorf** [comment]
OK I got it to work lie this:

```
.areAnnotatedWith(new DescribedPredicate<JavaAnnotation<?>>("@%s(policy = %s)",
		Reference.class.getSimpleName(), "dynamic") {

	@Override
	public boolean apply(final JavaAnnotation<?> input) {
		return input.getRawType().isEquivalentTo(Reference.class) &&
				input.as(Reference.class).policy() == DYNAMIC;
	}
})

```
Thanks for the helpful pointers!

Bye Peter

**Comment by codecholeric** [comment]
Glad you got it to work, and yes, that's how I meant it :slightly_smiling_face: Note that there is also a more "lambda'y" factory method `DescribedPredicate.describe(description, annotation -> ...)` if you don't want to create an anonymous class for the predicate there.
