### ISSUE TITLE
Bug/Feature: inner lambda access is cumbersome

### ISSUE THREAD

**Issue by nbrugger-tgm** [TNG/ArchUnit#898]
When you create a rule like this: `ArchCondition<JavaMethod> accessMethodsThat(DescribedPredicate<? super JavaMember> predicate)`
for implementation, you need to call: 
```java
public void check(JavaMethod item, ConditionEvents events) {
    var accesses = new HashSet<>(item.getAccessesFromSelf());//<-- get the accesses
```
There is one problem if `item` contains a lambda
```java
void foo(){
    Optional.ofNullable(null).ifPresent(str -> System.out.println(str));
}
```
compiles down to
```java
void foo(){
    Optional.ofNullable(null).ifPresent(this::lambda$foo$0);
}
void lambda$foo$0(String str){
    sout(str);
}
```
So `item.getAccessesFromSelf()` will not contain the sysout call. (which is correct on bytecode level)

Per`se this is not too much of a problem since you will get something like as violation
``Method<lambda$foo$0> does access forbidden variable System.out``(pseudo message)

But in any more advanced example, this logic breaks:
```java
methods()
        .that().areNotAnnotatedWith(Deprecated.class)
        .should(not(accessMethodsThat(are(declaredIn(System.class))))
        .because("Who needs System");
```
(this rule itself is not very useful, but proves the point)

So we allow "bad" behaviour in `@Deprecated` methods, the problem is that even if `foo` is marked deprecated the compiled lambda function is not! Therefore, you cannot prevent failing the test without a workaround

**Comment by nbrugger-tgm** [comment]
Here is the workaround I use at the moment: (tested with JVM/OpenJDK 11)
```java
private Set<? extends JavaAccess<?>> getInnerLambdaAccesses(JavaMethod item) {
    var isLambda = lambdas();
    var innerLambdas = item.getOwner().getMethods().stream()
        .filter(isLambda::apply)
        .filter(lambda -> lambda.getName().contains(item.getName()))
        .collect(Collectors.toSet());
    return innerLambdas.stream()
        .map(JavaMethod::getAccessesFromSelf)
        .flatMap(Set::stream)
        .collect(Collectors.toSet());
}
public DescribedPredicate<JavaMethod> lambdas() {
    return new DescribedPredicate<>("lambdas") {
        @Override
        public boolean apply(JavaMethod javaMethod) {
            return javaMethod.getName().matches("lambda\\$.+\\$\\d+");//lambda$methodName$6
        }
    };
}
```
which can get all calls using this:
```java
var accesses = new HashSet<>(item.getAccessesFromSelf());
accesses.addAll(getInnerLambdaAccesses(item));
```

**Comment by hankem** [comment]
You're issue has already been addressed and should be solved with the next release:
After #847, the access to `System.out.println` will be mapped from `lambda$foo$0` to `foo`.

**Comment by nbrugger-tgm** [comment]
I see, sorry for the duplicate

**Comment by hankem** [comment]
No problem! 😉
