### ISSUE TITLE
Ensure order of code units is always the same

### ISSUE THREAD

**Issue by andrinmeier** [TNG/ArchUnit#937]
Is there a reliable way of ensuring the code units / members of a class are always written in the same order? For example, each class should have members written in the following order:

1. Static fields
2. Instance variables
3. Methods
4. Constructors

I've tried using the source code location feature but some code units always appear to have a line number of 0.

**Comment by codecholeric** [comment]
Sorry, I don't think this can be achieved with ArchUnit. Because member declarations in bytecode have no line numbers associated with them (only executable statements have). I think what you need for these cases is a source code analysis tool.

**Comment by andrinmeier** [comment]
No problem. Thank you for your answer!
