### ISSUE TITLE
`are(..)` clause for lang API

### ISSUE THREAD

**Issue by Vyom-Yadav** [TNG/ArchUnit#950]
So I was defining a rule like:
```java
fields()                                
    .that(ARE_NOT_SUPPRESSED)           
    .and()                              
    .areDeclaredInClassesThat()         
    .haveSimpleNameEndingWith("Util")   
    .should(BE_IMMUTABLE)               
    .andShould()                        
    .beFinal()                          
    .andShould()                        
    .beStatic();                       
```
`ARE_NOT_SUPPRESSED` and `BE_IMMUTABLE` are `DescribedPredicate` and `ArchCondition` respectively. Not I want to add another condition to the fields.
```java
fields()                                
    .that(ARE_NOT_SUPPRESSED)           
    .and()
    .are(NOT_ZERO_SIZE_ARRAY)   
    .and()                           
    .areDeclaredInClassesThat()         
    .haveSimpleNameEndingWith("Util")   
    .should(BE_IMMUTABLE)               
    .andShould()                        
    .beFinal()                          
    .andShould()                        
    .beStatic();   
```
But this is currently not possible, can't we make a `ArchCondition` like this?

I can still achieve this by modifying the `that(..)` clause, but I only want to keep one method to do a single task.

**Comment by hankem** [comment]
I guess that `NOT_ZERO_SIZE_ARRAY` is a `DescribedPredicate<JavaField>`?

You can use
```java
    fields()
            .that(ARE_NOT_SUPPRESSED.and(NOT_ZERO_SIZE_ARRAY))
            .and().areDeclaredInClassesThat() // ...
```
(If `ARE_NOT_SUPPRESSED` is a `DescribedPredicate<? super JavaField>`, you may have to add a cast `.<JavaField>forSubtype()`.)

By the way, there are static methods that allow you to add syntax words to more basic predicates. For instance, with
```java
import static com.tngtech.archunit.base.DescribedPredicate.not;
import static com.tngtech.archunit.lang.conditions.ArchPredicates.are;
```
you could use `DescribedPredicate`s `SUPPRESSED` and `ZERO_SIZE_ARRAY` to compose your rule:
```java
    fields()
            .that(are(not(SUPPRESSED)).and(are(not(ZERO_SIZE_ARRAY))))
            .and().areDeclaredInClassesThat() //...
```

**Comment by Vyom-Yadav** [comment]
@hankem Thanks a lot!

**Comment by hankem** [comment]
You're welcome, I'm glad if I could help!

By the way, I forgot to mention that you could also have composed your rule from multiple predicates on the rule-level like this:
```diff
         fields()
             .that(ARE_NOT_SUPPRESSED)
-            .and()
-            .are(NOT_ZERO_SIZE_ARRAY)
+            .and(NOT_ZERO_SIZE_ARRAY)
             .and()
             .areDeclaredInClassesThat() // ...
```
This is again where `ArchPredicates.`_`are`_ comes in handy for _syntactic_ sugar.
