### ISSUE TITLE
Problem with getRawReturnType and getRawParameterTypes when the objects are not in the same module

### ISSUE THREAD

**Issue by murilophilips** [TNG/ArchUnit#961]
I'm using IntelliJ Idea as my IDE, this will be relevant below.
We have implemented a number of archUnit rules and never had a problem with them. This is likely something I can't see, but I'm stumped.
As I said, I am working with modules in IntelliJ, but so far we always had our checked files belong in the same package and module. But moving forward we'll have three main modules: api, controller and core.
Today I tried moving two DTOs (Request and Response objects) from the core module to api, and ran my archUnit check, only to see the checks fail.
I investigated further, and when debugging I found out the JavaClass object I'm getting using getRawReturnType and getRawParameterTypes doesn't have the right numbers in fields, methods and such (it's all zero).
Here's the rule (the '**' shows my method)

```
ArchRuleDefinition.classes()
                .that().areAnnotatedWith(DatabaseServiceBean.class)
                .should(**haveAllOrderedParamsInTheirListedDto**(packagePath))
                .check(ArchUtils.importAllClassesInPackage(scopePathProvider.getMainClassesPath(), packagePath, excludedPaths));

```
Which resolves to

```
static ArchCondition<JavaClass> haveAllOrderedParamsInTheirListedDto(String packageName) {
        return new OrderedParamsChecker("have all ordered params in either the request or the response", packageName);
    }
```
and here's the OrderedParamsChecker, which extends ArchCondition:

```
 @Override
    public void check(final JavaClass javaClass, final ConditionEvents events) {
        javaClass.getMethods().forEach(method -> {
            final JavaClass response = method.getRawReturnType();
            final List<JavaClass> requestList = method.getRawParameterTypes();
            method.getAnnotations().forEach(annotation -> {
                final String[] paramNames = (String[]) annotation.get("orderedParamNames").get();
                Arrays.stream(paramNames).forEach(param -> {
                    if (!(inResponse(response, param) || inRequest(requestList, param))) {
                        events.add(SimpleConditionEvent.violated(javaClass,
                            "Parameter " + param + " not found in request/response objects in " + javaClass.getSimpleName()));
                    }
                });
            });
        });
    }


    private boolean inRequest(final List<JavaClass> requestList, final String fieldName) {
        for (final JavaClass request : requestList) {
            if (request.tryGetField(fieldName).isPresent()) {
                return true;
            }
        }
        return false;
    }

    private boolean inResponse(final JavaClass response, final String fieldName) {
        return response != null
            && !response.isEquivalentTo(Void.class)
            && response.tryGetField(fieldName).isPresent();
    }
```

I hope I was able to explain the issue, please let me know if you need more info on this and I can elaborate more.

Here's the message I get when moving the files to a different module in the IDE:
![image](https://user-images.githubusercontent.com/74658567/191258287-1ce04a43-b652-4916-b6e3-313f9085b5b4.png)

Here's the debugging screen when the classes are in the same module:
![image](https://user-images.githubusercontent.com/74658567/191264998-ae80a4dd-bb00-4032-8d10-a8cb19d6e6c8.png)

And here's when they're not: 
![image](https://user-images.githubusercontent.com/74658567/191265845-f441197d-d829-4ce8-bbb6-51f5753e686e.png)

Thanks in advance,
Murilo

**Comment by codecholeric** [comment]
To me this looks like an import problem :thinking: Because when ArchUnit can't find certain classes it will create some "stub" classes instead. So suppose you have a method

```
class Example {
  void example(SomeParam param) {}
}
```

And you move `SomeParam` out of reach (e.g. to some location that is not on the classpath of your test), then ArchUnit would see when importing `Example` "I need some type `SomeParam` but can't find it". In this case some stub class called `SomeParam` would be created that has only the minimal info that could be derived (e.g. class name, package name, etc.). Further things, like modifiers, can't be derived however. (you can read a little bit more about the problem in the [user guide](https://www.archunit.org/userguide/html/000_Index.html#_dealing_with_missing_classes)).

The symptoms you're showing me there (that IntelliJ complains some class is not accessible, that modifiers are missing from the debug output) points a little bit into this direction.

One important thing missing though is, is the class you're showing in your debug screenshot directly imported (i.e. part of `JavaClasses` from the import) or is it retrieved as a dependency (e.g. `JavaClass.getMethod(..).getRawParameterTypes()`). If it is the former, then my theory makes no sense I think. But if it's the latter it's a good possible explanation.

**Comment by hankem** [comment]
> this looks like an import problem

@murilophilips, you should check whether
```
ArchUtils.importAllClassesInPackage(scopePathProvider.getMainClassesPath(), packagePath, excludedPaths)
```
includes the relevant `JavaClass`es after the move.

**Comment by hankem** [comment]
If you have the `JavaClass response` already in your debugger, you could evaluate `response.isFullyImported()`.
The hypothesis is that you get `true` when the classes are in the same module, but `false` after the move.

**Comment by murilophilips** [comment]
Hey, @hankem Thanks for your reply, too. Funnily enough (I was expecting to see false) isFullyImported shows true. Now I wonder if the stub would do that.

**Comment by codecholeric** [comment]
Hmm, it should not, but just to make sure we're not having some internal problem here, do you think you could put a breakpoint into `com.tngtech.archunit.core.importer.ImportedClasses#stubClassOf` and debug it to see if you end up in that method?

**Comment by murilophilips** [comment]
I thought I should leave some closure before I call this done, because someone else might be looking for something similar.
Turns out we apply our ArchUnit checks from a gradle plugin that cycles through the modules and uses those as the starting points to run the rules and checks. Because of that, indeed the other modules are inaccessible, and there's no way to walk the tree upward. My options so far are creating a shortcut (via siglink in Linux or Windows) that allows the rule to see the objects it needs to, or creating a "merged" folder and then apply the rule to that folder instead.
Since this is really not an ArchUnit issue, I'm closing it. 
My sincerest thanks to all who helped me understand the problem and how to fix it. You're all awesome!
