### ISSUE TITLE
Is there any way to check if a JavaAccess belong to a method call?

### ISSUE THREAD

**Issue by zhangchunzhao12** [TNG/ArchUnit#990]
Is there any way to check if a `JavaAccess` belong to a method call?
Since we have a test code like :
I put `getString` mehod as parameter to method `test_aaa`, and I want to know `getString` invoking has some relating with method `test_aaa`
```java
class for_test{
    private String field1 = "Field1";
    private String field2 = "Field2";
    private String field3 = "Field3";
    private String field4 = "Field4";
    private void test_func() {
        test_aaa(getString(field1), 
                getString(field2),
                getString(field3),
                getString(field4));
    }
    private void test_aaa(String str1, String str2, 
                    String str3, String str4) {
        
    }
    private String getString(String str) {
        return str;
    }
}
```
And I test it like:
```java
        JavaClasses javaClasses = new ClassFileImporter().importClasses(for_test.class);
        for (JavaClass javaClass : javaClasses) {
            for (JavaAccess<?> access : javaClass.getAccessesFromSelf()) {
                Log.i(TAG, "test = {}", access.getDescription());
            }
        }
```
> test = Method <com.transsion.tools.for_test.test_func()> calls method <com.transsion.tools.for_test.getString(java.lang.String)> in (FwNonStubCodeDetectTest.java:236)
test = Method <com.transsion.tools.for_test.test_func()> calls method <com.transsion.tools.for_test.test_aaa(java.lang.String, java.lang.String, java.lang.String, java.lang.String)> in (FwNonStubCodeDetectTest.java:234)
test = Method <com.transsion.tools.for_test.test_func()> calls method <com.transsion.tools.for_test.getString(java.lang.String)> in (FwNonStubCodeDetectTest.java:237)
test = Method <com.transsion.tools.for_test.test_func()> calls method <com.transsion.tools.for_test.getString(java.lang.String)> in (FwNonStubCodeDetectTest.java:234)
test = Method <com.transsion.tools.for_test.test_func()> calls method <com.transsion.tools.for_test.getString(java.lang.String)> in (FwNonStubCodeDetectTest.java:235)

As a result, each `getString` take a different linenumber, I don't know how to regard it as parameter to method `test_aaa`;
Thanks for your helping!

**Comment by hankem** [comment]
ArchUnit does not give you information about a method call's parameter values, so you unfortunately cannot relate the `getString` method calls to the `test_aaa` method call.
