### ISSUE TITLE
How to forbidden method call?

### ISSUE THREAD

**Issue by weiwangmr** [TNG/ArchUnit#995]
In some cases we want to forbidden some method calls, but I can't find any this kind of usage. Did i miss something? or not support right now?

**Comment by weiwangmr** [comment]
noClasses seem not work on callMethod

**Comment by hankem** [comment]
[`callMethod`](https://javadoc.io/static/com.tngtech.archunit/archunit/1.0.0/com/tngtech/archunit/lang/syntax/elements/ClassesShould.html#callMethod(java.lang.Class,java.lang.String,java.lang.Class...)) works for me as I'd expect, e.g.
```java
@ArchTest
ArchRule noStringToString = noClasses().should().callMethod(String.class, "toString".toString());  // ← violation
```

Note that you need to specify the types if your method has parameters, e.g.:
```java
@ArchTest
ArchRule noStringConcat = noClasses().should().callMethod(String.class, "con".concat("cat"), String.class);  // ← violation
```
If you forget to specify that `String#concat` takes `String` parameter, the rule will not work:
```java
@ArchTest
ArchRule willNeverFail = noClasses().should().callMethod(String.class, "con".concat("cat"));  // ← "apparently okay"
```

If `callMethod` doesn't work for you, you probably need to give more details.
